// ============================================================
// FerrumEngine Effects Library - Lightweight index (no CSS strings)
// For fast initial load. Full CSS loaded on demand.
// Auto-generated — do not edit manually.
// ============================================================

export interface FerrumEffectIndex {
  name: string;
  className: string;
  category: string;
  displayType: string;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
}

export interface Stats {
  total: number;
  categories: number;
  unique: number;
  keyframes: number;
}

// Categories extracted from ferrum-effects-data.ts
export const categories: Category[] = [
  { id: "core-animations", name: "Core Animations", icon: "Sparkles" },
  { id: "hover", name: "Hover", icon: "MousePointer" },
  { id: "text", name: "Text", icon: "Type" },
  { id: "backgrounds", name: "Backgrounds", icon: "ImageIcon" },
  { id: "loaders", name: "Loaders", icon: "Loader2" },
  { id: "3d-transforms", name: "3D & Transforms", icon: "Move3D" },
  { id: "button-card", name: "Buttons & Cards", icon: "Zap" },
  { id: "forms", name: "Forms & Inputs", icon: "Eye" },
  { id: "navigation", name: "Navigation & UI", icon: "Box" },
  { id: "scroll-micro", name: "Scroll & Micro", icon: "Layers" },
  { id: "advanced", name: "Advanced", icon: "Crown" },
];

export const effects: FerrumEffectIndex[] = [
  { name: "3d Book", className: "rc-3d-book", category: "3d-transforms", displayType: "box" },
  { name: "3d Gallery", className: "rc-3d-gallery", category: "3d-transforms", displayType: "box" },
  { name: "3d Poster", className: "rc-3d-poster", category: "3d-transforms", displayType: "box" },
  { name: "Accordion 3d", className: "rc-accordion-3d", category: "3d-transforms", displayType: "box" },
  { name: "Apple Bounce Settle", className: "rc-apple-bounce-settle", category: "core-animations", displayType: "box" },
  { name: "Apple Elastic Scale", className: "rc-apple-elastic-scale", category: "core-animations", displayType: "box" },
  { name: "Apple Flip Spring", className: "rc-apple-flip-spring", category: "core-animations", displayType: "box" },
  { name: "Apple Frosted Vibrancy", className: "rc-apple-frosted-vibrancy", category: "advanced", displayType: "box" },
  { name: "Apple Material Thick", className: "rc-apple-material-thick", category: "advanced", displayType: "box" },
  { name: "Apple Material Thin", className: "rc-apple-material-thin", category: "advanced", displayType: "box" },
  { name: "Apple Sidebar Material", className: "rc-apple-sidebar-material", category: "advanced", displayType: "box" },
  { name: "Apple Squish In", className: "rc-apple-squish-in", category: "core-animations", displayType: "box" },
  { name: "Apple Squish Out", className: "rc-apple-squish-out", category: "core-animations", displayType: "box" },
  { name: "Apple Ultra Thin", className: "rc-apple-ultra-thin", category: "advanced", displayType: "box" },
  { name: "Apple Vibrancy Dark", className: "rc-apple-vibrancy-dark", category: "advanced", displayType: "box" },
  { name: "Apple Vibrancy Light", className: "rc-apple-vibrancy-light", category: "advanced", displayType: "box" },
  { name: "Ascii Rain", className: "rc-ascii-rain", category: "backgrounds", displayType: "box" },
  { name: "BG Animated Gradient", className: "rc-bg-animated-gradient", category: "backgrounds", displayType: "bg" },
  { name: "BG Concentric", className: "rc-bg-concentric", category: "backgrounds", displayType: "bg" },
  { name: "BG Conic Gradient", className: "rc-bg-conic-gradient", category: "backgrounds", displayType: "bg" },
  { name: "BG Diagonal Stripes", className: "rc-bg-diagonal-stripes", category: "backgrounds", displayType: "bg" },
  { name: "BG Dot Pattern", className: "rc-bg-dot-pattern", category: "backgrounds", displayType: "bg" },
  { name: "BG Gradient Pulse", className: "rc-bg-gradient-pulse", category: "backgrounds", displayType: "bg" },
  { name: "BG Gradient Sweep", className: "rc-bg-gradient-sweep", category: "backgrounds", displayType: "bg" },
  { name: "BG Grid Lines", className: "rc-bg-grid-lines", category: "backgrounds", displayType: "bg" },
  { name: "BG Hexagon", className: "rc-bg-hexagon", category: "backgrounds", displayType: "bg" },
  { name: "BG Lava Lamp", className: "rc-bg-lava-lamp", category: "backgrounds", displayType: "bg" },
  { name: "BG Mesh Gradient", className: "rc-bg-mesh-gradient", category: "backgrounds", displayType: "bg" },
  { name: "BG Noise", className: "rc-bg-noise", category: "backgrounds", displayType: "bg" },
  { name: "BG Plaid", className: "rc-bg-plaid", category: "backgrounds", displayType: "bg" },
  { name: "BG Radial Rays", className: "rc-bg-radial-rays", category: "backgrounds", displayType: "bg" },
  { name: "BG Stripes", className: "rc-bg-stripes", category: "backgrounds", displayType: "bg" },
  { name: "BG Sunburst", className: "rc-bg-sunburst", category: "backgrounds", displayType: "bg" },
  { name: "BG Sunset", className: "rc-bg-sunset", category: "backgrounds", displayType: "bg" },
  { name: "BG Triangles", className: "rc-bg-triangles", category: "backgrounds", displayType: "bg" },
  { name: "BG Zigzag", className: "rc-bg-zigzag", category: "backgrounds", displayType: "bg" },
  { name: "Blink", className: "rc-blink", category: "core-animations", displayType: "box" },
  { name: "Blueprint", className: "rc-blueprint", category: "advanced", displayType: "box" },
  { name: "Blur In Up", className: "rc-blur-in-up", category: "core-animations", displayType: "box" },
  { name: "Blur Out Down", className: "rc-blur-out-down", category: "core-animations", displayType: "box" },
  { name: "Book Open", className: "rc-book-open", category: "3d-transforms", displayType: "box" },
  { name: "Border Animated Dash", className: "rc-border-animated-dash", category: "button-card", displayType: "box" },
  { name: "Border Banner", className: "rc-border-banner", category: "button-card", displayType: "box" },
  { name: "Border Clip Path", className: "rc-border-clip-path", category: "button-card", displayType: "box" },
  { name: "Border Corner Brackets", className: "rc-border-corner-brackets", category: "button-card", displayType: "box" },
  { name: "Border Dashed Draw", className: "rc-border-dashed-draw", category: "button-card", displayType: "box" },
  { name: "Border Double Glow", className: "rc-border-double-glow", category: "button-card", displayType: "box" },
  { name: "Border Frame", className: "rc-border-frame", category: "button-card", displayType: "box" },
  { name: "Border Gradient Animated", className: "rc-border-gradient-animated", category: "button-card", displayType: "box" },
  { name: "Border Inset Glow", className: "rc-border-inset-glow", category: "button-card", displayType: "box" },
  { name: "Border Marching Ants", className: "rc-border-marching-ants", category: "button-card", displayType: "box" },
  { name: "Border Neon Pulse", className: "rc-border-neon-pulse", category: "button-card", displayType: "box" },
  { name: "Border Polaroid", className: "rc-border-polaroid", category: "button-card", displayType: "box" },
  { name: "Border Ribbon", className: "rc-border-ribbon", category: "button-card", displayType: "box" },
  { name: "Border Sticker", className: "rc-border-sticker", category: "button-card", displayType: "box" },
  { name: "Border Torn Paper", className: "rc-border-torn-paper", category: "button-card", displayType: "box" },
  { name: "Bounce In Down", className: "rc-bounce-in-down", category: "core-animations", displayType: "box" },
  { name: "Bounce In Left", className: "rc-bounce-in-left", category: "core-animations", displayType: "box" },
  { name: "Bounce In Right", className: "rc-bounce-in-right", category: "core-animations", displayType: "box" },
  { name: "Bounce In Up", className: "rc-bounce-in-up", category: "core-animations", displayType: "box" },
  { name: "Bounce Out", className: "rc-bounce-out", category: "core-animations", displayType: "box" },
  { name: "Bounce Rotate", className: "rc-bounce-rotate", category: "core-animations", displayType: "box" },
  { name: "Breathe", className: "rc-breathe", category: "core-animations", displayType: "box" },
  { name: "Button 3d Push", className: "rc-btn-3d-push", category: "button-card", displayType: "button" },
  { name: "Button Arrow Slide", className: "rc-btn-arrow-slide", category: "button-card", displayType: "button" },
  { name: "Button Border Draw", className: "rc-btn-border-draw", category: "button-card", displayType: "button" },
  { name: "Button Border Glow", className: "rc-btn-border-glow", category: "button-card", displayType: "button" },
  { name: "Button Bounce", className: "rc-btn-bounce", category: "button-card", displayType: "button" },
  { name: "Button Expand", className: "rc-btn-expand", category: "button-card", displayType: "button" },
  { name: "Button Fill Slide", className: "rc-btn-fill-slide", category: "button-card", displayType: "button" },
  { name: "Button Flip", className: "rc-btn-flip", category: "button-card", displayType: "button" },
  { name: "Button Glow", className: "rc-btn-glow", category: "button-card", displayType: "button" },
  { name: "Button Gradient", className: "rc-btn-gradient", category: "button-card", displayType: "button" },
  { name: "Button Icon Slide", className: "rc-btn-icon-slide", category: "button-card", displayType: "button" },
  { name: "Button Lift", className: "rc-btn-lift", category: "button-card", displayType: "button" },
  { name: "Button Liquid", className: "rc-btn-liquid", category: "button-card", displayType: "button" },
  { name: "Button Morph", className: "rc-btn-morph", category: "button-card", displayType: "button" },
  { name: "Button Neon", className: "rc-btn-neon", category: "button-card", displayType: "button" },
  { name: "Button Outline Fill", className: "rc-btn-outline-fill", category: "button-card", displayType: "button" },
  { name: "Button Press", className: "rc-btn-press", category: "button-card", displayType: "button" },
  { name: "Button Pulse", className: "rc-btn-pulse", category: "button-card", displayType: "button" },
  { name: "Button Ripple", className: "rc-btn-ripple", category: "button-card", displayType: "button" },
  { name: "Button Rotate", className: "rc-btn-rotate", category: "button-card", displayType: "button" },
  { name: "Button Shadow Push", className: "rc-btn-shadow-push", category: "button-card", displayType: "button" },
  { name: "Button Shine Sweep", className: "rc-btn-shine-sweep", category: "button-card", displayType: "button" },
  { name: "Button Skew", className: "rc-btn-skew", category: "button-card", displayType: "button" },
  { name: "Button Slide Bg", className: "rc-btn-slide-bg", category: "button-card", displayType: "button" },
  { name: "Button Sparkle", className: "rc-btn-sparkle", category: "button-card", displayType: "button" },
  { name: "Card Flip", className: "rc-card-flip", category: "3d-transforms", displayType: "card" },
  { name: "Card Flip Back", className: "rc-card-flip-back", category: "3d-transforms", displayType: "card" },
  { name: "Card Flip Inner", className: "rc-card-flip-inner", category: "3d-transforms", displayType: "card" },
  { name: "Card Glassmorphism", className: "rc-card-glassmorphism", category: "button-card", displayType: "card" },
  { name: "Card Gradient Border", className: "rc-card-gradient-border", category: "button-card", displayType: "card" },
  { name: "Card Hover Border", className: "rc-card-hover-border", category: "button-card", displayType: "card" },
  { name: "Card Hover Color", className: "rc-card-hover-color", category: "button-card", displayType: "card" },
  { name: "Card Hover Fade", className: "rc-card-hover-fade", category: "button-card", displayType: "card" },
  { name: "Card Hover Flip", className: "rc-card-hover-flip", category: "button-card", displayType: "card" },
  { name: "Card Hover Glow", className: "rc-card-hover-glow", category: "button-card", displayType: "card" },
  { name: "Card Hover Lift", className: "rc-card-hover-lift", category: "button-card", displayType: "card" },
  { name: "Card Hover Press", className: "rc-card-hover-press", category: "button-card", displayType: "card" },
  { name: "Card Hover Push", className: "rc-card-hover-push", category: "button-card", displayType: "card" },
  { name: "Card Hover Reveal", className: "rc-card-hover-reveal", category: "button-card", displayType: "card" },
  { name: "Card Hover Rotate", className: "rc-card-hover-rotate", category: "button-card", displayType: "card" },
  { name: "Card Hover Skew", className: "rc-card-hover-skew", category: "button-card", displayType: "card" },
  { name: "Card Hover Slide", className: "rc-card-hover-slide", category: "button-card", displayType: "card" },
  { name: "Card Hover Swing", className: "rc-card-hover-swing", category: "button-card", displayType: "card" },
  { name: "Card Hover Tada", className: "rc-card-hover-tada", category: "button-card", displayType: "card" },
  { name: "Card Hover Wobble", className: "rc-card-hover-wobble", category: "button-card", displayType: "card" },
  { name: "Card Hover Zoom", className: "rc-card-hover-zoom", category: "button-card", displayType: "card" },
  { name: "Card Neon", className: "rc-card-neon", category: "button-card", displayType: "card" },
  { name: "Card Shuffle", className: "rc-card-shuffle", category: "button-card", displayType: "card" },
  { name: "Card Spotlight", className: "rc-card-spotlight", category: "button-card", displayType: "card" },
  { name: "Clip Path Hexagon", className: "rc-clip-path-hexagon", category: "button-card", displayType: "box" },
  { name: "Clip Path Star", className: "rc-clip-path-star", category: "button-card", displayType: "box" },
  { name: "Cube Face", className: "rc-cube-face", category: "3d-transforms", displayType: "box" },
  { name: "Cube Rotate", className: "rc-cube-rotate", category: "3d-transforms", displayType: "box" },
  { name: "Cursor Arrow Bounce", className: "rc-cursor-arrow-bounce", category: "advanced", displayType: "box" },
  { name: "Cursor Blob", className: "rc-cursor-blob", category: "advanced", displayType: "box" },
  { name: "Cursor Crosshair", className: "rc-cursor-crosshair", category: "advanced", displayType: "box" },
  { name: "Cursor Firefly", className: "rc-cursor-firefly", category: "advanced", displayType: "box" },
  { name: "Cursor Glow Dot", className: "rc-cursor-glow-dot", category: "advanced", displayType: "box" },
  { name: "Cursor Gradient Trail", className: "rc-cursor-gradient-trail", category: "advanced", displayType: "box" },
  { name: "Cursor Magnetic", className: "rc-cursor-magnetic", category: "advanced", displayType: "box" },
  { name: "Cursor Pulse Ring", className: "rc-cursor-pulse-ring", category: "advanced", displayType: "box" },
  { name: "Cursor Ring", className: "rc-cursor-ring", category: "advanced", displayType: "box" },
  { name: "Cursor Ripple", className: "rc-cursor-ripple", category: "advanced", displayType: "box" },
  { name: "Cursor Spotlight", className: "rc-cursor-spotlight", category: "advanced", displayType: "box" },
  { name: "Cursor Trail", className: "rc-cursor-trail", category: "advanced", displayType: "box" },
  { name: "Deep Sea", className: "rc-deep-sea", category: "backgrounds", displayType: "box" },
  { name: "Depth Shadow", className: "rc-depth-shadow", category: "3d-transforms", displayType: "box" },
  { name: "Door Open", className: "rc-door-open", category: "3d-transforms", displayType: "box" },
  { name: "Drawer Slide", className: "rc-drawer-slide", category: "3d-transforms", displayType: "box" },
  { name: "Fade In Bl", className: "rc-fade-in-bl", category: "core-animations", displayType: "box" },
  { name: "Fade In Br", className: "rc-fade-in-br", category: "core-animations", displayType: "box" },
  { name: "Fade In Right", className: "rc-fade-in-right", category: "core-animations", displayType: "box" },
  { name: "Fade Out Down", className: "rc-fade-out-down", category: "core-animations", displayType: "box" },
  { name: "Fade Out Left", className: "rc-fade-out-left", category: "core-animations", displayType: "box" },
  { name: "Fade Out Right", className: "rc-fade-out-right", category: "core-animations", displayType: "box" },
  { name: "Fade Out Up", className: "rc-fade-out-up", category: "core-animations", displayType: "box" },
  { name: "Filter Blur Focus", className: "rc-filter-blur-focus", category: "advanced", displayType: "image" },
  { name: "Filter Cinematic", className: "rc-filter-cinematic", category: "advanced", displayType: "image" },
  { name: "Filter Contrast", className: "rc-filter-contrast", category: "advanced", displayType: "image" },
  { name: "Filter Dramatic", className: "rc-filter-dramatic", category: "advanced", displayType: "image" },
  { name: "Filter Dreamy", className: "rc-filter-dreamy", category: "advanced", displayType: "image" },
  { name: "Filter Duotone", className: "rc-filter-duotone", category: "advanced", displayType: "image" },
  { name: "Filter Emboss", className: "rc-filter-emboss", category: "advanced", displayType: "image" },
  { name: "Filter Glitch", className: "rc-filter-glitch", category: "advanced", displayType: "image" },
  { name: "Filter Grayscale Hover", className: "rc-filter-grayscale-hover", category: "advanced", displayType: "image" },
  { name: "Filter Halftone", className: "rc-filter-halftone", category: "advanced", displayType: "image" },
  { name: "Filter Hue Rotate", className: "rc-filter-hue-rotate", category: "advanced", displayType: "image" },
  { name: "Filter Invert", className: "rc-filter-invert", category: "advanced", displayType: "image" },
  { name: "Filter Saturate", className: "rc-filter-saturate", category: "advanced", displayType: "image" },
  { name: "Filter Sepia", className: "rc-filter-sepia", category: "advanced", displayType: "image" },
  { name: "Filter Vintage", className: "rc-filter-vintage", category: "advanced", displayType: "image" },
  { name: "Flip X", className: "rc-flip-x", category: "core-animations", displayType: "box" },
  { name: "Flip Y", className: "rc-flip-y", category: "core-animations", displayType: "box" },
  { name: "Float", className: "rc-float", category: "core-animations", displayType: "box" },
  { name: "Fold", className: "rc-fold", category: "3d-transforms", displayType: "box" },
  { name: "Form Checkbox Custom", className: "rc-form-checkbox-custom", category: "forms", displayType: "box" },
  { name: "Form Error Shake", className: "rc-form-error-shake", category: "forms", displayType: "box" },
  { name: "Form Focus Glow", className: "rc-form-focus-glow", category: "forms", displayType: "box" },
  { name: "Form Label Float", className: "rc-form-label-float", category: "forms", displayType: "box" },
  { name: "Form Placeholder Shimmer", className: "rc-form-placeholder-shimmer", category: "forms", displayType: "box" },
  { name: "Form Radio Custom", className: "rc-form-radio-custom", category: "forms", displayType: "box" },
  { name: "Form Search Expand", className: "rc-form-search-expand", category: "forms", displayType: "box" },
  { name: "Form Success Check", className: "rc-form-success-check", category: "forms", displayType: "box" },
  { name: "Form Toggle Switch", className: "rc-form-toggle-switch", category: "forms", displayType: "box" },
  { name: "Form Underline Draw", className: "rc-form-underline-draw", category: "forms", displayType: "box" },
  { name: "Fortune Teller", className: "rc-fortune-teller", category: "backgrounds", displayType: "box" },
  { name: "Frozen Ice", className: "rc-frozen-ice", category: "backgrounds", displayType: "box" },
  { name: "Glass Acrylic", className: "rc-glass-acrylic", category: "button-card", displayType: "card" },
  { name: "Glass Border Glow", className: "rc-glass-border-glow", category: "button-card", displayType: "card" },
  { name: "Glass Claymorphism", className: "rc-glass-claymorphism", category: "button-card", displayType: "card" },
  { name: "Glass Depth Layer", className: "rc-glass-depth-layer", category: "button-card", displayType: "card" },
  { name: "Glass Frosted", className: "rc-glass-frosted", category: "button-card", displayType: "card" },
  { name: "Glass Frosted Dark", className: "rc-glass-frosted-dark", category: "button-card", displayType: "card" },
  { name: "Glass Liquid", className: "rc-glass-liquid", category: "button-card", displayType: "card" },
  { name: "Glass Neumorphism", className: "rc-glass-neumorphism", category: "button-card", displayType: "card" },
  { name: "Glass Neumorphism Inset", className: "rc-glass-neumorphism-inset", category: "button-card", displayType: "card" },
  { name: "Glass Noise Overlay", className: "rc-glass-noise-overlay", category: "button-card", displayType: "card" },
  { name: "Glass Prism", className: "rc-glass-prism", category: "button-card", displayType: "card" },
  { name: "Glass Reflection", className: "rc-glass-reflection", category: "button-card", displayType: "card" },
  { name: "Glass Transparent Blur", className: "rc-glass-transparent-blur", category: "button-card", displayType: "card" },
  { name: "Glass Vibrant", className: "rc-glass-vibrant", category: "button-card", displayType: "card" },
  { name: "Gold Leaf", className: "rc-gold-leaf", category: "backgrounds", displayType: "box" },
  { name: "Head Shake", className: "rc-head-shake", category: "core-animations", displayType: "box" },
  { name: "Heat Haze", className: "rc-heat-haze", category: "backgrounds", displayType: "box" },
  { name: "Hover Border Draw", className: "rc-hover-border-draw", category: "hover", displayType: "box" },
  { name: "Hover Color Shift", className: "rc-hover-color-shift", category: "hover", displayType: "box" },
  { name: "Hover Depth", className: "rc-hover-depth", category: "hover", displayType: "box" },
  { name: "Hover Drop Shadow", className: "rc-hover-drop-shadow", category: "hover", displayType: "box" },
  { name: "Hover Fade Overlay", className: "rc-hover-fade-overlay", category: "hover", displayType: "box" },
  { name: "Hover Glow Border", className: "rc-hover-glow-border", category: "hover", displayType: "box" },
  { name: "Hover Grayscale To Color", className: "rc-hover-grayscale-to-color", category: "hover", displayType: "box" },
  { name: "Hover Hue Rotate", className: "rc-hover-hue-rotate", category: "hover", displayType: "box" },
  { name: "Hover Neon Flicker", className: "rc-hover-neon-flicker", category: "hover", displayType: "box" },
  { name: "Hover Opacity", className: "rc-hover-opacity", category: "hover", displayType: "box" },
  { name: "Hover Overlay Reveal", className: "rc-hover-overlay-reveal", category: "hover", displayType: "box" },
  { name: "Hover Press", className: "rc-hover-press", category: "hover", displayType: "box" },
  { name: "Hover Push Up", className: "rc-hover-push-up", category: "hover", displayType: "box" },
  { name: "Hover Scale", className: "rc-hover-scale", category: "hover", displayType: "box" },
  { name: "Hover Shadow Grow", className: "rc-hover-shadow-grow", category: "hover", displayType: "box" },
  { name: "Hover Slide Overlay", className: "rc-hover-slide-overlay", category: "hover", displayType: "box" },
  { name: "Hover Tilt Rotate", className: "rc-hover-tilt-rotate", category: "hover", displayType: "box" },
  { name: "Hover Underline Slide", className: "rc-hover-underline-slide", category: "hover", displayType: "box" },
  { name: "Hover Zoom Blur", className: "rc-hover-zoom-blur", category: "hover", displayType: "box" },
  { name: "Jack In Box", className: "rc-jack-in-box", category: "core-animations", displayType: "box" },
  { name: "Jiggle", className: "rc-jiggle", category: "core-animations", displayType: "box" },
  { name: "Kaleidoscope", className: "rc-kaleidoscope", category: "backgrounds", displayType: "box" },
  { name: "Linear Aurora Glow", className: "rc-linear-aurora-glow", category: "advanced", displayType: "box" },
  { name: "Linear Card Lift", className: "rc-linear-card-lift", category: "advanced", displayType: "card" },
  { name: "Linear Dark Surface", className: "rc-linear-dark-surface", category: "advanced", displayType: "box" },
  { name: "Linear Depth Shadow", className: "rc-linear-depth-shadow", category: "advanced", displayType: "box" },
  { name: "Linear Glow Border", className: "rc-linear-glow-border", category: "advanced", displayType: "box" },
  { name: "Linear Gradient Mesh Bg", className: "rc-linear-gradient-mesh-bg", category: "advanced", displayType: "box" },
  { name: "Linear Gradient Sweep", className: "rc-linear-gradient-sweep", category: "advanced", displayType: "box" },
  { name: "Linear Icon Bounce", className: "rc-linear-icon-bounce", category: "core-animations", displayType: "box" },
  { name: "Linear Magnetic Pull", className: "rc-linear-magnetic-pull", category: "advanced", displayType: "box" },
  { name: "Linear Noise Overlay", className: "rc-linear-noise-overlay", category: "advanced", displayType: "box" },
  { name: "Linear Shimmer Hover", className: "rc-linear-shimmer-hover", category: "advanced", displayType: "box" },
  { name: "Linear Spotlight", className: "rc-linear-spotlight", category: "advanced", displayType: "box" },
  { name: "Linear Text Glow", className: "rc-linear-text-glow", category: "advanced", displayType: "box" },
  { name: "Liquid Drop", className: "rc-liquid-drop", category: "backgrounds", displayType: "box" },
  { name: "Liquid Metal", className: "rc-liquid-metal", category: "backgrounds", displayType: "box" },
  { name: "Loader Bouncing Grid", className: "rc-loader-bouncing-grid", category: "loaders", displayType: "loader" },
  { name: "Loader Chasing Dots", className: "rc-loader-chasing-dots", category: "loaders", displayType: "loader" },
  { name: "Loader Circle Notch", className: "rc-loader-circle-notch", category: "loaders", displayType: "loader" },
  { name: "Loader Dual Ring", className: "rc-loader-dual-ring", category: "loaders", displayType: "loader" },
  { name: "Loader Fading Dots", className: "rc-loader-fading-dots", category: "loaders", displayType: "loader" },
  { name: "Loader Folding Cube", className: "rc-loader-folding-cube", category: "loaders", displayType: "loader" },
  { name: "Loader Indeterminate", className: "rc-loader-indeterminate", category: "loaders", displayType: "loader" },
  { name: "Loader Line Scale", className: "rc-loader-line-scale", category: "loaders", displayType: "loader" },
  { name: "Loader Pacman", className: "rc-loader-pacman", category: "loaders", displayType: "loader" },
  { name: "Loader Progress Bar", className: "rc-loader-progress-bar", category: "loaders", displayType: "loader" },
  { name: "Loader Pulse Ring", className: "rc-loader-pulse-ring", category: "loaders", displayType: "loader" },
  { name: "Loader Skeleton", className: "rc-loader-skeleton", category: "loaders", displayType: "loader" },
  { name: "Loader Three Bounce", className: "rc-loader-three-bounce", category: "loaders", displayType: "loader" },
  { name: "Loader Whale", className: "rc-loader-whale", category: "loaders", displayType: "loader" },
  { name: "Material Container Transform", className: "rc-material-container-transform", category: "core-animations", displayType: "box" },
  { name: "Material Elevation 1", className: "rc-material-elevation-1", category: "core-animations", displayType: "box" },
  { name: "Material Elevation 3", className: "rc-material-elevation-3", category: "core-animations", displayType: "box" },
  { name: "Material Elevation 5", className: "rc-material-elevation-5", category: "core-animations", displayType: "box" },
  { name: "Material Emphasized", className: "rc-material-emphasized", category: "core-animations", displayType: "box" },
  { name: "Material Emphasized Decel", className: "rc-material-emphasized-decel", category: "core-animations", displayType: "box" },
  { name: "Material Fab Scale", className: "rc-material-fab-scale", category: "core-animations", displayType: "box" },
  { name: "Material Spring Down", className: "rc-material-spring-down", category: "core-animations", displayType: "box" },
  { name: "Material Spring Up", className: "rc-material-spring-up", category: "core-animations", displayType: "box" },
  { name: "Material State Layer", className: "rc-material-state-layer", category: "core-animations", displayType: "box" },
  { name: "Material State Layer Surface", className: "rc-material-state-layer-surface", category: "core-animations", displayType: "box" },
  { name: "Material Surface Tint", className: "rc-material-surface-tint", category: "core-animations", displayType: "box" },
  { name: "Micro Accordion Expand", className: "rc-micro-accordion-expand", category: "navigation", displayType: "box" },
  { name: "Micro Badge Bounce", className: "rc-micro-badge-bounce", category: "navigation", displayType: "box" },
  { name: "Micro Checkbox Check", className: "rc-micro-checkbox-check", category: "navigation", displayType: "box" },
  { name: "Micro Dropdown Reveal", className: "rc-micro-dropdown-reveal", category: "navigation", displayType: "box" },
  { name: "Micro Fab Expand", className: "rc-micro-fab-expand", category: "navigation", displayType: "box" },
  { name: "Micro Modal Scale", className: "rc-micro-modal-scale", category: "navigation", displayType: "box" },
  { name: "Micro Progress Fill", className: "rc-micro-progress-fill", category: "navigation", displayType: "box" },
  { name: "Micro Radio Select", className: "rc-micro-radio-select", category: "navigation", displayType: "box" },
  { name: "Micro Tab Indicator", className: "rc-micro-tab-indicator", category: "navigation", displayType: "box" },
  { name: "Micro Toast Slide", className: "rc-micro-toast-slide", category: "navigation", displayType: "box" },
  { name: "Micro Toggle Switch", className: "rc-micro-toggle-switch", category: "navigation", displayType: "box" },
  { name: "Micro Tooltip Appear", className: "rc-micro-tooltip-appear", category: "navigation", displayType: "box" },
  { name: "Misc Bubbles", className: "rc-misc-bubbles", category: "backgrounds", displayType: "bg" },
  { name: "Misc Confetti", className: "rc-misc-confetti", category: "backgrounds", displayType: "bg" },
  { name: "Misc Fireflies", className: "rc-misc-fireflies", category: "backgrounds", displayType: "bg" },
  { name: "Misc Fireworks", className: "rc-misc-fireworks", category: "backgrounds", displayType: "bg" },
  { name: "Misc Hologram", className: "rc-misc-hologram", category: "backgrounds", displayType: "bg" },
  { name: "Misc Pulse Ring Expand", className: "rc-misc-pulse-ring-expand", category: "backgrounds", displayType: "bg" },
  { name: "Misc Rain", className: "rc-misc-rain", category: "backgrounds", displayType: "bg" },
  { name: "Misc Ripple Click", className: "rc-misc-ripple-click", category: "advanced", displayType: "bg" },
  { name: "Misc Scan Line", className: "rc-misc-scan-line", category: "backgrounds", displayType: "bg" },
  { name: "Misc Shimmer Overlay", className: "rc-misc-shimmer-overlay", category: "backgrounds", displayType: "bg" },
  { name: "Misc Snow", className: "rc-misc-snow", category: "backgrounds", displayType: "bg" },
  { name: "Misc Sparkles", className: "rc-misc-sparkles", category: "backgrounds", displayType: "bg" },
  { name: "Misc Typewriter", className: "rc-misc-typewriter", category: "backgrounds", displayType: "bg" },
  { name: "Misc Vhs Effect", className: "rc-misc-vhs-effect", category: "backgrounds", displayType: "bg" },
  { name: "Misc Wave", className: "rc-misc-wave", category: "backgrounds", displayType: "bg" },
  { name: "Molten Lava", className: "rc-molten-lava", category: "backgrounds", displayType: "box" },
  { name: "Morph Blob", className: "rc-morph-blob", category: "backgrounds", displayType: "box" },
  { name: "Natural Drop", className: "rc-natural-drop", category: "core-animations", displayType: "box" },
  { name: "Nav Accordion", className: "rc-nav-accordion", category: "navigation", displayType: "box" },
  { name: "Nav Breadcrumb", className: "rc-nav-breadcrumb", category: "navigation", displayType: "box" },
  { name: "Nav Dropdown", className: "rc-nav-dropdown", category: "navigation", displayType: "box" },
  { name: "Nav Menu Fade", className: "rc-nav-menu-fade", category: "navigation", displayType: "box" },
  { name: "Nav Menu Scale", className: "rc-nav-menu-scale", category: "navigation", displayType: "box" },
  { name: "Nav Menu Slide", className: "rc-nav-menu-slide", category: "navigation", displayType: "box" },
  { name: "Nav Pagination", className: "rc-nav-pagination", category: "navigation", displayType: "box" },
  { name: "Nav Progress Indicator", className: "rc-nav-progress-indicator", category: "navigation", displayType: "box" },
  { name: "Nav Stepper", className: "rc-nav-stepper", category: "navigation", displayType: "box" },
  { name: "Nav Tabs Underline", className: "rc-nav-tabs-underline", category: "navigation", displayType: "box" },
  { name: "Neon Sign", className: "rc-neon-sign", category: "backgrounds", displayType: "box" },
  { name: "Oil Slick", className: "rc-oil-slick", category: "backgrounds", displayType: "box" },
  { name: "Origami Fold", className: "rc-origami-fold", category: "backgrounds", displayType: "box" },
  { name: "Page Circle Reveal", className: "rc-page-circle-reveal", category: "advanced", displayType: "box" },
  { name: "Page Cube", className: "rc-page-cube", category: "advanced", displayType: "box" },
  { name: "Page Curtain", className: "rc-page-curtain", category: "advanced", displayType: "box" },
  { name: "Page Dissolve", className: "rc-page-dissolve", category: "advanced", displayType: "box" },
  { name: "Page Fade", className: "rc-page-fade", category: "advanced", displayType: "box" },
  { name: "Page Flip", className: "rc-page-flip", category: "advanced", displayType: "box" },
  { name: "Page Liquid", className: "rc-page-liquid", category: "advanced", displayType: "box" },
  { name: "Page Mask Reveal", className: "rc-page-mask-reveal", category: "advanced", displayType: "box" },
  { name: "Page Shutter", className: "rc-page-shutter", category: "advanced", displayType: "box" },
  { name: "Page Slide Left", className: "rc-page-slide-left", category: "advanced", displayType: "box" },
  { name: "Page Slide Up", className: "rc-page-slide-up", category: "advanced", displayType: "box" },
  { name: "Page Zoom", className: "rc-page-zoom", category: "advanced", displayType: "box" },
  { name: "Paper Flip", className: "rc-paper-flip", category: "backgrounds", displayType: "box" },
  { name: "Particles Bubbles", className: "rc-particles-bubbles", category: "backgrounds", displayType: "bg" },
  { name: "Particles Confetti Burst", className: "rc-particles-confetti-burst", category: "backgrounds", displayType: "bg" },
  { name: "Particles Dust", className: "rc-particles-dust", category: "backgrounds", displayType: "bg" },
  { name: "Particles Fire", className: "rc-particles-fire", category: "backgrounds", displayType: "bg" },
  { name: "Particles Fireflies", className: "rc-particles-fireflies", category: "backgrounds", displayType: "bg" },
  { name: "Particles Floating Dots", className: "rc-particles-floating-dots", category: "backgrounds", displayType: "bg" },
  { name: "Particles Orbiting", className: "rc-particles-orbiting", category: "backgrounds", displayType: "bg" },
  { name: "Particles Rain", className: "rc-particles-rain", category: "backgrounds", displayType: "bg" },
  { name: "Particles Smoke", className: "rc-particles-smoke", category: "backgrounds", displayType: "bg" },
  { name: "Particles Snow Fall", className: "rc-particles-snow-fall", category: "backgrounds", displayType: "bg" },
  { name: "Particles Sparks", className: "rc-particles-sparks", category: "backgrounds", displayType: "bg" },
  { name: "Particles Stars Twinkle", className: "rc-particles-stars-twinkle", category: "backgrounds", displayType: "bg" },
  { name: "Pendulum", className: "rc-pendulum", category: "core-animations", displayType: "box" },
  { name: "Pendulum Swing Spring", className: "rc-pendulum-swing-spring", category: "core-animations", displayType: "box" },
  { name: "Perspective Tilt", className: "rc-perspective-tilt", category: "3d-transforms", displayType: "box" },
  { name: "Pixel Art", className: "rc-pixel-art", category: "backgrounds", displayType: "box" },
  { name: "Pop In", className: "rc-pop-in", category: "core-animations", displayType: "box" },
  { name: "Pop Out", className: "rc-pop-out", category: "core-animations", displayType: "box" },
  { name: "Prism Rainbow", className: "rc-prism-rainbow", category: "backgrounds", displayType: "box" },
  { name: "Pulse Soft", className: "rc-pulse-soft", category: "core-animations", displayType: "box" },
  { name: "Rotate 3d", className: "rc-rotate-3d", category: "core-animations", displayType: "box" },
  { name: "Rotate Spin", className: "rc-rotate-spin", category: "core-animations", displayType: "box" },
  { name: "Rotate X", className: "rc-rotate-x", category: "core-animations", displayType: "box" },
  { name: "Rotate Y", className: "rc-rotate-y", category: "core-animations", displayType: "box" },
  { name: "Roulette Spin", className: "rc-roulette-spin", category: "backgrounds", displayType: "box" },
  { name: "Rubber Snap Back", className: "rc-rubber-snap-back", category: "core-animations", displayType: "box" },
  { name: "Scale 3d", className: "rc-scale-3d", category: "3d-transforms", displayType: "box" },
  { name: "Scale Compress", className: "rc-scale-compress", category: "core-animations", displayType: "box" },
  { name: "Scale Expand", className: "rc-scale-expand", category: "core-animations", displayType: "box" },
  { name: "Scale Grow", className: "rc-scale-grow", category: "core-animations", displayType: "box" },
  { name: "Scale Shrink", className: "rc-scale-shrink", category: "core-animations", displayType: "box" },
  { name: "Scroll Driven Blur", className: "rc-scroll-driven-blur", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Driven Color", className: "rc-scroll-driven-color", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Driven Fade", className: "rc-scroll-driven-fade", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Driven Progress Ring", className: "rc-scroll-driven-progress-ring", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Driven Rotate", className: "rc-scroll-driven-rotate", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Driven Scale", className: "rc-scroll-driven-scale", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Driven Sticky", className: "rc-scroll-driven-sticky", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Driven Translate", className: "rc-scroll-driven-translate", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Fade Out", className: "rc-scroll-fade-out", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Horizontal", className: "rc-scroll-horizontal", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Indicator", className: "rc-scroll-indicator", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Parallax Slow", className: "rc-scroll-parallax-slow", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Progress Bar", className: "rc-scroll-progress-bar", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Reveal Left", className: "rc-scroll-reveal-left", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Reveal Right", className: "rc-scroll-reveal-right", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Reveal Rotate", className: "rc-scroll-reveal-rotate", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Reveal Scale", className: "rc-scroll-reveal-scale", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Reveal Up", className: "rc-scroll-reveal-up", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Sticky Header", className: "rc-scroll-sticky-header", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Timeline Spin", className: "rc-scroll-timeline-spin", category: "scroll-micro", displayType: "box" },
  { name: "Skew 3d", className: "rc-skew-3d", category: "3d-transforms", displayType: "box" },
  { name: "Slide Diagonal", className: "rc-slide-diagonal", category: "core-animations", displayType: "box" },
  { name: "Slide In Bottom", className: "rc-slide-in-bottom", category: "core-animations", displayType: "box" },
  { name: "Slide In Top", className: "rc-slide-in-top", category: "core-animations", displayType: "box" },
  { name: "Slide Out Bottom", className: "rc-slide-out-bottom", category: "core-animations", displayType: "box" },
  { name: "Slide Out Top", className: "rc-slide-out-top", category: "core-animations", displayType: "box" },
  { name: "Slide Rotate In", className: "rc-slide-rotate-in", category: "core-animations", displayType: "box" },
  { name: "Slot Machine", className: "rc-slot-machine", category: "backgrounds", displayType: "box" },
  { name: "Snap In", className: "rc-snap-in", category: "core-animations", displayType: "box" },
  { name: "Soap Bubble", className: "rc-soap-bubble", category: "backgrounds", displayType: "box" },
  { name: "Spiral Galaxy", className: "rc-spiral-galaxy", category: "backgrounds", displayType: "box" },
  { name: "Spring In", className: "rc-spring-in", category: "core-animations", displayType: "box" },
  { name: "Stained Glass", className: "rc-stained-glass", category: "backgrounds", displayType: "box" },
  { name: "Stretch", className: "rc-stretch", category: "core-animations", displayType: "box" },
  { name: "Sway", className: "rc-sway", category: "core-animations", displayType: "box" },
  { name: "Swing In", className: "rc-swing-in", category: "core-animations", displayType: "box" },
  { name: "Text 3d Cinema", className: "rc-text-3d-cinema", category: "text", displayType: "text" },
  { name: "Text 3d Shadow", className: "rc-text-3d-shadow", category: "text", displayType: "text" },
  { name: "Text Blur Reveal", className: "rc-text-blur-reveal", category: "text", displayType: "text" },
  { name: "Text Bounce Letters", className: "rc-text-bounce-letters", category: "text", displayType: "text" },
  { name: "Text Chrome", className: "rc-text-chrome", category: "text", displayType: "text" },
  { name: "Text Emboss", className: "rc-text-emboss", category: "text", displayType: "text" },
  { name: "Text Fire", className: "rc-text-fire", category: "text", displayType: "text" },
  { name: "Text Fire Flame", className: "rc-text-fire-flame", category: "text", displayType: "text" },
  { name: "Text Flip", className: "rc-text-flip", category: "text", displayType: "text" },
  { name: "Text Gradient Shift", className: "rc-text-gradient-shift", category: "text", displayType: "text" },
  { name: "Text Highlight Marker", className: "rc-text-highlight-marker", category: "text", displayType: "text" },
  { name: "Text Holographic", className: "rc-text-holographic", category: "text", displayType: "text" },
  { name: "Text Mirror", className: "rc-text-mirror", category: "text", displayType: "text" },
  { name: "Text Neon Glow", className: "rc-text-neon-glow", category: "text", displayType: "text" },
  { name: "Text Neon Sign", className: "rc-text-neon-sign", category: "text", displayType: "text" },
  { name: "Text Outline Offset", className: "rc-text-outline-offset", category: "text", displayType: "text" },
  { name: "Text Reflection", className: "rc-text-reflection", category: "text", displayType: "text" },
  { name: "Text Shadow Long", className: "rc-text-shadow-long", category: "text", displayType: "text" },
  { name: "Text Shadow Soft", className: "rc-text-shadow-soft", category: "text", displayType: "text" },
  { name: "Text Shimmer", className: "rc-text-shimmer", category: "text", displayType: "text" },
  { name: "Text Skew", className: "rc-text-skew", category: "text", displayType: "text" },
  { name: "Text Stretch", className: "rc-text-stretch", category: "text", displayType: "text" },
  { name: "Text Typing Cursor", className: "rc-text-typing-cursor", category: "text", displayType: "text" },
  { name: "Text Underline Draw", className: "rc-text-underline-draw", category: "text", displayType: "text" },
  { name: "Text Water", className: "rc-text-water", category: "text", displayType: "text" },
  { name: "Topographic", className: "rc-topographic", category: "advanced", displayType: "box" },
  { name: "Transform Origin Spin", className: "rc-transform-origin-spin", category: "3d-transforms", displayType: "box" },
  { name: "Velvet Fabric", className: "rc-velvet-fabric", category: "backgrounds", displayType: "box" },
  { name: "Vhs Glitch", className: "rc-vhs-glitch", category: "advanced", displayType: "box" },
  { name: "Vibrate", className: "rc-vibrate", category: "core-animations", displayType: "box" },
  { name: "Vintage Tv", className: "rc-vintage-tv", category: "backgrounds", displayType: "box" },
  { name: "Visual Aurora Border", className: "rc-visual-aurora-border", category: "advanced", displayType: "image" },
  { name: "Visual Backdrop Blur Heavy", className: "rc-visual-backdrop-blur-heavy", category: "advanced", displayType: "image" },
  { name: "Visual Blend Mode Overlay", className: "rc-visual-blend-mode-overlay", category: "advanced", displayType: "image" },
  { name: "Visual Border Beam", className: "rc-visual-border-beam", category: "advanced", displayType: "image" },
  { name: "Visual Chrome", className: "rc-visual-chrome", category: "advanced", displayType: "image" },
  { name: "Visual Color Shift", className: "rc-visual-color-shift", category: "advanced", displayType: "image" },
  { name: "Visual Foil", className: "rc-visual-foil", category: "advanced", displayType: "image" },
  { name: "Visual Frost Blur", className: "rc-visual-frost-blur", category: "advanced", displayType: "image" },
  { name: "Visual Glass Reflection", className: "rc-visual-glass-reflection", category: "advanced", displayType: "card" },
  { name: "Visual Glitch Distort", className: "rc-visual-glitch-distort", category: "advanced", displayType: "image" },
  { name: "Visual Gradient Mesh", className: "rc-visual-gradient-mesh", category: "advanced", displayType: "image" },
  { name: "Visual Gradient Text Animated", className: "rc-visual-gradient-text-animated", category: "advanced", displayType: "image" },
  { name: "Visual Holographic", className: "rc-visual-holographic", category: "advanced", displayType: "image" },
  { name: "Visual Hue Rotate Loop", className: "rc-visual-hue-rotate-loop", category: "advanced", displayType: "image" },
  { name: "Visual Image Distortion", className: "rc-visual-image-distortion", category: "advanced", displayType: "image" },
  { name: "Visual Inner Glow", className: "rc-visual-inner-glow", category: "advanced", displayType: "image" },
  { name: "Visual Iridescent", className: "rc-visual-iridescent", category: "advanced", displayType: "image" },
  { name: "Visual Liquid Fill", className: "rc-visual-liquid-fill", category: "advanced", displayType: "image" },
  { name: "Visual Mask Fade", className: "rc-visual-mask-fade", category: "advanced", displayType: "image" },
  { name: "Visual Metallic", className: "rc-visual-metallic", category: "advanced", displayType: "image" },
  { name: "Visual Neon Pulse", className: "rc-visual-neon-pulse", category: "advanced", displayType: "image" },
  { name: "Visual Noise Overlay", className: "rc-visual-noise-overlay", category: "advanced", displayType: "image" },
  { name: "Visual Pixelate", className: "rc-visual-pixelate", category: "advanced", displayType: "image" },
  { name: "Visual Prism", className: "rc-visual-prism", category: "advanced", displayType: "image" },
  { name: "Visual Saturation Pulse", className: "rc-visual-saturation-pulse", category: "advanced", displayType: "image" },
  { name: "Visual Shadow Pulse", className: "rc-visual-shadow-pulse", category: "advanced", displayType: "image" },
  { name: "Visual Shimmer Sweep", className: "rc-visual-shimmer-sweep", category: "advanced", displayType: "image" },
  { name: "Visual Spotlight Follow", className: "rc-visual-spotlight-follow", category: "advanced", displayType: "image" },
  { name: "Water Ripple", className: "rc-water-ripple", category: "backgrounds", displayType: "box" },
  { name: "Watercolor", className: "rc-watercolor", category: "advanced", displayType: "box" },
  { name: "Zoom In Down", className: "rc-zoom-in-down", category: "core-animations", displayType: "box" },
  { name: "Zoom In Left", className: "rc-zoom-in-left", category: "core-animations", displayType: "box" },
  { name: "Zoom In Right", className: "rc-zoom-in-right", category: "core-animations", displayType: "box" },
  { name: "Zoom In Up", className: "rc-zoom-in-up", category: "core-animations", displayType: "box" },
  { name: "Zoom Out Left", className: "rc-zoom-out-left", category: "core-animations", displayType: "box" },
  { name: "Zoom Out Up", className: "rc-zoom-out-up", category: "core-animations", displayType: "box" }
];

// Pre-computed stats
export const stats: Stats = {
  total: 848,
  categories: 11,
  unique: 181,
  keyframes: 284,
};

export const effectsIndex: FerrumEffectIndex[] = [
  { name: "Fade In", className: "rc-fade-in", category: "core-animations", displayType: "box" },
  { name: "Slide In Up", className: "rc-slide-in-up", category: "core-animations", displayType: "box" },
  { name: "Slide In Down", className: "rc-slide-in-down", category: "core-animations", displayType: "box" },
  { name: "Slide In Left", className: "rc-slide-in-left", category: "core-animations", displayType: "box" },
  { name: "Slide In Right", className: "rc-slide-in-right", category: "core-animations", displayType: "box" },
  { name: "Zoom In", className: "rc-zoom-in", category: "core-animations", displayType: "box" },
  { name: "Bounce In", className: "rc-bounce-in", category: "core-animations", displayType: "box" },
  { name: "Flip In X", className: "rc-flip-in-x", category: "core-animations", displayType: "box" },
  { name: "Flip In Y", className: "rc-flip-in-y", category: "core-animations", displayType: "box" },
  { name: "Fade In Up", className: "rc-fade-in-up", category: "core-animations", displayType: "box" },
  { name: "Fade In Down", className: "rc-fade-in-down", category: "core-animations", displayType: "box" },
  { name: "Fade In Left", className: "rc-fade-in-left", category: "core-animations", displayType: "box" },
  { name: "Roll In", className: "rc-roll-in", category: "core-animations", displayType: "box" },
  { name: "Light Speed In", className: "rc-light-speed-in", category: "core-animations", displayType: "box" },
  { name: "Rotate In", className: "rc-rotate-in", category: "core-animations", displayType: "box" },
  { name: "Rotate In Down Left", className: "rc-rotate-in-down-left", category: "core-animations", displayType: "box" },
  { name: "Rotate In Up Right", className: "rc-rotate-in-up-right", category: "core-animations", displayType: "box" },
  { name: "Fade In Scale", className: "rc-fade-in-scale", category: "core-animations", displayType: "box" },
  { name: "Drop In", className: "rc-drop-in", category: "core-animations", displayType: "box" },
  { name: "Expand In", className: "rc-expand-in", category: "core-animations", displayType: "box" },
  { name: "Fade Out", className: "rc-fade-out", category: "core-animations", displayType: "box" },
  { name: "Slide Out Up", className: "rc-slide-out-up", category: "core-animations", displayType: "box" },
  { name: "Slide Out Down", className: "rc-slide-out-down", category: "core-animations", displayType: "box" },
  { name: "Slide Out Left", className: "rc-slide-out-left", category: "core-animations", displayType: "box" },
  { name: "Slide Out Right", className: "rc-slide-out-right", category: "core-animations", displayType: "box" },
  { name: "Zoom Out", className: "rc-zoom-out", category: "core-animations", displayType: "box" },
  { name: "Flip Out X", className: "rc-flip-out-x", category: "core-animations", displayType: "box" },
  { name: "Flip Out Y", className: "rc-flip-out-y", category: "core-animations", displayType: "box" },
  { name: "Light Speed Out", className: "rc-light-speed-out", category: "core-animations", displayType: "box" },
  { name: "Roll Out", className: "rc-roll-out", category: "core-animations", displayType: "box" },
  { name: "Rotate Out", className: "rc-rotate-out", category: "core-animations", displayType: "box" },
  { name: "Fade Out Scale", className: "rc-fade-out-scale", category: "core-animations", displayType: "box" },
  { name: "Shrink Out", className: "rc-shrink-out", category: "core-animations", displayType: "box" },
  { name: "Fold Out", className: "rc-fold-out", category: "core-animations", displayType: "box" },
  { name: "Fly Out Up", className: "rc-fly-out-up", category: "core-animations", displayType: "box" },
  { name: "Bounce", className: "rc-bounce", category: "core-animations", displayType: "box" },
  { name: "Pulse", className: "rc-pulse", category: "core-animations", displayType: "box" },
  { name: "Shake", className: "rc-shake", category: "core-animations", displayType: "box" },
  { name: "Swing", className: "rc-swing", category: "core-animations", displayType: "box" },
  { name: "Tada", className: "rc-tada", category: "core-animations", displayType: "box" },
  { name: "Wobble", className: "rc-wobble", category: "core-animations", displayType: "box" },
  { name: "Heartbeat", className: "rc-heartbeat", category: "core-animations", displayType: "box" },
  { name: "Shake X", className: "rc-shake-x", category: "core-animations", displayType: "box" },
  { name: "Shake Y", className: "rc-shake-y", category: "core-animations", displayType: "box" },
  { name: "Jelly", className: "rc-jelly", category: "core-animations", displayType: "box" },
  { name: "Rubber Band", className: "rc-rubber-band", category: "core-animations", displayType: "box" },
  { name: "Pulse Glow", className: "rc-pulse-glow", category: "core-animations", displayType: "box" },
  { name: "Wiggle", className: "rc-wiggle", category: "core-animations", displayType: "box" },
  { name: "Jello", className: "rc-jello", category: "core-animations", displayType: "box" },
  { name: "Sonar", className: "rc-sonar", category: "core-animations", displayType: "box" },
  { name: "Flash", className: "rc-flash", category: "core-animations", displayType: "box" },
  { name: "Strobe", className: "rc-strobe", category: "core-animations", displayType: "box" },
  { name: "Glow", className: "rc-hover-glow", category: "hover", displayType: "box" },
  { name: "Scale Up", className: "rc-hover-scale-up", category: "hover", displayType: "box" },
  { name: "Scale Down", className: "rc-hover-scale-down", category: "hover", displayType: "box" },
  { name: "Rotate", className: "rc-hover-rotate", category: "hover", displayType: "box" },
  { name: "Skew", className: "rc-hover-skew", category: "hover", displayType: "box" },
  { name: "Border Glow", className: "rc-hover-border-glow", category: "hover", displayType: "box" },
  { name: "Shadow Lift", className: "rc-hover-shadow-lift", category: "hover", displayType: "box" },
  { name: "Float", className: "rc-hover-float", category: "hover", displayType: "box" },
  { name: "Tilt", className: "rc-hover-tilt", category: "hover", displayType: "box" },
  { name: "Ripple", className: "rc-hover-ripple", category: "hover", displayType: "box" },
  { name: "Underline Grow", className: "rc-hover-underline-grow", category: "hover", displayType: "box" },
  { name: "Overlay Slide", className: "rc-hover-overlay-slide", category: "hover", displayType: "box" },
  { name: "Background Slide", className: "rc-hover-bg-slide", category: "hover", displayType: "box" },
  { name: "Shrink Border", className: "rc-hover-shrink-border", category: "hover", displayType: "box" },
  { name: "Expand", className: "rc-hover-expand", category: "hover", displayType: "box" },
  { name: "Neon Pulse", className: "rc-hover-neon-pulse", category: "hover", displayType: "box" },
  { name: "Hover Fill", className: "rc-hover-fill", category: "hover", displayType: "box" },
  { name: "Hover Swipe", className: "rc-hover-swipe", category: "hover", displayType: "box" },
  { name: "Hover Shadow", className: "rc-hover-shadow", category: "hover", displayType: "box" },
  { name: "Hover Blur", className: "rc-hover-blur", category: "hover", displayType: "box" },
  { name: "Hover Skew Reverse", className: "rc-hover-skew-reverse", category: "hover", displayType: "box" },
  { name: "Hover Flip", className: "rc-hover-flip", category: "hover", displayType: "box" },
  { name: "Hover Slide Right", className: "rc-hover-slide-right", category: "hover", displayType: "box" },
  { name: "Hover Slide Up", className: "rc-hover-slide-up", category: "hover", displayType: "box" },
  { name: "Hover Morph", className: "rc-hover-morph", category: "hover", displayType: "box" },
  { name: "Hover Shake", className: "rc-hover-shake", category: "hover", displayType: "box" },
  { name: "Hover Glow Text", className: "rc-hover-glow-text", category: "hover", displayType: "box" },
  { name: "Hover 3D Lift", className: "rc-hover-3d-lift", category: "hover", displayType: "box" },
  { name: "Gradient", className: "rc-text-gradient", category: "text", displayType: "text" },
  { name: "Shadow Pop", className: "rc-text-shadow-pop", category: "text", displayType: "text" },
  { name: "Stroke", className: "rc-text-stroke", category: "text", displayType: "text" },
  { name: "Glow", className: "rc-text-glow", category: "text", displayType: "text" },
  { name: "Typewriter", className: "rc-text-typewriter", category: "text", displayType: "text" },
  { name: "Wave", className: "rc-text-wave", category: "text", displayType: "text" },
  { name: "Blur In", className: "rc-text-blur-in", category: "text", displayType: "text" },
  { name: "Highlight", className: "rc-text-highlight", category: "text", displayType: "text" },
  { name: "Underline Slide", className: "rc-text-underline-slide", category: "text", displayType: "text" },
  { name: "Blink", className: "rc-text-blink", category: "text", displayType: "text" },
  { name: "Text Scramble", className: "rc-text-scramble", category: "text", displayType: "text" },
  { name: "Text 3D", className: "rc-text-3d", category: "text", displayType: "text" },
  { name: "Text Neon Flicker", className: "rc-text-neon-flicker", category: "text", displayType: "text" },
  { name: "Text Rainbow", className: "rc-text-rainbow", category: "text", displayType: "text" },
  { name: "Text Slide Up", className: "rc-text-slide-up", category: "text", displayType: "text" },
  { name: "Text Glitch", className: "rc-text-glitch", category: "text", displayType: "text" },
  { name: "Text Reveal", className: "rc-text-reveal", category: "text", displayType: "text" },
  { name: "Text Bounce", className: "rc-text-bounce", category: "text", displayType: "text" },
  { name: "Gradient Shift", className: "rc-bg-gradient-shift", category: "backgrounds", displayType: "bg" },
  { name: "Mesh Gradient", className: "rc-bg-mesh", category: "backgrounds", displayType: "bg" },
  { name: "Animated Dots", className: "rc-bg-dots", category: "backgrounds", displayType: "bg" },
  { name: "Striped", className: "rc-bg-striped", category: "backgrounds", displayType: "bg" },
  { name: "Checkerboard", className: "rc-bg-checkerboard", category: "backgrounds", displayType: "bg" },
  { name: "Radial Pulse", className: "rc-bg-radial-pulse", category: "backgrounds", displayType: "bg" },
  { name: "Noise Texture", className: "rc-bg-noise-texture", category: "backgrounds", displayType: "bg" },
  { name: "Aurora", className: "rc-bg-aurora", category: "backgrounds", displayType: "bg" },
  { name: "Background Liquid", className: "rc-bg-liquid", category: "backgrounds", displayType: "bg" },
  { name: "Background Waves", className: "rc-bg-waves", category: "backgrounds", displayType: "bg" },
  { name: "Background Plasma", className: "rc-bg-plasma", category: "backgrounds", displayType: "bg" },
  { name: "Background Matrix Rain", className: "rc-bg-matrix", category: "backgrounds", displayType: "bg" },
  { name: "Background Starfield", className: "rc-bg-starfield", category: "backgrounds", displayType: "bg" },
  { name: "Background Smoke", className: "rc-bg-smoke", category: "backgrounds", displayType: "bg" },
  { name: "Background Circuit", className: "rc-bg-circuit", category: "backgrounds", displayType: "bg" },
  { name: "Background Lava Lamp", className: "rc-bg-lava", category: "backgrounds", displayType: "bg" },
  { name: "Spinner", className: "rc-loader-spinner", category: "loaders", displayType: "loader" },
  { name: "Dots", className: "rc-loader-dots", category: "loaders", displayType: "loader" },
  { name: "Bars", className: "rc-loader-bars", category: "loaders", displayType: "loader" },
  { name: "Pulse", className: "rc-loader-pulse", category: "loaders", displayType: "loader" },
  { name: "Orbit", className: "rc-loader-orbit", category: "loaders", displayType: "loader" },
  { name: "Wave", className: "rc-loader-wave", category: "loaders", displayType: "loader" },
  { name: "DNA", className: "rc-loader-dna", category: "loaders", displayType: "loader" },
  { name: "Circle Fade", className: "rc-loader-circle-fade", category: "loaders", displayType: "loader" },
  { name: "Square Spin", className: "rc-loader-square-spin", category: "loaders", displayType: "loader" },
  { name: "Ring", className: "rc-loader-ring", category: "loaders", displayType: "loader" },
  { name: "Loader Cube", className: "rc-loader-cube", category: "loaders", displayType: "loader" },
  { name: "Loader Hourglass", className: "rc-loader-hourglass", category: "loaders", displayType: "loader" },
  { name: "Loader Grid", className: "rc-loader-grid", category: "loaders", displayType: "loader" },
  { name: "Loader Ripple", className: "rc-loader-ripple", category: "loaders", displayType: "loader" },
  { name: "Loader Typing", className: "rc-loader-typing", category: "loaders", displayType: "loader" },
  { name: "Loader Pencil", className: "rc-loader-pencil", category: "loaders", displayType: "loader" },
  { name: "Loader Atom", className: "rc-loader-atom", category: "loaders", displayType: "loader" },
  { name: "Loader Bar Progress", className: "rc-loader-bar-progress", category: "loaders", displayType: "loader" },
  { name: "Loader Clock", className: "rc-loader-clock", category: "loaders", displayType: "loader" },
  { name: "Loader Bouncing Ball", className: "rc-loader-bounce", category: "loaders", displayType: "loader" },
  { name: "Loader Moon", className: "rc-loader-moon", category: "loaders", displayType: "loader" },
  { name: "Loader Heartbeat", className: "rc-loader-heartbeat", category: "loaders", displayType: "loader" },
  { name: "Flip", className: "roy-flip", category: "3d-transforms", displayType: "box" },
  { name: "Cube", className: "roy-cube", category: "3d-transforms", displayType: "box" },
  { name: "Prism", className: "roy-prism", category: "3d-transforms", displayType: "box" },
  { name: "Carousel", className: "roy-carousel", category: "3d-transforms", displayType: "box" },
  { name: "Card Tilt", className: "roy-card-tilt", category: "3d-transforms", displayType: "box" },
  { name: "Perspective", className: "roy-perspective", category: "3d-transforms", displayType: "box" },
  { name: "Depth Float", className: "roy-depth-float", category: "3d-transforms", displayType: "box" },
  { name: "Rotate3D", className: "roy-rotate3d", category: "3d-transforms", displayType: "box" },
  { name: "3D Book Open", className: "roy-book-open", category: "3d-transforms", displayType: "box" },
  { name: "3D Door Open", className: "roy-door-open", category: "3d-transforms", displayType: "box" },
  { name: "3D Coin Flip", className: "roy-coin-flip", category: "3d-transforms", displayType: "box" },
  { name: "3D Swing", className: "roy-swing", category: "3d-transforms", displayType: "box" },
  { name: "3D Helix", className: "roy-helix", category: "3d-transforms", displayType: "box" },
  { name: "3D Morphing Cube", className: "roy-morphing-cube", category: "3d-transforms", displayType: "box" },
  { name: "3D Orbit", className: "roy-orbit", category: "3d-transforms", displayType: "box" },
  { name: "3D Tumble", className: "roy-tumble", category: "3d-transforms", displayType: "box" },
  { name: "Morph Circle", className: "roy-morph-circle", category: "3d-transforms", displayType: "box" },
  { name: "Morph Diamond", className: "roy-morph-diamond", category: "3d-transforms", displayType: "box" },
  { name: "Rotate 90", className: "roy-rotate90", category: "3d-transforms", displayType: "box" },
  { name: "Rotate 180", className: "roy-rotate180", category: "3d-transforms", displayType: "box" },
  { name: "Rotate 360", className: "roy-rotate360", category: "3d-transforms", displayType: "box" },
  { name: "Skew X", className: "roy-skew-x", category: "3d-transforms", displayType: "box" },
  { name: "Skew Y", className: "roy-skew-y", category: "3d-transforms", displayType: "box" },
  { name: "Scale Rotate", className: "roy-scale-rotate", category: "3d-transforms", displayType: "box" },
  { name: "Transform Accordion", className: "roy-accordion", category: "3d-transforms", displayType: "box" },
  { name: "Transform Fan", className: "roy-fan", category: "3d-transforms", displayType: "box" },
  { name: "Transform Stretch", className: "roy-stretch", category: "3d-transforms", displayType: "box" },
  { name: "Transform Compress", className: "roy-compress", category: "3d-transforms", displayType: "box" },
  { name: "Transform Wobble", className: "roy-wobble", category: "3d-transforms", displayType: "box" },
  { name: "Transform Twist", className: "roy-twist", category: "3d-transforms", displayType: "box" },
  { name: "Transform Fold", className: "roy-fold", category: "3d-transforms", displayType: "box" },
  { name: "Transform Unfold", className: "roy-unfold", category: "3d-transforms", displayType: "box" },
  { name: "Liquid Fill", className: "roy-liquid-fill", category: "advanced", displayType: "box" },
  { name: "Smoke", className: "roy-smoke", category: "advanced", displayType: "box" },
  { name: "Electric", className: "roy-electric", category: "advanced", displayType: "box" },
  { name: "Holographic", className: "roy-holographic", category: "advanced", displayType: "box" },
  { name: "Breathing", className: "roy-breathing", category: "advanced", displayType: "box" },
  { name: "Paper Unfold", className: "roy-paper-unfold", category: "advanced", displayType: "box" },
  { name: "Ripple Spread", className: "roy-ripple-spread", category: "advanced", displayType: "box" },
  { name: "Confetti Burst", className: "roy-confetti-burst", category: "advanced", displayType: "box" },
  { name: "Magnetic Pull", className: "roy-magnetic-pull", category: "advanced", displayType: "box" },
  { name: "Glass Shatter", className: "roy-glass-shatter", category: "advanced", displayType: "box" },
  { name: "Neon Outline", className: "roy-neon-outline", category: "advanced", displayType: "box" },
  { name: "Gradient Border Spin", className: "roy-gradient-border-spin", category: "advanced", displayType: "box" },
  { name: "Unique Aurora Text", className: "roy-aurora-text", category: "advanced", displayType: "text" },
  { name: "Unique Fire", className: "roy-fire", category: "advanced", displayType: "box" },
  { name: "Unique Ice", className: "roy-ice", category: "advanced", displayType: "box" },
  { name: "Unique Sand", className: "roy-sand", category: "advanced", displayType: "box" },
  { name: "Unique Water Drop", className: "roy-water-drop", category: "advanced", displayType: "box" },
  { name: "Unique Glitch Morph", className: "roy-glitch-morph", category: "advanced", displayType: "box" },
  { name: "Unique Pixelate", className: "roy-pixelate", category: "advanced", displayType: "box" },
  { name: "Unique Cyber Grid", className: "roy-cyber-grid", category: "advanced", displayType: "bg" },
  { name: "Unique Morphing Blob", className: "roy-morphing-blob", category: "advanced", displayType: "box" },
  { name: "Unique Text Shadow Stack", className: "roy-text-shadow-stack", category: "advanced", displayType: "text" },
  { name: "Unique Prism Refraction", className: "roy-prism-refraction", category: "advanced", displayType: "box" },
  { name: "Unique Typing Cursor", className: "roy-typing-cursor", category: "advanced", displayType: "text" },
  { name: "Button Shine", className: "btn-shine", category: "button-card", displayType: "button" },
  { name: "Button Ripple Click", className: "btn-ripple", category: "button-card", displayType: "button" },
  { name: "Button Fill Left", className: "btn-fill-left", category: "button-card", displayType: "button" },
  { name: "Button Fill Right", className: "btn-fill-right", category: "button-card", displayType: "button" },
  { name: "Button Fill Top", className: "btn-fill-top", category: "button-card", displayType: "button" },
  { name: "Button Fill Bottom", className: "btn-fill-bottom", category: "button-card", displayType: "button" },
  { name: "Button Outline Draw", className: "btn-outline-draw", category: "button-card", displayType: "button" },
  { name: "Button Glow Pulse", className: "btn-glow-pulse", category: "button-card", displayType: "button" },
  { name: "Button Skew Fill", className: "btn-skew-fill", category: "button-card", displayType: "button" },
  { name: "Button Slide Icon", className: "btn-slide-icon", category: "button-card", displayType: "button" },
  { name: "Button Bounce", className: "btn-bounce", category: "button-card", displayType: "button" },
  { name: "Button Press", className: "btn-press", category: "button-card", displayType: "button" },
  { name: "Button Border Sweep", className: "btn-border-sweep", category: "button-card", displayType: "button" },
  { name: "Button Neon Border", className: "btn-neon-border", category: "button-card", displayType: "button" },
  { name: "Button Gradient Shift", className: "btn-gradient-shift", category: "button-card", displayType: "button" },
  { name: "Button Underline Center", className: "btn-underline-center", category: "button-card", displayType: "button" },
  { name: "Button Shadow Lift", className: "btn-shadow-lift", category: "button-card", displayType: "button" },
  { name: "Button Ghost Fill", className: "btn-ghost-fill", category: "button-card", displayType: "button" },
  { name: "Card Lift", className: "card-lift", category: "button-card", displayType: "card" },
  { name: "Card Tilt 3D", className: "card-tilt-3d", category: "button-card", displayType: "card" },
  { name: "Card Flip", className: "card-flip", category: "button-card", displayType: "card" },
  { name: "Card Spotlight", className: "card-spotlight", category: "button-card", displayType: "card" },
  { name: "Card Reveal", className: "card-reveal", category: "button-card", displayType: "card" },
  { name: "Card Border Glow", className: "card-border-glow", category: "button-card", displayType: "card" },
  { name: "Card Split", className: "card-split", category: "button-card", displayType: "card" },
  { name: "Card Fold Corner", className: "card-fold-corner", category: "button-card", displayType: "card" },
  { name: "Card Slide Up", className: "card-slide-up", category: "button-card", displayType: "card" },
  { name: "Card Glass", className: "card-glass", category: "button-card", displayType: "card" },
  { name: "Card Expand", className: "card-expand", category: "button-card", displayType: "card" },
  { name: "Card Skew Reveal", className: "card-skew-reveal", category: "button-card", displayType: "card" },
  { name: "Card Holographic", className: "card-holographic", category: "button-card", displayType: "card" },
  { name: "Card Pulse Border", className: "card-pulse-border", category: "button-card", displayType: "card" },
  { name: "Image Zoom In", className: "rc-img-zoom-in", category: "hover", displayType: "image" },
  { name: "Image Zoom Out", className: "rc-img-zoom-out", category: "hover", displayType: "image" },
  { name: "Image Pan Right", className: "rc-img-pan-right", category: "hover", displayType: "image" },
  { name: "Image Pan Left", className: "rc-img-pan-left", category: "hover", displayType: "image" },
  { name: "Image Blur Reveal", className: "rc-img-blur-reveal", category: "hover", displayType: "image" },
  { name: "Image Grayscale", className: "rc-img-grayscale", category: "hover", displayType: "image" },
  { name: "Image Sepia", className: "rc-img-sepia", category: "hover", displayType: "image" },
  { name: "Image Brightness", className: "rc-img-brightness", category: "hover", displayType: "image" },
  { name: "Image Contrast", className: "rc-img-contrast", category: "hover", displayType: "image" },
  { name: "Image Rotate Zoom", className: "rc-img-rotate-zoom", category: "hover", displayType: "image" },
  { name: "Image Overlay Slide Up", className: "rc-img-overlay-up", category: "hover", displayType: "image" },
  { name: "Image Overlay Fade", className: "rc-img-overlay-fade", category: "hover", displayType: "image" },
  { name: "Image Split Reveal", className: "rc-img-split-reveal", category: "hover", displayType: "image" },
  { name: "Image Shutter", className: "rc-img-shutter", category: "hover", displayType: "image" },
  { name: "Image Circle Reveal", className: "rc-img-circle-reveal", category: "hover", displayType: "image" },
  { name: "Image Tilt 3D", className: "rc-img-tilt-3d", category: "hover", displayType: "image" },
  { name: "Circle Reveal In", className: "rc-circle-reveal-in", category: "hover", displayType: "box" },
  { name: "Circle Reveal Out", className: "rc-circle-reveal-out", category: "hover", displayType: "box" },
  { name: "Diamond Reveal", className: "rc-diamond-reveal", category: "hover", displayType: "box" },
  { name: "Triangle Reveal", className: "rc-triangle-reveal", category: "hover", displayType: "box" },
  { name: "Cross Reveal", className: "rc-cross-reveal", category: "hover", displayType: "box" },
  { name: "Hexagon Reveal", className: "rc-hexagon-reveal", category: "hover", displayType: "box" },
  { name: "Star Reveal", className: "rc-star-reveal", category: "hover", displayType: "box" },
  { name: "Slide Left Reveal", className: "rc-slide-left-reveal", category: "hover", displayType: "box" },
  { name: "Slide Down Reveal", className: "rc-slide-down-reveal", category: "hover", displayType: "box" },
  { name: "Wipe Reveal", className: "rc-wipe-reveal", category: "hover", displayType: "box" },
  { name: "Skeleton Pulse", className: "rc-skeleton-pulse", category: "loaders", displayType: "loader" },
  { name: "Skeleton Shimmer", className: "rc-skeleton-shimmer", category: "loaders", displayType: "loader" },
  { name: "Skeleton Wave", className: "rc-skeleton-wave", category: "loaders", displayType: "loader" },
  { name: "Skeleton Text", className: "rc-skeleton-text", category: "loaders", displayType: "loader" },
  { name: "Skeleton Card", className: "rc-skeleton-card", category: "loaders", displayType: "loader" },
  { name: "Skeleton Circle", className: "rc-skeleton-circle", category: "loaders", displayType: "loader" },
  { name: "Skeleton Grid", className: "rc-skeleton-grid", category: "loaders", displayType: "loader" },
  { name: "Skeleton Gradient", className: "rc-skeleton-gradient", category: "loaders", displayType: "loader" },
  { name: "Skeleton Blink", className: "rc-skeleton-blink", category: "loaders", displayType: "loader" },
  { name: "Skeleton Fade", className: "rc-skeleton-fade", category: "loaders", displayType: "loader" },
  { name: "Toggle Switch", className: "rc-toggle-switch", category: "scroll-micro", displayType: "box" },
  { name: "Checkbox Anim", className: "rc-checkbox-anim", category: "scroll-micro", displayType: "box" },
  { name: "Radio Pulse", className: "rc-radio-pulse", category: "scroll-micro", displayType: "box" },
  { name: "Input Focus Glow", className: "rc-input-focus-glow", category: "scroll-micro", displayType: "box" },
  { name: "Input Float Label", className: "rc-input-float-label", category: "scroll-micro", displayType: "box" },
  { name: "Tooltip Fade", className: "rc-tooltip-fade", category: "scroll-micro", displayType: "box" },
  { name: "Accordion Slide", className: "rc-accordion-slide", category: "scroll-micro", displayType: "box" },
  { name: "Tab Underline", className: "rc-tab-underline", category: "scroll-micro", displayType: "box" },
  { name: "Dropdown Slide", className: "rc-dropdown-slide", category: "scroll-micro", displayType: "box" },
  { name: "Notification Slide In", className: "rc-notification-slide-in", category: "scroll-micro", displayType: "box" },
  { name: "Progress Bar Fill", className: "rc-progress-bar-fill", category: "scroll-micro", displayType: "box" },
  { name: "Ripple Click", className: "rc-ripple-click", category: "scroll-micro", displayType: "box" },
  { name: "Blur In", className: "rc-blur-in", category: "advanced", displayType: "box" },
  { name: "Blur Out", className: "rc-blur-out", category: "advanced", displayType: "box" },
  { name: "Grayscale In", className: "rc-grayscale-in", category: "advanced", displayType: "box" },
  { name: "Grayscale Out", className: "rc-grayscale-out", category: "advanced", displayType: "box" },
  { name: "Sepia In", className: "rc-sepia-in", category: "advanced", displayType: "box" },
  { name: "Sepia Out", className: "rc-sepia-out", category: "advanced", displayType: "box" },
  { name: "Saturate Pulse", className: "rc-saturate-pulse", category: "advanced", displayType: "box" },
  { name: "Hue Rotate", className: "rc-hue-rotate", category: "advanced", displayType: "box" },
  { name: "Invert Flash", className: "rc-invert-flash", category: "advanced", displayType: "box" },
  { name: "Brightness Pulse", className: "rc-brightness-pulse", category: "advanced", displayType: "box" },
  { name: "Contrast Switch", className: "rc-contrast-switch", category: "advanced", displayType: "box" },
  { name: "Vintage", className: "rc-vintage", category: "advanced", displayType: "box" },
  { name: "Rain", className: "rc-rain", category: "backgrounds", displayType: "bg" },
  { name: "Snow", className: "rc-snow", category: "backgrounds", displayType: "bg" },
  { name: "Lightning", className: "rc-lightning", category: "backgrounds", displayType: "bg" },
  { name: "Clouds", className: "rc-clouds", category: "backgrounds", displayType: "bg" },
  { name: "Fireflies", className: "rc-fireflies", category: "backgrounds", displayType: "bg" },
  { name: "Ocean Waves", className: "rc-ocean-waves", category: "backgrounds", displayType: "bg" },
  { name: "Sunset", className: "rc-sunset", category: "backgrounds", displayType: "bg" },
  { name: "Northern Lights", className: "rc-northern-lights", category: "backgrounds", displayType: "bg" },
  { name: "Fog", className: "rc-fog", category: "backgrounds", displayType: "bg" },
  { name: "Stars Twinkle", className: "rc-stars-twinkle", category: "backgrounds", displayType: "bg" },
  { name: "Status Pulse Green", className: "rc-status-pulse-green", category: "advanced", displayType: "box" },
  { name: "Status Pulse Red", className: "rc-status-pulse-red", category: "advanced", displayType: "box" },
  { name: "Status Pulse Yellow", className: "rc-status-pulse-yellow", category: "advanced", displayType: "box" },
  { name: "Status Breathing Blue", className: "rc-status-breathing-blue", category: "advanced", displayType: "box" },
  { name: "Status Progress Ring", className: "rc-status-progress-ring", category: "advanced", displayType: "box" },
  { name: "Status Loading Bar", className: "rc-status-loading-bar", category: "advanced", displayType: "box" },
  { name: "Status Notification Badge", className: "rc-status-notification-badge", category: "advanced", displayType: "box" },
  { name: "Status Dot Bounce", className: "rc-status-dot-bounce", category: "advanced", displayType: "box" },
  { name: "Status Signal Wave", className: "rc-status-signal-wave", category: "advanced", displayType: "box" },
  { name: "Status Heartbeat", className: "rc-status-heartbeat", category: "advanced", displayType: "box" },
  { name: "Scroll Fade Up", className: "rc-scroll-fade-up", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Fade Left", className: "rc-scroll-fade-left", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Fade Right", className: "rc-scroll-fade-right", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Zoom In", className: "rc-scroll-zoom-in", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Slide In Stagger", className: "rc-scroll-slide-stagger", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Flip In", className: "rc-scroll-flip-in", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Rotate In", className: "rc-scroll-rotate-in", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Scale Bounce", className: "rc-scroll-scale-bounce", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Blur Clear", className: "rc-scroll-blur-clear", category: "scroll-micro", displayType: "box" },
  { name: "Scroll Clip Reveal", className: "rc-scroll-clip-reveal", category: "scroll-micro", displayType: "box" },
  { name: "Ease Linear", className: "rc-ease-linear", category: "advanced", displayType: "box" },
  { name: "Ease In Quad", className: "rc-ease-in-quad", category: "advanced", displayType: "box" },
  { name: "Ease Out Quad", className: "rc-ease-out-quad", category: "advanced", displayType: "box" },
  { name: "Ease In Out Quad", className: "rc-ease-in-out-quad", category: "advanced", displayType: "box" },
  { name: "Ease In Cubic", className: "rc-ease-in-cubic", category: "advanced", displayType: "box" },
  { name: "Ease Out Cubic", className: "rc-ease-out-cubic", category: "advanced", displayType: "box" },
  { name: "Ease In Out Cubic", className: "rc-ease-in-out-cubic", category: "advanced", displayType: "box" },
  { name: "Ease In Back", className: "rc-ease-in-back", category: "advanced", displayType: "box" },
  { name: "Ease Out Back", className: "rc-ease-out-back", category: "advanced", displayType: "box" },
  { name: "Ease In Out Back", className: "rc-ease-in-out-back", category: "advanced", displayType: "box" },
  { name: "Elastic Out", className: "rc-ease-elastic-out", category: "advanced", displayType: "box" },
  { name: "Bounce Out", className: "rc-ease-bounce-out", category: "advanced", displayType: "box" },
  { name: "Glassmorphism", className: "rc-preset-glassmorphism", category: "advanced", displayType: "preset" },
  { name: "Neumorphism", className: "rc-preset-neumorphism", category: "advanced", displayType: "preset" },
  { name: "Claymorphism", className: "rc-preset-claymorphism", category: "advanced", displayType: "preset" },
  { name: "Brutalism", className: "rc-preset-brutalism", category: "advanced", displayType: "preset" },
  { name: "Retro/Pixel", className: "rc-preset-retro-pixel", category: "advanced", displayType: "preset" },
  { name: "Cyberpunk", className: "rc-preset-cyberpunk", category: "advanced", displayType: "preset" },
  { name: "Minimalism", className: "rc-preset-minimalism", category: "advanced", displayType: "preset" },
  { name: "Elevation", className: "rc-preset-elevation", category: "advanced", displayType: "preset" },
  { name: "Gradient Border", className: "rc-preset-gradient-border", category: "advanced", displayType: "preset" },
  { name: "Dark Glass", className: "rc-preset-dark-glass", category: "advanced", displayType: "preset" },
  { name: "Soft UI", className: "rc-preset-soft-ui", category: "advanced", displayType: "preset" },
  { name: "Neobrutalism", className: "rc-preset-neobrutalism", category: "advanced", displayType: "preset" },
  { name: "Fade Through", className: "rc-fade-through", category: "scroll-micro", displayType: "box" },
  { name: "Slide Over Left", className: "rc-slide-over-left", category: "scroll-micro", displayType: "box" },
  { name: "Slide Over Right", className: "rc-slide-over-right", category: "scroll-micro", displayType: "box" },
  { name: "Slide Over Up", className: "rc-slide-over-up", category: "scroll-micro", displayType: "box" },
  { name: "Zoom Fade", className: "rc-zoom-fade", category: "scroll-micro", displayType: "box" },
  { name: "Flip Transition", className: "rc-flip-transition", category: "scroll-micro", displayType: "box" },
  { name: "Dissolve", className: "rc-dissolve", category: "scroll-micro", displayType: "box" },
  { name: "CurtaIn", className: "rc-curtain-in", category: "scroll-micro", displayType: "box" },
  { name: "Focus Visible Ring", className: "rc-focus-visible-ring", category: "advanced", displayType: "box" },
  { name: "Skip Link", className: "rc-skip-link", category: "advanced", displayType: "box" },
  { name: "Reduced Motion Fade", className: "rc-reduced-motion-fade", category: "advanced", displayType: "box" },
  { name: "Reduced Motion Slide", className: "rc-reduced-motion-slide", category: "advanced", displayType: "box" },
  { name: "High Contrast Border", className: "rc-high-contrast-border", category: "advanced", displayType: "box" },
  { name: "Screen Reader Only", className: "rc-sr-only", category: "advanced", displayType: "box" },
  { name: "Motion Safe Bounce", className: "rc-motion-safe-bounce", category: "advanced", displayType: "box" },
  { name: "Motion Safe Pulse", className: "rc-motion-safe-pulse", category: "advanced", displayType: "box" },
  { name: "Icon Spin", className: "rc-icon-spin", category: "advanced", displayType: "icon" },
  { name: "Icon Bounce", className: "rc-icon-bounce", category: "advanced", displayType: "icon" },
  { name: "Icon Pulse", className: "rc-icon-pulse", category: "advanced", displayType: "icon" },
  { name: "Icon Shake", className: "rc-icon-shake", category: "advanced", displayType: "icon" },
  { name: "Icon Flip", className: "rc-icon-flip", category: "advanced", displayType: "icon" },
  { name: "Icon Swing", className: "rc-icon-swing", category: "advanced", displayType: "icon" },
  { name: "Icon Tada", className: "rc-icon-tada", category: "advanced", displayType: "icon" },
  { name: "Icon Wobble", className: "rc-icon-wobble", category: "advanced", displayType: "icon" },
  { name: "Icon Fade In", className: "rc-icon-fade-in", category: "advanced", displayType: "icon" },
  { name: "Icon Drop In", className: "rc-icon-drop-in", category: "advanced", displayType: "icon" },
  { name: "Icon Rubber Band", className: "rc-icon-rubber-band", category: "advanced", displayType: "icon" },
  { name: "Icon Beat", className: "rc-icon-beat", category: "advanced", displayType: "icon" },
  { name: "Anchor Tooltip", className: "rc-anchor-tooltip", category: "navigation", displayType: "box" },
  { name: "Auto Height Expand", className: "rc-auto-height-expand", category: "navigation", displayType: "box" },
  { name: "Backdrop Multi Filter", className: "rc-backdrop-multi-filter", category: "backgrounds", displayType: "box" },
  { name: "Balanced Text", className: "rc-balanced-text", category: "text", displayType: "box" },
  { name: "Color Mix Gradient", className: "rc-color-mix-gradient", category: "backgrounds", displayType: "box" },
  { name: "Color Mix Mesh", className: "rc-color-mix-mesh", category: "backgrounds", displayType: "box" },
  { name: "Conic Gradient Clock", className: "rc-conic-gradient-clock", category: "backgrounds", displayType: "box" },
  { name: "Container Query Card", className: "rc-container-query-card", category: "button-card", displayType: "box" },
  { name: "Double Conic Spinner", className: "rc-double-conic-spinner", category: "loaders", displayType: "box" },
  { name: "Film Grain", className: "rc-film-grain", category: "backgrounds", displayType: "box" },
  { name: "Has Parent Highlight", className: "rc-has-parent-highlight", category: "scroll-micro", displayType: "box" },
  { name: "Hover Bounce", className: "rc-hover-bounce", category: "hover", displayType: "box" },
  { name: "Infinity Loop", className: "rc-infinity-loop", category: "3d-transforms", displayType: "box" },
  { name: "Interpolate Size Accordion", className: "rc-interpolate-size-accordion", category: "navigation", displayType: "box" },
  { name: "Light Dark Auto", className: "rc-light-dark-auto", category: "navigation", displayType: "box" },
  { name: "Mask Composite Reveal", className: "rc-mask-composite-reveal", category: "advanced", displayType: "box" },
  { name: "Mask Linear Wipe", className: "rc-mask-linear-wipe", category: "advanced", displayType: "box" },
  { name: "Mask Radial Reveal", className: "rc-mask-radial-reveal", category: "advanced", displayType: "box" },
  { name: "Mix Blend Difference", className: "rc-mix-blend-difference", category: "backgrounds", displayType: "box" },
  { name: "Mix Blend Exclusion", className: "rc-mix-blend-exclusion", category: "backgrounds", displayType: "box" },
  { name: "Offset Path Draw", className: "rc-offset-path-draw", category: "3d-transforms", displayType: "box" },
  { name: "Offset Path Orbit", className: "rc-offset-path-orbit", category: "3d-transforms", displayType: "box" },
  { name: "Offset Path Wave", className: "rc-offset-path-wave", category: "3d-transforms", displayType: "box" },
  { name: "Painting Oil", className: "rc-painting-oil", category: "backgrounds", displayType: "box" },
  { name: "Pencil Sketch", className: "rc-pencil-sketch", category: "backgrounds", displayType: "box" },
  { name: "Property Angle Rotate", className: "rc-property-angle-rotate", category: "3d-transforms", displayType: "box" },
  { name: "Property Color Shift", className: "rc-property-color-shift", category: "advanced", displayType: "box" },
  { name: "Property Conic Loader", className: "rc-property-conic-loader", category: "loaders", displayType: "box" },
  { name: "Property Gradient Flow", className: "rc-property-gradient-flow", category: "advanced", displayType: "box" },
  { name: "Property Hue Cycle", className: "rc-property-hue-cycle", category: "advanced", displayType: "box" },
  { name: "Property Progress Bar", className: "rc-property-progress-bar", category: "loaders", displayType: "box" },
  { name: "Property Shadow Breathe", className: "rc-property-shadow-breathe", category: "advanced", displayType: "box" },
  { name: "Relative Color Hover", className: "rc-relative-color-hover", category: "hover", displayType: "box" },
  { name: "Relative Color Tint", className: "rc-relative-color-tint", category: "backgrounds", displayType: "box" },
  { name: "Scrollbar Gutter Stable", className: "rc-scrollbar-gutter-stable", category: "navigation", displayType: "box" },
  { name: "Starting Style Drop In", className: "rc-starting-style-drop-in", category: "scroll-micro", displayType: "box" },
  { name: "Starting Style Fade", className: "rc-starting-style-fade", category: "scroll-micro", displayType: "box" },
  { name: "SVG Displacement Wave", className: "rc-svg-displacement-wave", category: "advanced", displayType: "box" },
  { name: "SVG Gooey Merge", className: "rc-svg-gooey-merge", category: "advanced", displayType: "box" },
  { name: "SVG Turbulence Distort", className: "rc-svg-turbulence-distort", category: "advanced", displayType: "box" },
  { name: "View Timeline Reveal", className: "rc-view-timeline-reveal", category: "advanced", displayType: "box" },
  { name: "View Transition Snapshot", className: "rc-view-transition-snapshot", category: "advanced", displayType: "box" },
  { name: "Entrance Curtain", className: "rc-entrance-curtain", category: "core-animations", displayType: "box" },
  { name: "Entrance Scale Blur", className: "rc-entrance-scale-blur", category: "core-animations", displayType: "box" },
  { name: "Entrance Slide Blur", className: "rc-entrance-slide-blur", category: "core-animations", displayType: "box" },
  { name: "Exit Fade Scale", className: "rc-exit-fade-scale", category: "core-animations", displayType: "box" },
  { name: "Exit Slide Down", className: "rc-exit-slide-down", category: "core-animations", displayType: "box" },
  { name: "Stagger Fade Up", className: "rc-stagger-fade-up", category: "core-animations", displayType: "box" },
  { name: "Stagger Scale In", className: "rc-stagger-scale-in", category: "core-animations", displayType: "box" },
  { name: "Hover Image Zoom", className: "rc-hover-image-zoom", category: "hover", displayType: "box" },
  { name: "Hover Border Gradient", className: "rc-hover-border-gradient", category: "hover", displayType: "box" },
  { name: "Hover Arrow Move", className: "rc-hover-arrow-move", category: "hover", displayType: "box" },
  { name: "Text Gradient Animate", className: "rc-text-gradient-animate", category: "text", displayType: "text" },
  { name: "Text Clip Reveal", className: "rc-text-clip-reveal", category: "text", displayType: "text" },
  { name: "Text Shadow Glow Pulse", className: "rc-text-shadow-glow-pulse", category: "text", displayType: "text" },
  { name: "BG Dots Grid", className: "rc-bg-dots-grid", category: "backgrounds", displayType: "box" },
  { name: "BG Lines", className: "rc-bg-lines", category: "backgrounds", displayType: "box" },
  { name: "3D Card Tilt", className: "rc-3d-card-tilt", category: "3d-transforms", displayType: "box" },
  { name: "3D Flip X", className: "rc-3d-flip-x", category: "3d-transforms", displayType: "box" },
  { name: "3D Flip Y", className: "rc-3d-flip-y", category: "3d-transforms", displayType: "box" },
];

export const categoryCounts: Record<string, number> = {
  all: 848,
  "core-animations": 133,
  "hover": 78,
  "text": 50,
  "backgrounds": 134,
  "loaders": 59,
  "3d-transforms": 58,
  "button-card": 118,
  "forms": 14,
  "navigation": 35,
  "scroll-micro": 53,
  "advanced": 196,
};
