// ============================================================
// RoyCSS v3.0 — Effect Library Index (lightweight, no CSS)
// Effects: 568 | Categories: 36
// Auto-generated — do not edit manually.
// ============================================================

import type { FerrumEffectIndex, Category } from "./types";
export type { FerrumEffectIndex, Category };

export const categories: Category[] = [
  { id: "3d", name: "3D", icon: "Move3D" },
  { id: "attention", name: "Attention", icon: "Eye" },
  { id: "background", name: "Background", icon: "ImageIcon" },
  { id: "blend-modes", name: "Blend Modes", icon: "Eye" },
  { id: "borders", name: "Borders", icon: "Box" },
  { id: "buttons", name: "Buttons", icon: "Zap" },
  { id: "cards", name: "Cards", icon: "Layers" },
  { id: "clip-path", name: "Clip Path", icon: "Sparkles" },
  { id: "cursor", name: "Cursor", icon: "MousePointer" },
  { id: "design-presets", name: "Design Presets", icon: "Sparkles" },
  { id: "entrance", name: "Entrance", icon: "LogIn" },
  { id: "exit", name: "Exit", icon: "LogOut" },
  { id: "filter", name: "Filter", icon: "Eye" },
  { id: "forms", name: "Forms", icon: "Eye" },
  { id: "glass", name: "Glass", icon: "Layers" },
  { id: "hover", name: "Hover", icon: "MousePointer" },
  { id: "image-hover", name: "Image Hover", icon: "ImageIcon" },
  { id: "loading", name: "Loading", icon: "Loader2" },
  { id: "mask", name: "Mask", icon: "Box" },
  { id: "micro-interaction", name: "Micro", icon: "Zap" },
  { id: "misc", name: "Misc", icon: "Zap" },
  { id: "modern-css", name: "Modern CSS", icon: "Code" },
  { id: "next-gen-css", name: "Next-Gen CSS", icon: "Sparkles" },
  { id: "nature", name: "Nature", icon: "Sparkles" },
  { id: "navigation", name: "Navigation", icon: "Menu" },
  { id: "offset-path", name: "Offset Path", icon: "Move3D" },
  { id: "page-transition", name: "Page Trans.", icon: "Move3D" },
  { id: "particles", name: "Particles", icon: "Sparkles" },
  { id: "property", name: "Property", icon: "Box" },
  { id: "scroll", name: "Scroll", icon: "Move3D" },
  { id: "specialized", name: "Specialized", icon: "Sparkles" },
  { id: "svg", name: "SVG", icon: "Box" },
  { id: "text", name: "Text", icon: "Type" },
  { id: "transform", name: "Transform", icon: "Box" },
  { id: "unique", name: "Unique", icon: "Crown" },
  { id: "visual-effects", name: "Visual FX", icon: "Eye" },
];

export const effects: FerrumEffectIndex[] = [
  { name: "3D Book", className: "roycss-3d-book", category: "3d", displayType: "box" },
  { name: "3D Gallery", className: "roycss-3d-gallery", category: "3d", displayType: "box" },
  { name: "3D Poster", className: "roycss-3d-poster", category: "3d", displayType: "box" },
  { name: "Accordion 3D", className: "roycss-accordion-3d", category: "3d", displayType: "box" },
  { name: "Cube Face", className: "roycss-cube-face", category: "3d", displayType: "box" },
  { name: "Cube Rotate", className: "roycss-cube-rotate", category: "3d", displayType: "box" },
  { name: "Perspective Tilt", className: "roycss-perspective-tilt", category: "3d", displayType: "box" },
  { name: "Rotate 3D", className: "roycss-rotate-3d", category: "3d", displayType: "box" },
  { name: "Scale 3D", className: "roycss-scale-3d", category: "3d", displayType: "box" },
  { name: "Skew 3D", className: "roycss-skew-3d", category: "3d", displayType: "box" },
  { name: "Bounce Rotate", className: "roycss-bounce-rotate", category: "attention", displayType: "box" },
  { name: "Breathe", className: "roycss-breathe", category: "attention", displayType: "box" },
  { name: "Float", className: "roycss-float", category: "attention", displayType: "box" },
  { name: "Head Shake", className: "roycss-head-shake", category: "attention", displayType: "box" },
  { name: "Heartbeat", className: "roycss-heartbeat", category: "attention", displayType: "box" },
  { name: "Jello", className: "roycss-jello", category: "attention", displayType: "box" },
  { name: "Jiggle", className: "roycss-jiggle", category: "attention", displayType: "box" },
  { name: "Pendulum", className: "roycss-pendulum", category: "attention", displayType: "box" },
  { name: "Pulse Glow", className: "roycss-pulse-glow", category: "attention", displayType: "box" },
  { name: "Pulse Soft", className: "roycss-pulse-soft", category: "attention", displayType: "box" },
  { name: "Rubber Band", className: "roycss-rubber-band", category: "attention", displayType: "box" },
  { name: "Shake", className: "roycss-shake", category: "attention", displayType: "box" },
  { name: "Stretch", className: "roycss-stretch", category: "attention", displayType: "box" },
  { name: "Sway", className: "roycss-sway", category: "attention", displayType: "box" },
  { name: "Swing", className: "roycss-swing", category: "attention", displayType: "box" },
  { name: "Tada", className: "roycss-tada", category: "attention", displayType: "box" },
  { name: "Vibrate", className: "roycss-vibrate", category: "attention", displayType: "box" },
  { name: "Wiggle", className: "roycss-wiggle", category: "attention", displayType: "box" },
  { name: "Wobble", className: "roycss-wobble", category: "attention", displayType: "box" },
  { name: "Background Animated Gradient", className: "roycss-bg-animated-gradient", category: "background", displayType: "bg" },
  { name: "Background Aurora", className: "roycss-bg-aurora", category: "background", displayType: "bg" },
  { name: "Background Checkerboard", className: "roycss-bg-checkerboard", category: "background", displayType: "bg" },
  { name: "Background Concentric", className: "roycss-bg-concentric", category: "background", displayType: "bg" },
  { name: "Background Conic Gradient", className: "roycss-bg-conic-gradient", category: "background", displayType: "bg" },
  { name: "Background Diagonal Stripes", className: "roycss-bg-diagonal-stripes", category: "background", displayType: "bg" },
  { name: "Background Dot Pattern", className: "roycss-bg-dot-pattern", category: "background", displayType: "bg" },
  { name: "Background Gradient Pulse", className: "roycss-bg-gradient-pulse", category: "background", displayType: "bg" },
  { name: "Background Gradient Sweep", className: "roycss-bg-gradient-sweep", category: "background", displayType: "bg" },
  { name: "Background Grid Lines", className: "roycss-bg-grid-lines", category: "background", displayType: "bg" },
  { name: "Background Hexagon", className: "roycss-bg-hexagon", category: "background", displayType: "bg" },
  { name: "Background Lava Lamp", className: "roycss-bg-lava-lamp", category: "background", displayType: "bg" },
  { name: "Background Mesh Gradient", className: "roycss-bg-mesh-gradient", category: "background", displayType: "bg" },
  { name: "Background Noise", className: "roycss-bg-noise", category: "background", displayType: "bg" },
  { name: "Background Plaid", className: "roycss-bg-plaid", category: "background", displayType: "bg" },
  { name: "Background Plasma", className: "roycss-bg-plasma", category: "background", displayType: "bg" },
  { name: "Background Radial Rays", className: "roycss-bg-radial-rays", category: "background", displayType: "bg" },
  { name: "Background Smoke", className: "roycss-bg-smoke", category: "background", displayType: "bg" },
  { name: "Background Starfield", className: "roycss-bg-starfield", category: "background", displayType: "bg" },
  { name: "Background Stripes", className: "roycss-bg-stripes", category: "background", displayType: "bg" },
  { name: "Background Sunburst", className: "roycss-bg-sunburst", category: "background", displayType: "bg" },
  { name: "Background Sunset", className: "roycss-bg-sunset", category: "background", displayType: "bg" },
  { name: "Background Triangles", className: "roycss-bg-triangles", category: "background", displayType: "bg" },
  { name: "Background Waves", className: "roycss-bg-waves", category: "background", displayType: "bg" },
  { name: "Background Zigzag", className: "roycss-bg-zigzag", category: "background", displayType: "bg" },
  { name: "Mix Blend Difference", className: "roycss-mix-blend-difference", category: "blend-modes", displayType: "box" },
  { name: "Mix Blend Exclusion", className: "roycss-mix-blend-exclusion", category: "blend-modes", displayType: "box" },
  { name: "Border Animated Dash", className: "roycss-border-animated-dash", category: "borders", displayType: "box" },
  { name: "Border Banner", className: "roycss-border-banner", category: "borders", displayType: "box" },
  { name: "Border Clip Path", className: "roycss-border-clip-path", category: "borders", displayType: "box" },
  { name: "Border Corner Brackets", className: "roycss-border-corner-brackets", category: "borders", displayType: "box" },
  { name: "Border Dashed Draw", className: "roycss-border-dashed-draw", category: "borders", displayType: "box" },
  { name: "Border Double Glow", className: "roycss-border-double-glow", category: "borders", displayType: "box" },
  { name: "Border Frame", className: "roycss-border-frame", category: "borders", displayType: "box" },
  { name: "Border Gradient Animated", className: "roycss-border-gradient-animated", category: "borders", displayType: "box" },
  { name: "Border Inset Glow", className: "roycss-border-inset-glow", category: "borders", displayType: "box" },
  { name: "Border Marching Ants", className: "roycss-border-marching-ants", category: "borders", displayType: "box" },
  { name: "Border Neon Pulse", className: "roycss-border-neon-pulse", category: "borders", displayType: "box" },
  { name: "Border Polaroid", className: "roycss-border-polaroid", category: "borders", displayType: "box" },
  { name: "Border Ribbon", className: "roycss-border-ribbon", category: "borders", displayType: "box" },
  { name: "Border Sticker", className: "roycss-border-sticker", category: "borders", displayType: "box" },
  { name: "Border Torn Paper", className: "roycss-border-torn-paper", category: "borders", displayType: "box" },
  { name: "Button 3D Push", className: "roycss-btn-3d-push", category: "buttons", displayType: "button" },
  { name: "Button Arrow Slide", className: "roycss-btn-arrow-slide", category: "buttons", displayType: "button" },
  { name: "Button Border Draw", className: "roycss-btn-border-draw", category: "buttons", displayType: "button" },
  { name: "Button Border Glow", className: "roycss-btn-border-glow", category: "buttons", displayType: "button" },
  { name: "Button Bounce", className: "roycss-btn-bounce", category: "buttons", displayType: "button" },
  { name: "Button Expand", className: "roycss-btn-expand", category: "buttons", displayType: "button" },
  { name: "Button Fill Slide", className: "roycss-btn-fill-slide", category: "buttons", displayType: "button" },
  { name: "Button Flip", className: "roycss-btn-flip", category: "buttons", displayType: "button" },
  { name: "Button Glow", className: "roycss-btn-glow", category: "buttons", displayType: "button" },
  { name: "Button Gradient", className: "roycss-btn-gradient", category: "buttons", displayType: "button" },
  { name: "Button Icon Slide", className: "roycss-btn-icon-slide", category: "buttons", displayType: "button" },
  { name: "Button Lift", className: "roycss-btn-lift", category: "buttons", displayType: "button" },
  { name: "Button Liquid", className: "roycss-btn-liquid", category: "buttons", displayType: "button" },
  { name: "Button Morph", className: "roycss-btn-morph", category: "buttons", displayType: "button" },
  { name: "Button Neon", className: "roycss-btn-neon", category: "buttons", displayType: "button" },
  { name: "Button Outline Fill", className: "roycss-btn-outline-fill", category: "buttons", displayType: "button" },
  { name: "Button Press", className: "roycss-btn-press", category: "buttons", displayType: "button" },
  { name: "Button Pulse", className: "roycss-btn-pulse", category: "buttons", displayType: "button" },
  { name: "Button Ripple", className: "roycss-btn-ripple", category: "buttons", displayType: "button" },
  { name: "Button Rotate", className: "roycss-btn-rotate", category: "buttons", displayType: "button" },
  { name: "Button Shadow Push", className: "roycss-btn-shadow-push", category: "buttons", displayType: "button" },
  { name: "Button Shine Sweep", className: "roycss-btn-shine-sweep", category: "buttons", displayType: "button" },
  { name: "Button Skew", className: "roycss-btn-skew", category: "buttons", displayType: "button" },
  { name: "Button Slide Bg", className: "roycss-btn-slide-bg", category: "buttons", displayType: "button" },
  { name: "Button Sparkle", className: "roycss-btn-sparkle", category: "buttons", displayType: "button" },
  { name: "Card Flip", className: "roycss-card-flip", category: "cards", displayType: "card" },
  { name: "Card Flip Back", className: "roycss-card-flip-back", category: "cards", displayType: "card" },
  { name: "Card Flip Inner", className: "roycss-card-flip-inner", category: "cards", displayType: "card" },
  { name: "Card Glassmorphism", className: "roycss-card-glassmorphism", category: "cards", displayType: "card" },
  { name: "Card Gradient Border", className: "roycss-card-gradient-border", category: "cards", displayType: "card" },
  { name: "Card Hover Border", className: "roycss-card-hover-border", category: "cards", displayType: "card" },
  { name: "Card Hover Color", className: "roycss-card-hover-color", category: "cards", displayType: "card" },
  { name: "Card Hover Fade", className: "roycss-card-hover-fade", category: "cards", displayType: "card" },
  { name: "Card Hover Flip", className: "roycss-card-hover-flip", category: "cards", displayType: "card" },
  { name: "Card Hover Glow", className: "roycss-card-hover-glow", category: "cards", displayType: "card" },
  { name: "Card Hover Lift", className: "roycss-card-hover-lift", category: "cards", displayType: "card" },
  { name: "Card Hover Press", className: "roycss-card-hover-press", category: "cards", displayType: "card" },
  { name: "Card Hover Push", className: "roycss-card-hover-push", category: "cards", displayType: "card" },
  { name: "Card Hover Reveal", className: "roycss-card-hover-reveal", category: "cards", displayType: "card" },
  { name: "Card Hover Rotate", className: "roycss-card-hover-rotate", category: "cards", displayType: "card" },
  { name: "Card Hover Skew", className: "roycss-card-hover-skew", category: "cards", displayType: "card" },
  { name: "Card Hover Slide", className: "roycss-card-hover-slide", category: "cards", displayType: "card" },
  { name: "Card Hover Swing", className: "roycss-card-hover-swing", category: "cards", displayType: "card" },
  { name: "Card Hover Tada", className: "roycss-card-hover-tada", category: "cards", displayType: "card" },
  { name: "Card Hover Wobble", className: "roycss-card-hover-wobble", category: "cards", displayType: "card" },
  { name: "Card Hover Zoom", className: "roycss-card-hover-zoom", category: "cards", displayType: "card" },
  { name: "Card Neon", className: "roycss-card-neon", category: "cards", displayType: "card" },
  { name: "Card Shuffle", className: "roycss-card-shuffle", category: "cards", displayType: "card" },
  { name: "Card Spotlight", className: "roycss-card-spotlight", category: "cards", displayType: "card" },
  { name: "Clip Path Hexagon", className: "roycss-clip-path-hexagon", category: "clip-path", displayType: "box" },
  { name: "Clip Path Star", className: "roycss-clip-path-star", category: "clip-path", displayType: "box" },
  { name: "Cursor Arrow Bounce", className: "roycss-cursor-arrow-bounce", category: "cursor", displayType: "box" },
  { name: "Cursor Blob", className: "roycss-cursor-blob", category: "cursor", displayType: "box" },
  { name: "Cursor Crosshair", className: "roycss-cursor-crosshair", category: "cursor", displayType: "box" },
  { name: "Cursor Firefly", className: "roycss-cursor-firefly", category: "cursor", displayType: "box" },
  { name: "Cursor Glow Dot", className: "roycss-cursor-glow-dot", category: "cursor", displayType: "box" },
  { name: "Cursor Gradient Trail", className: "roycss-cursor-gradient-trail", category: "cursor", displayType: "box" },
  { name: "Cursor Magnetic", className: "roycss-cursor-magnetic", category: "cursor", displayType: "box" },
  { name: "Cursor Pulse Ring", className: "roycss-cursor-pulse-ring", category: "cursor", displayType: "box" },
  { name: "Cursor Ring", className: "roycss-cursor-ring", category: "cursor", displayType: "box" },
  { name: "Cursor Ripple", className: "roycss-cursor-ripple", category: "cursor", displayType: "box" },
  { name: "Cursor Spotlight", className: "roycss-cursor-spotlight", category: "cursor", displayType: "box" },
  { name: "Cursor Trail", className: "roycss-cursor-trail", category: "cursor", displayType: "box" },
  { name: "Apple Bounce Settle", className: "roycss-apple-bounce-settle", category: "design-presets", displayType: "box" },
  { name: "Apple Elastic Scale", className: "roycss-apple-elastic-scale", category: "design-presets", displayType: "box" },
  { name: "Apple Flip Spring", className: "roycss-apple-flip-spring", category: "design-presets", displayType: "box" },
  { name: "Apple Frosted Vibrancy", className: "roycss-apple-frosted-vibrancy", category: "design-presets", displayType: "box" },
  { name: "Apple Material Thick", className: "roycss-apple-material-thick", category: "design-presets", displayType: "box" },
  { name: "Apple Material Thin", className: "roycss-apple-material-thin", category: "design-presets", displayType: "box" },
  { name: "Apple Sidebar Material", className: "roycss-apple-sidebar-material", category: "design-presets", displayType: "box" },
  { name: "Apple Squish In", className: "roycss-apple-squish-in", category: "design-presets", displayType: "box" },
  { name: "Apple Squish Out", className: "roycss-apple-squish-out", category: "design-presets", displayType: "box" },
  { name: "Apple Ultra Thin", className: "roycss-apple-ultra-thin", category: "design-presets", displayType: "box" },
  { name: "Apple Vibrancy Dark", className: "roycss-apple-vibrancy-dark", category: "design-presets", displayType: "box" },
  { name: "Apple Vibrancy Light", className: "roycss-apple-vibrancy-light", category: "design-presets", displayType: "box" },
  { name: "Linear Aurora Glow", className: "roycss-linear-aurora-glow", category: "design-presets", displayType: "box" },
  { name: "Linear Card Lift", className: "roycss-linear-card-lift", category: "design-presets", displayType: "box" },
  { name: "Linear Dark Surface", className: "roycss-linear-dark-surface", category: "design-presets", displayType: "box" },
  { name: "Linear Depth Shadow", className: "roycss-linear-depth-shadow", category: "design-presets", displayType: "box" },
  { name: "Linear Glow Border", className: "roycss-linear-glow-border", category: "design-presets", displayType: "box" },
  { name: "Linear Gradient Mesh Bg", className: "roycss-linear-gradient-mesh-bg", category: "design-presets", displayType: "box" },
  { name: "Linear Gradient Sweep", className: "roycss-linear-gradient-sweep", category: "design-presets", displayType: "box" },
  { name: "Linear Icon Bounce", className: "roycss-linear-icon-bounce", category: "design-presets", displayType: "box" },
  { name: "Linear Magnetic Pull", className: "roycss-linear-magnetic-pull", category: "design-presets", displayType: "box" },
  { name: "Linear Noise Overlay", className: "roycss-linear-noise-overlay", category: "design-presets", displayType: "box" },
  { name: "Linear Shimmer Hover", className: "roycss-linear-shimmer-hover", category: "design-presets", displayType: "box" },
  { name: "Linear Spotlight", className: "roycss-linear-spotlight", category: "design-presets", displayType: "box" },
  { name: "Linear Text Glow", className: "roycss-linear-text-glow", category: "design-presets", displayType: "box" },
  { name: "Material Container Transform", className: "roycss-material-container-transform", category: "design-presets", displayType: "box" },
  { name: "Material Elevation 1", className: "roycss-material-elevation-1", category: "design-presets", displayType: "box" },
  { name: "Material Elevation 3", className: "roycss-material-elevation-3", category: "design-presets", displayType: "box" },
  { name: "Material Elevation 5", className: "roycss-material-elevation-5", category: "design-presets", displayType: "box" },
  { name: "Material Emphasized", className: "roycss-material-emphasized", category: "design-presets", displayType: "box" },
  { name: "Material Emphasized Decel", className: "roycss-material-emphasized-decel", category: "design-presets", displayType: "box" },
  { name: "Material Fab Scale", className: "roycss-material-fab-scale", category: "design-presets", displayType: "box" },
  { name: "Material Spring Down", className: "roycss-material-spring-down", category: "design-presets", displayType: "box" },
  { name: "Material Spring Up", className: "roycss-material-spring-up", category: "design-presets", displayType: "box" },
  { name: "Material State Layer", className: "roycss-material-state-layer", category: "design-presets", displayType: "box" },
  { name: "Material State Layer Surface", className: "roycss-material-state-layer-surface", category: "design-presets", displayType: "box" },
  { name: "Material Surface Tint", className: "roycss-material-surface-tint", category: "design-presets", displayType: "box" },
  { name: "Blur In", className: "roycss-blur-in", category: "entrance", displayType: "box" },
  { name: "Blur In Up", className: "roycss-blur-in-up", category: "entrance", displayType: "box" },
  { name: "Bounce In", className: "roycss-bounce-in", category: "entrance", displayType: "box" },
  { name: "Bounce In Down", className: "roycss-bounce-in-down", category: "entrance", displayType: "box" },
  { name: "Bounce In Left", className: "roycss-bounce-in-left", category: "entrance", displayType: "box" },
  { name: "Bounce In Right", className: "roycss-bounce-in-right", category: "entrance", displayType: "box" },
  { name: "Bounce In Up", className: "roycss-bounce-in-up", category: "entrance", displayType: "box" },
  { name: "Drop In", className: "roycss-drop-in", category: "entrance", displayType: "box" },
  { name: "Fade In", className: "roycss-fade-in", category: "entrance", displayType: "box" },
  { name: "Fade In Bl", className: "roycss-fade-in-bl", category: "entrance", displayType: "box" },
  { name: "Fade In Br", className: "roycss-fade-in-br", category: "entrance", displayType: "box" },
  { name: "Fade In Down", className: "roycss-fade-in-down", category: "entrance", displayType: "box" },
  { name: "Fade In Left", className: "roycss-fade-in-left", category: "entrance", displayType: "box" },
  { name: "Fade In Right", className: "roycss-fade-in-right", category: "entrance", displayType: "box" },
  { name: "Fade In Up", className: "roycss-fade-in-up", category: "entrance", displayType: "box" },
  { name: "Flip In X", className: "roycss-flip-in-x", category: "entrance", displayType: "box" },
  { name: "Flip In Y", className: "roycss-flip-in-y", category: "entrance", displayType: "box" },
  { name: "Jack In Box", className: "roycss-jack-in-box", category: "entrance", displayType: "box" },
  { name: "Light Speed In", className: "roycss-light-speed-in", category: "entrance", displayType: "box" },
  { name: "Pop In", className: "roycss-pop-in", category: "entrance", displayType: "box" },
  { name: "Roll In", className: "roycss-roll-in", category: "entrance", displayType: "box" },
  { name: "Rotate Spin", className: "roycss-rotate-spin", category: "entrance", displayType: "box" },
  { name: "Slide Diagonal", className: "roycss-slide-diagonal", category: "entrance", displayType: "box" },
  { name: "Slide In Bottom", className: "roycss-slide-in-bottom", category: "entrance", displayType: "box" },
  { name: "Slide In Left", className: "roycss-slide-in-left", category: "entrance", displayType: "box" },
  { name: "Slide In Right", className: "roycss-slide-in-right", category: "entrance", displayType: "box" },
  { name: "Slide In Top", className: "roycss-slide-in-top", category: "entrance", displayType: "box" },
  { name: "Slide Rotate In", className: "roycss-slide-rotate-in", category: "entrance", displayType: "box" },
  { name: "Snap In", className: "roycss-snap-in", category: "entrance", displayType: "box" },
  { name: "Spring In", className: "roycss-spring-in", category: "entrance", displayType: "box" },
  { name: "Swing In", className: "roycss-swing-in", category: "entrance", displayType: "box" },
  { name: "Zoom In", className: "roycss-zoom-in", category: "entrance", displayType: "box" },
  { name: "Zoom In Down", className: "roycss-zoom-in-down", category: "entrance", displayType: "box" },
  { name: "Zoom In Left", className: "roycss-zoom-in-left", category: "entrance", displayType: "box" },
  { name: "Zoom In Right", className: "roycss-zoom-in-right", category: "entrance", displayType: "box" },
  { name: "Zoom In Up", className: "roycss-zoom-in-up", category: "entrance", displayType: "box" },
  { name: "Blur Out", className: "roycss-blur-out", category: "exit", displayType: "box" },
  { name: "Blur Out Down", className: "roycss-blur-out-down", category: "exit", displayType: "box" },
  { name: "Fade Out", className: "roycss-fade-out", category: "exit", displayType: "box" },
  { name: "Fade Out Down", className: "roycss-fade-out-down", category: "exit", displayType: "box" },
  { name: "Fade Out Left", className: "roycss-fade-out-left", category: "exit", displayType: "box" },
  { name: "Fade Out Right", className: "roycss-fade-out-right", category: "exit", displayType: "box" },
  { name: "Fade Out Up", className: "roycss-fade-out-up", category: "exit", displayType: "box" },
  { name: "Pop Out", className: "roycss-pop-out", category: "exit", displayType: "box" },
  { name: "Roll Out", className: "roycss-roll-out", category: "exit", displayType: "box" },
  { name: "Rotate Out", className: "roycss-rotate-out", category: "exit", displayType: "box" },
  { name: "Slide Out Bottom", className: "roycss-slide-out-bottom", category: "exit", displayType: "box" },
  { name: "Slide Out Left", className: "roycss-slide-out-left", category: "exit", displayType: "box" },
  { name: "Slide Out Right", className: "roycss-slide-out-right", category: "exit", displayType: "box" },
  { name: "Slide Out Top", className: "roycss-slide-out-top", category: "exit", displayType: "box" },
  { name: "Zoom Out", className: "roycss-zoom-out", category: "exit", displayType: "box" },
  { name: "Zoom Out Left", className: "roycss-zoom-out-left", category: "exit", displayType: "box" },
  { name: "Zoom Out Up", className: "roycss-zoom-out-up", category: "exit", displayType: "box" },
  { name: "Filter Blur Focus", className: "roycss-filter-blur-focus", category: "filter", displayType: "box" },
  { name: "Filter Cinematic", className: "roycss-filter-cinematic", category: "filter", displayType: "box" },
  { name: "Filter Contrast", className: "roycss-filter-contrast", category: "filter", displayType: "box" },
  { name: "Filter Dramatic", className: "roycss-filter-dramatic", category: "filter", displayType: "box" },
  { name: "Filter Dreamy", className: "roycss-filter-dreamy", category: "filter", displayType: "box" },
  { name: "Filter Duotone", className: "roycss-filter-duotone", category: "filter", displayType: "box" },
  { name: "Filter Emboss", className: "roycss-filter-emboss", category: "filter", displayType: "box" },
  { name: "Filter Glitch", className: "roycss-filter-glitch", category: "filter", displayType: "box" },
  { name: "Filter Grayscale Hover", className: "roycss-filter-grayscale-hover", category: "filter", displayType: "box" },
  { name: "Filter Halftone", className: "roycss-filter-halftone", category: "filter", displayType: "box" },
  { name: "Filter Hue Rotate", className: "roycss-filter-hue-rotate", category: "filter", displayType: "box" },
  { name: "Filter Invert", className: "roycss-filter-invert", category: "filter", displayType: "box" },
  { name: "Filter Saturate", className: "roycss-filter-saturate", category: "filter", displayType: "box" },
  { name: "Filter Sepia", className: "roycss-filter-sepia", category: "filter", displayType: "box" },
  { name: "Filter Vintage", className: "roycss-filter-vintage", category: "filter", displayType: "box" },
  { name: "Form Checkbox Custom", className: "roycss-form-checkbox-custom", category: "forms", displayType: "box" },
  { name: "Form Error Shake", className: "roycss-form-error-shake", category: "forms", displayType: "box" },
  { name: "Form Focus Glow", className: "roycss-form-focus-glow", category: "forms", displayType: "box" },
  { name: "Form Label Float", className: "roycss-form-label-float", category: "forms", displayType: "box" },
  { name: "Form Placeholder Shimmer", className: "roycss-form-placeholder-shimmer", category: "forms", displayType: "box" },
  { name: "Form Radio Custom", className: "roycss-form-radio-custom", category: "forms", displayType: "box" },
  { name: "Form Search Expand", className: "roycss-form-search-expand", category: "forms", displayType: "box" },
  { name: "Form Success Check", className: "roycss-form-success-check", category: "forms", displayType: "box" },
  { name: "Form Toggle Switch", className: "roycss-form-toggle-switch", category: "forms", displayType: "box" },
  { name: "Form Underline Draw", className: "roycss-form-underline-draw", category: "forms", displayType: "box" },
  { name: "Glass Acrylic", className: "roycss-glass-acrylic", category: "glass", displayType: "card" },
  { name: "Glass Border Glow", className: "roycss-glass-border-glow", category: "glass", displayType: "card" },
  { name: "Glass Claymorphism", className: "roycss-glass-claymorphism", category: "glass", displayType: "card" },
  { name: "Glass Depth Layer", className: "roycss-glass-depth-layer", category: "glass", displayType: "card" },
  { name: "Glass Frosted", className: "roycss-glass-frosted", category: "glass", displayType: "card" },
  { name: "Glass Frosted Dark", className: "roycss-glass-frosted-dark", category: "glass", displayType: "card" },
  { name: "Glass Liquid", className: "roycss-glass-liquid", category: "glass", displayType: "card" },
  { name: "Glass Neumorphism", className: "roycss-glass-neumorphism", category: "glass", displayType: "card" },
  { name: "Glass Neumorphism Inset", className: "roycss-glass-neumorphism-inset", category: "glass", displayType: "card" },
  { name: "Glass Noise Overlay", className: "roycss-glass-noise-overlay", category: "glass", displayType: "card" },
  { name: "Glass Prism", className: "roycss-glass-prism", category: "glass", displayType: "card" },
  { name: "Glass Reflection", className: "roycss-glass-reflection", category: "glass", displayType: "card" },
  { name: "Glass Transparent Blur", className: "roycss-glass-transparent-blur", category: "glass", displayType: "card" },
  { name: "Glass Vibrant", className: "roycss-glass-vibrant", category: "glass", displayType: "card" },
  { name: "Hover Border Draw", className: "roycss-hover-border-draw", category: "hover", displayType: "box" },
  { name: "Hover Color Shift", className: "roycss-hover-color-shift", category: "hover", displayType: "box" },
  { name: "Hover Depth", className: "roycss-hover-depth", category: "hover", displayType: "box" },
  { name: "Hover Drop Shadow", className: "roycss-hover-drop-shadow", category: "hover", displayType: "box" },
  { name: "Hover Flip", className: "roycss-hover-flip", category: "hover", displayType: "box" },
  { name: "Hover Glow Border", className: "roycss-hover-glow-border", category: "hover", displayType: "box" },
  { name: "Hover Neon Flicker", className: "roycss-hover-neon-flicker", category: "hover", displayType: "box" },
  { name: "Hover Opacity", className: "roycss-hover-opacity", category: "hover", displayType: "box" },
  { name: "Hover Press", className: "roycss-hover-press", category: "hover", displayType: "box" },
  { name: "Hover Push Up", className: "roycss-hover-push-up", category: "hover", displayType: "box" },
  { name: "Hover Rotate", className: "roycss-hover-rotate", category: "hover", displayType: "box" },
  { name: "Hover Scale", className: "roycss-hover-scale", category: "hover", displayType: "box" },
  { name: "Hover Scale Down", className: "roycss-hover-scale-down", category: "hover", displayType: "box" },
  { name: "Hover Shadow Grow", className: "roycss-hover-shadow-grow", category: "hover", displayType: "box" },
  { name: "Hover Skew", className: "roycss-hover-skew", category: "hover", displayType: "box" },
  { name: "Hover Tilt Rotate", className: "roycss-hover-tilt-rotate", category: "hover", displayType: "box" },
  { name: "Hover Underline Slide", className: "roycss-hover-underline-slide", category: "hover", displayType: "box" },
  { name: "Hover Fade Overlay", className: "roycss-hover-fade-overlay", category: "image-hover", displayType: "image" },
  { name: "Hover Grayscale To Color", className: "roycss-hover-grayscale-to-color", category: "image-hover", displayType: "image" },
  { name: "Hover Hue Rotate", className: "roycss-hover-hue-rotate", category: "image-hover", displayType: "image" },
  { name: "Hover Overlay Reveal", className: "roycss-hover-overlay-reveal", category: "image-hover", displayType: "image" },
  { name: "Hover Slide Overlay", className: "roycss-hover-slide-overlay", category: "image-hover", displayType: "image" },
  { name: "Hover Slide Right", className: "roycss-hover-slide-right", category: "image-hover", displayType: "image" },
  { name: "Hover Zoom Blur", className: "roycss-hover-zoom-blur", category: "image-hover", displayType: "image" },
  { name: "Loader Bars", className: "roycss-loader-bars", category: "loading", displayType: "loader" },
  { name: "Loader Bouncing Grid", className: "roycss-loader-bouncing-grid", category: "loading", displayType: "loader" },
  { name: "Loader Chasing Dots", className: "roycss-loader-chasing-dots", category: "loading", displayType: "loader" },
  { name: "Loader Circle Fade", className: "roycss-loader-circle-fade", category: "loading", displayType: "loader" },
  { name: "Loader Circle Notch", className: "roycss-loader-circle-notch", category: "loading", displayType: "loader" },
  { name: "Loader Clock", className: "roycss-loader-clock", category: "loading", displayType: "loader" },
  { name: "Loader Cube", className: "roycss-loader-cube", category: "loading", displayType: "loader" },
  { name: "Loader Dots", className: "roycss-loader-dots", category: "loading", displayType: "loader" },
  { name: "Loader Dual Ring", className: "roycss-loader-dual-ring", category: "loading", displayType: "loader" },
  { name: "Loader Fading Dots", className: "roycss-loader-fading-dots", category: "loading", displayType: "loader" },
  { name: "Loader Folding Cube", className: "roycss-loader-folding-cube", category: "loading", displayType: "loader" },
  { name: "Loader Grid", className: "roycss-loader-grid", category: "loading", displayType: "loader" },
  { name: "Loader Indeterminate", className: "roycss-loader-indeterminate", category: "loading", displayType: "loader" },
  { name: "Loader Line Scale", className: "roycss-loader-line-scale", category: "loading", displayType: "loader" },
  { name: "Loader Orbit", className: "roycss-loader-orbit", category: "loading", displayType: "loader" },
  { name: "Loader Pacman", className: "roycss-loader-pacman", category: "loading", displayType: "loader" },
  { name: "Loader Progress Bar", className: "roycss-loader-progress-bar", category: "loading", displayType: "loader" },
  { name: "Loader Pulse Ring", className: "roycss-loader-pulse-ring", category: "loading", displayType: "loader" },
  { name: "Loader Ripple", className: "roycss-loader-ripple", category: "loading", displayType: "loader" },
  { name: "Loader Skeleton", className: "roycss-loader-skeleton", category: "loading", displayType: "loader" },
  { name: "Loader Spinner", className: "roycss-loader-spinner", category: "loading", displayType: "loader" },
  { name: "Loader Square Spin", className: "roycss-loader-square-spin", category: "loading", displayType: "loader" },
  { name: "Loader Three Bounce", className: "roycss-loader-three-bounce", category: "loading", displayType: "loader" },
  { name: "Loader Typing", className: "roycss-loader-typing", category: "loading", displayType: "loader" },
  { name: "Loader Whale", className: "roycss-loader-whale", category: "loading", displayType: "loader" },
  { name: "Mask Composite Reveal", className: "roycss-mask-composite-reveal", category: "mask", displayType: "bg" },
  { name: "Mask Linear Wipe", className: "roycss-mask-linear-wipe", category: "mask", displayType: "bg" },
  { name: "Mask Radial Reveal", className: "roycss-mask-radial-reveal", category: "mask", displayType: "bg" },
  { name: "Micro Accordion Expand", className: "roycss-micro-accordion-expand", category: "micro-interaction", displayType: "box" },
  { name: "Micro Badge Bounce", className: "roycss-micro-badge-bounce", category: "micro-interaction", displayType: "box" },
  { name: "Micro Checkbox Check", className: "roycss-micro-checkbox-check", category: "micro-interaction", displayType: "box" },
  { name: "Micro Dropdown Reveal", className: "roycss-micro-dropdown-reveal", category: "micro-interaction", displayType: "box" },
  { name: "Micro Fab Expand", className: "roycss-micro-fab-expand", category: "micro-interaction", displayType: "box" },
  { name: "Micro Modal Scale", className: "roycss-micro-modal-scale", category: "micro-interaction", displayType: "box" },
  { name: "Micro Progress Fill", className: "roycss-micro-progress-fill", category: "micro-interaction", displayType: "box" },
  { name: "Micro Radio Select", className: "roycss-micro-radio-select", category: "micro-interaction", displayType: "box" },
  { name: "Micro Tab Indicator", className: "roycss-micro-tab-indicator", category: "micro-interaction", displayType: "box" },
  { name: "Micro Toast Slide", className: "roycss-micro-toast-slide", category: "micro-interaction", displayType: "box" },
  { name: "Micro Toggle Switch", className: "roycss-micro-toggle-switch", category: "micro-interaction", displayType: "box" },
  { name: "Micro Tooltip Appear", className: "roycss-micro-tooltip-appear", category: "micro-interaction", displayType: "box" },
  { name: "Ascii Rain", className: "roycss-ascii-rain", category: "misc", displayType: "box" },
  { name: "Blueprint", className: "roycss-blueprint", category: "misc", displayType: "box" },
  { name: "Bounce Out", className: "roycss-bounce-out", category: "misc", displayType: "box" },
  { name: "Double Conic Spinner", className: "roycss-double-conic-spinner", category: "misc", displayType: "loader" },
  { name: "Drawer Slide", className: "roycss-drawer-slide", category: "misc", displayType: "box" },
  { name: "Film Grain", className: "roycss-film-grain", category: "misc", displayType: "box" },
  { name: "Fold", className: "roycss-fold", category: "misc", displayType: "box" },
  { name: "Infinity Loop", className: "roycss-infinity-loop", category: "misc", displayType: "box" },
  { name: "Liquid Drop", className: "roycss-liquid-drop", category: "misc", displayType: "box" },
  { name: "Liquid Metal", className: "roycss-liquid-metal", category: "misc", displayType: "box" },
  { name: "Misc Bubbles", className: "roycss-misc-bubbles", category: "misc", displayType: "bg" },
  { name: "Misc Confetti", className: "roycss-misc-confetti", category: "misc", displayType: "bg" },
  { name: "Misc Fireflies", className: "roycss-misc-fireflies", category: "misc", displayType: "bg" },
  { name: "Misc Fireworks", className: "roycss-misc-fireworks", category: "misc", displayType: "bg" },
  { name: "Misc Hologram", className: "roycss-misc-hologram", category: "misc", displayType: "bg" },
  { name: "Misc Pulse Ring Expand", className: "roycss-misc-pulse-ring-expand", category: "misc", displayType: "bg" },
  { name: "Misc Rain", className: "roycss-misc-rain", category: "misc", displayType: "bg" },
  { name: "Misc Ripple Click", className: "roycss-misc-ripple-click", category: "misc", displayType: "bg" },
  { name: "Misc Scan Line", className: "roycss-misc-scan-line", category: "misc", displayType: "bg" },
  { name: "Misc Shimmer Overlay", className: "roycss-misc-shimmer-overlay", category: "misc", displayType: "bg" },
  { name: "Misc Snow", className: "roycss-misc-snow", category: "misc", displayType: "bg" },
  { name: "Misc Sparkles", className: "roycss-misc-sparkles", category: "misc", displayType: "bg" },
  { name: "Misc Typewriter", className: "roycss-misc-typewriter", category: "misc", displayType: "bg" },
  { name: "Misc Vhs Effect", className: "roycss-misc-vhs-effect", category: "misc", displayType: "bg" },
  { name: "Misc Wave", className: "roycss-misc-wave", category: "misc", displayType: "bg" },
  { name: "Natural Drop", className: "roycss-natural-drop", category: "misc", displayType: "box" },
  { name: "Pendulum Swing Spring", className: "roycss-pendulum-swing-spring", category: "misc", displayType: "box" },
  { name: "Pixel Art", className: "roycss-pixel-art", category: "misc", displayType: "box" },
  { name: "Rubber Snap Back", className: "roycss-rubber-snap-back", category: "misc", displayType: "box" },
  { name: "Scrollbar Gutter Stable", className: "roycss-scrollbar-gutter-stable", category: "misc", displayType: "box" },
  { name: "Color Mix Gradient", className: "roycss-color-mix-gradient", category: "modern-css", displayType: "box" },
  { name: "Color Mix Mesh", className: "roycss-color-mix-mesh", category: "modern-css", displayType: "box" },
  { name: "Container Query Card", className: "roycss-container-query-card", category: "modern-css", displayType: "box" },
  { name: "Starting Style Drop In", className: "roycss-starting-style-drop-in", category: "modern-css", displayType: "box" },
  { name: "Starting Style Fade", className: "roycss-starting-style-fade", category: "modern-css", displayType: "box" },
  { name: "View Timeline Reveal", className: "roycss-view-timeline-reveal", category: "modern-css", displayType: "box" },
  { name: "View Transition Snapshot", className: "roycss-view-transition-snapshot", category: "modern-css", displayType: "box" },
  { name: "Houdini Animated Gradient", className: "roycss-ng-houdini-gradient", category: "next-gen-css", displayType: "box" },
  { name: "Houdini Hue Cycle", className: "roycss-ng-houdini-hue", category: "next-gen-css", displayType: "box" },
  { name: "Houdini Border Rainbow", className: "roycss-ng-border-rainbow", category: "next-gen-css", displayType: "box" },
  { name: "Houdini Progress Ring", className: "roycss-ng-progress-ring", category: "next-gen-css", displayType: "box" },
  { name: "Houdini Glow Pulse", className: "roycss-ng-glow-pulse", category: "next-gen-css", displayType: "box" },
  { name: "Houdini Gradient Morph", className: "roycss-ng-gradient-morph", category: "next-gen-css", displayType: "box" },
  { name: "Scroll Scale Reveal", className: "roycss-ng-scroll-scale", category: "next-gen-css", displayType: "box" },
  { name: "Scroll Opacity Fade", className: "roycss-ng-scroll-fade", category: "next-gen-css", displayType: "box" },
  { name: "Scroll Rotate In", className: "roycss-ng-scroll-rotate", category: "next-gen-css", displayType: "box" },
  { name: "View Transition Morph Shape", className: "roycss-ng-vt-morph", category: "next-gen-css", displayType: "box" },
  { name: "View Transition Color Swap", className: "roycss-ng-vt-swap", category: "next-gen-css", displayType: "box" },
  { name: "Anchor Tooltip", className: "roycss-ng-anchor-tooltip", category: "next-gen-css", displayType: "box" },
  { name: "Anchor Callout", className: "roycss-ng-anchor-callout", category: "next-gen-css", displayType: "box" },
  { name: "Nesting Hover Card", className: "roycss-ng-nesting-card", category: "next-gen-css", displayType: "box" },
  { name: "Nesting Interactive Button", className: "roycss-ng-nesting-btn", category: "next-gen-css", displayType: "box" },
  { name: "Has Focus Glow", className: "roycss-ng-has-focus", category: "next-gen-css", displayType: "box" },
  { name: "Has Checked Toggle", className: "roycss-ng-has-checked", category: "next-gen-css", displayType: "box" },
  { name: "Has Empty State", className: "roycss-ng-has-empty", category: "next-gen-css", displayType: "box" },
  { name: "Container Query Stack", className: "roycss-ng-cq-stack", category: "next-gen-css", displayType: "box" },
  { name: "Container Query Adaptive", className: "roycss-ng-cq-adaptive", category: "next-gen-css", displayType: "box" },
  { name: "Color Mix Blend", className: "roycss-ng-color-mix-blend", category: "next-gen-css", displayType: "box" },
  { name: "Color Mix Opacity", className: "roycss-ng-color-mix-opacity", category: "next-gen-css", displayType: "box" },
  { name: "Conic Gradient Pie", className: "roycss-ng-conic-pie", category: "next-gen-css", displayType: "box" },
  { name: "Repeating Gradient Motion", className: "roycss-ng-repeating-motion", category: "next-gen-css", displayType: "box" },
  { name: "Text Wrap Balance", className: "roycss-ng-text-balance", category: "next-gen-css", displayType: "box" },
  { name: "Discrete Transition", className: "roycss-ng-discrete-transition", category: "next-gen-css", displayType: "box" },

  { name: "Deep Sea", className: "roycss-deep-sea", category: "nature", displayType: "box" },
  { name: "Frozen Ice", className: "roycss-frozen-ice", category: "nature", displayType: "box" },
  { name: "Gold Leaf", className: "roycss-gold-leaf", category: "nature", displayType: "box" },
  { name: "Heat Haze", className: "roycss-heat-haze", category: "nature", displayType: "box" },
  { name: "Molten Lava", className: "roycss-molten-lava", category: "nature", displayType: "box" },
  { name: "Northern Lights", className: "roycss-northern-lights", category: "nature", displayType: "box" },
  { name: "Oil Slick", className: "roycss-oil-slick", category: "nature", displayType: "box" },
  { name: "Painting Oil", className: "roycss-painting-oil", category: "nature", displayType: "box" },
  { name: "Pencil Sketch", className: "roycss-pencil-sketch", category: "nature", displayType: "box" },
  { name: "Soap Bubble", className: "roycss-soap-bubble", category: "nature", displayType: "box" },
  { name: "Stained Glass", className: "roycss-stained-glass", category: "nature", displayType: "box" },
  { name: "Topographic", className: "roycss-topographic", category: "nature", displayType: "box" },
  { name: "Velvet Fabric", className: "roycss-velvet-fabric", category: "nature", displayType: "box" },
  { name: "Water Ripple", className: "roycss-water-ripple", category: "nature", displayType: "box" },
  { name: "Watercolor", className: "roycss-watercolor", category: "nature", displayType: "box" },
  { name: "Nav Accordion", className: "roycss-nav-accordion", category: "navigation", displayType: "box" },
  { name: "Nav Breadcrumb", className: "roycss-nav-breadcrumb", category: "navigation", displayType: "box" },
  { name: "Nav Dropdown", className: "roycss-nav-dropdown", category: "navigation", displayType: "box" },
  { name: "Nav Menu Fade", className: "roycss-nav-menu-fade", category: "navigation", displayType: "box" },
  { name: "Nav Menu Scale", className: "roycss-nav-menu-scale", category: "navigation", displayType: "box" },
  { name: "Nav Menu Slide", className: "roycss-nav-menu-slide", category: "navigation", displayType: "box" },
  { name: "Nav Pagination", className: "roycss-nav-pagination", category: "navigation", displayType: "box" },
  { name: "Nav Progress Indicator", className: "roycss-nav-progress-indicator", category: "navigation", displayType: "box" },
  { name: "Nav Stepper", className: "roycss-nav-stepper", category: "navigation", displayType: "box" },
  { name: "Nav Tabs Underline", className: "roycss-nav-tabs-underline", category: "navigation", displayType: "box" },
  { name: "Offset Path Draw", className: "roycss-offset-path-draw", category: "offset-path", displayType: "box" },
  { name: "Offset Path Orbit", className: "roycss-offset-path-orbit", category: "offset-path", displayType: "box" },
  { name: "Offset Path Wave", className: "roycss-offset-path-wave", category: "offset-path", displayType: "box" },
  { name: "Page Circle Reveal", className: "roycss-page-circle-reveal", category: "page-transition", displayType: "box" },
  { name: "Page Cube", className: "roycss-page-cube", category: "page-transition", displayType: "box" },
  { name: "Page Curtain", className: "roycss-page-curtain", category: "page-transition", displayType: "box" },
  { name: "Page Dissolve", className: "roycss-page-dissolve", category: "page-transition", displayType: "box" },
  { name: "Page Fade", className: "roycss-page-fade", category: "page-transition", displayType: "box" },
  { name: "Page Flip", className: "roycss-page-flip", category: "page-transition", displayType: "box" },
  { name: "Page Liquid", className: "roycss-page-liquid", category: "page-transition", displayType: "box" },
  { name: "Page Mask Reveal", className: "roycss-page-mask-reveal", category: "page-transition", displayType: "box" },
  { name: "Page Shutter", className: "roycss-page-shutter", category: "page-transition", displayType: "box" },
  { name: "Page Slide Left", className: "roycss-page-slide-left", category: "page-transition", displayType: "box" },
  { name: "Page Slide Up", className: "roycss-page-slide-up", category: "page-transition", displayType: "box" },
  { name: "Page Zoom", className: "roycss-page-zoom", category: "page-transition", displayType: "box" },
  { name: "Particles Bubbles", className: "roycss-particles-bubbles", category: "particles", displayType: "bg" },
  { name: "Particles Confetti Burst", className: "roycss-particles-confetti-burst", category: "particles", displayType: "bg" },
  { name: "Particles Dust", className: "roycss-particles-dust", category: "particles", displayType: "bg" },
  { name: "Particles Fire", className: "roycss-particles-fire", category: "particles", displayType: "bg" },
  { name: "Particles Fireflies", className: "roycss-particles-fireflies", category: "particles", displayType: "bg" },
  { name: "Particles Floating Dots", className: "roycss-particles-floating-dots", category: "particles", displayType: "bg" },
  { name: "Particles Orbiting", className: "roycss-particles-orbiting", category: "particles", displayType: "bg" },
  { name: "Particles Rain", className: "roycss-particles-rain", category: "particles", displayType: "bg" },
  { name: "Particles Smoke", className: "roycss-particles-smoke", category: "particles", displayType: "bg" },
  { name: "Particles Snow Fall", className: "roycss-particles-snow-fall", category: "particles", displayType: "bg" },
  { name: "Particles Sparks", className: "roycss-particles-sparks", category: "particles", displayType: "bg" },
  { name: "Particles Stars Twinkle", className: "roycss-particles-stars-twinkle", category: "particles", displayType: "bg" },
  { name: "Property Angle Rotate", className: "roycss-property-angle-rotate", category: "property", displayType: "box" },
  { name: "Property Color Shift", className: "roycss-property-color-shift", category: "property", displayType: "box" },
  { name: "Property Conic Loader", className: "roycss-property-conic-loader", category: "property", displayType: "box" },
  { name: "Property Gradient Flow", className: "roycss-property-gradient-flow", category: "property", displayType: "box" },
  { name: "Property Hue Cycle", className: "roycss-property-hue-cycle", category: "property", displayType: "box" },
  { name: "Property Progress Bar", className: "roycss-property-progress-bar", category: "property", displayType: "box" },
  { name: "Property Shadow Breathe", className: "roycss-property-shadow-breathe", category: "property", displayType: "box" },
  { name: "Scroll Driven Blur", className: "roycss-scroll-driven-blur", category: "scroll", displayType: "box" },
  { name: "Scroll Driven Color", className: "roycss-scroll-driven-color", category: "scroll", displayType: "box" },
  { name: "Scroll Driven Fade", className: "roycss-scroll-driven-fade", category: "scroll", displayType: "box" },
  { name: "Scroll Driven Progress Ring", className: "roycss-scroll-driven-progress-ring", category: "scroll", displayType: "box" },
  { name: "Scroll Driven Rotate", className: "roycss-scroll-driven-rotate", category: "scroll", displayType: "box" },
  { name: "Scroll Driven Scale", className: "roycss-scroll-driven-scale", category: "scroll", displayType: "box" },
  { name: "Scroll Driven Sticky", className: "roycss-scroll-driven-sticky", category: "scroll", displayType: "box" },
  { name: "Scroll Driven Translate", className: "roycss-scroll-driven-translate", category: "scroll", displayType: "box" },
  { name: "Scroll Fade Out", className: "roycss-scroll-fade-out", category: "scroll", displayType: "box" },
  { name: "Scroll Horizontal", className: "roycss-scroll-horizontal", category: "scroll", displayType: "box" },
  { name: "Scroll Indicator", className: "roycss-scroll-indicator", category: "scroll", displayType: "box" },
  { name: "Scroll Parallax Slow", className: "roycss-scroll-parallax-slow", category: "scroll", displayType: "box" },
  { name: "Scroll Progress Bar", className: "roycss-scroll-progress-bar", category: "scroll", displayType: "box" },
  { name: "Scroll Reveal Left", className: "roycss-scroll-reveal-left", category: "scroll", displayType: "box" },
  { name: "Scroll Reveal Right", className: "roycss-scroll-reveal-right", category: "scroll", displayType: "box" },
  { name: "Scroll Reveal Rotate", className: "roycss-scroll-reveal-rotate", category: "scroll", displayType: "box" },
  { name: "Scroll Reveal Scale", className: "roycss-scroll-reveal-scale", category: "scroll", displayType: "box" },
  { name: "Scroll Reveal Up", className: "roycss-scroll-reveal-up", category: "scroll", displayType: "box" },
  { name: "Scroll Sticky Header", className: "roycss-scroll-sticky-header", category: "scroll", displayType: "box" },
  { name: "Scroll Timeline Spin", className: "roycss-scroll-timeline-spin", category: "scroll", displayType: "box" },
  { name: "Scroll Zoom In", className: "roycss-scroll-zoom-in", category: "scroll", displayType: "box" },
  { name: "Anchor Tooltip", className: "roycss-anchor-tooltip", category: "specialized", displayType: "box" },
  { name: "Auto Height Expand", className: "roycss-auto-height-expand", category: "specialized", displayType: "box" },
  { name: "Backdrop Multi Filter", className: "roycss-backdrop-multi-filter", category: "specialized", displayType: "box" },
  { name: "Balanced Text", className: "roycss-balanced-text", category: "specialized", displayType: "box" },
  { name: "Blink", className: "roycss-blink", category: "specialized", displayType: "box" },
  { name: "Book Open", className: "roycss-book-open", category: "specialized", displayType: "box" },
  { name: "Conic Gradient Clock", className: "roycss-conic-gradient-clock", category: "specialized", displayType: "box" },
  { name: "Depth Shadow", className: "roycss-depth-shadow", category: "specialized", displayType: "box" },
  { name: "Dissolve", className: "roycss-dissolve", category: "specialized", displayType: "box" },
  { name: "Door Open", className: "roycss-door-open", category: "specialized", displayType: "box" },
  { name: "Flash", className: "roycss-flash", category: "specialized", displayType: "box" },
  { name: "Has Parent Highlight", className: "roycss-has-parent-highlight", category: "specialized", displayType: "box" },
  { name: "Interpolate Size Accordion", className: "roycss-interpolate-size-accordion", category: "specialized", displayType: "box" },
  { name: "Light Dark Auto", className: "roycss-light-dark-auto", category: "specialized", displayType: "box" },
  { name: "Neon Sign", className: "roycss-neon-sign", category: "specialized", displayType: "box" },
  { name: "Prism Rainbow", className: "roycss-prism-rainbow", category: "specialized", displayType: "box" },
  { name: "Relative Color Hover", className: "roycss-relative-color-hover", category: "specialized", displayType: "box" },
  { name: "Relative Color Tint", className: "roycss-relative-color-tint", category: "specialized", displayType: "box" },
  { name: "Spiral Galaxy", className: "roycss-spiral-galaxy", category: "specialized", displayType: "box" },
  { name: "Vhs Glitch", className: "roycss-vhs-glitch", category: "specialized", displayType: "box" },
  { name: "Vintage Tv", className: "roycss-vintage-tv", category: "specialized", displayType: "box" },
  { name: "SVG Displacement Wave", className: "roycss-svg-displacement-wave", category: "svg", displayType: "icon" },
  { name: "SVG Gooey Merge", className: "roycss-svg-gooey-merge", category: "svg", displayType: "icon" },
  { name: "SVG Turbulence Distort", className: "roycss-svg-turbulence-distort", category: "svg", displayType: "icon" },
  { name: "Text 3D Cinema", className: "roycss-text-3d-cinema", category: "text", displayType: "text" },
  { name: "Text 3D Shadow", className: "roycss-text-3d-shadow", category: "text", displayType: "text" },
  { name: "Text Blur Reveal", className: "roycss-text-blur-reveal", category: "text", displayType: "text" },
  { name: "Text Bounce Letters", className: "roycss-text-bounce-letters", category: "text", displayType: "text" },
  { name: "Text Chrome", className: "roycss-text-chrome", category: "text", displayType: "text" },
  { name: "Text Emboss", className: "roycss-text-emboss", category: "text", displayType: "text" },
  { name: "Text Fire", className: "roycss-text-fire", category: "text", displayType: "text" },
  { name: "Text Fire Flame", className: "roycss-text-fire-flame", category: "text", displayType: "text" },
  { name: "Text Flip", className: "roycss-text-flip", category: "text", displayType: "text" },
  { name: "Text Glitch", className: "roycss-text-glitch", category: "text", displayType: "text" },
  { name: "Text Gradient", className: "roycss-text-gradient", category: "text", displayType: "text" },
  { name: "Text Gradient Shift", className: "roycss-text-gradient-shift", category: "text", displayType: "text" },
  { name: "Text Highlight Marker", className: "roycss-text-highlight-marker", category: "text", displayType: "text" },
  { name: "Text Holographic", className: "roycss-text-holographic", category: "text", displayType: "text" },
  { name: "Text Mirror", className: "roycss-text-mirror", category: "text", displayType: "text" },
  { name: "Text Neon Glow", className: "roycss-text-neon-glow", category: "text", displayType: "text" },
  { name: "Text Neon Sign", className: "roycss-text-neon-sign", category: "text", displayType: "text" },
  { name: "Text Outline Offset", className: "roycss-text-outline-offset", category: "text", displayType: "text" },
  { name: "Text Rainbow", className: "roycss-text-rainbow", category: "text", displayType: "text" },
  { name: "Text Reflection", className: "roycss-text-reflection", category: "text", displayType: "text" },
  { name: "Text Shadow Long", className: "roycss-text-shadow-long", category: "text", displayType: "text" },
  { name: "Text Shadow Soft", className: "roycss-text-shadow-soft", category: "text", displayType: "text" },
  { name: "Text Shimmer", className: "roycss-text-shimmer", category: "text", displayType: "text" },
  { name: "Text Skew", className: "roycss-text-skew", category: "text", displayType: "text" },
  { name: "Text Stretch", className: "roycss-text-stretch", category: "text", displayType: "text" },
  { name: "Text Stroke", className: "roycss-text-stroke", category: "text", displayType: "text" },
  { name: "Text Typing Cursor", className: "roycss-text-typing-cursor", category: "text", displayType: "text" },
  { name: "Text Underline Draw", className: "roycss-text-underline-draw", category: "text", displayType: "text" },
  { name: "Text Water", className: "roycss-text-water", category: "text", displayType: "text" },
  { name: "Text Wave", className: "roycss-text-wave", category: "text", displayType: "text" },
  { name: "Flip X", className: "roycss-flip-x", category: "transform", displayType: "box" },
  { name: "Flip Y", className: "roycss-flip-y", category: "transform", displayType: "box" },
  { name: "Rotate X", className: "roycss-rotate-x", category: "transform", displayType: "box" },
  { name: "Rotate Y", className: "roycss-rotate-y", category: "transform", displayType: "box" },
  { name: "Scale Compress", className: "roycss-scale-compress", category: "transform", displayType: "box" },
  { name: "Scale Expand", className: "roycss-scale-expand", category: "transform", displayType: "box" },
  { name: "Scale Grow", className: "roycss-scale-grow", category: "transform", displayType: "box" },
  { name: "Scale Shrink", className: "roycss-scale-shrink", category: "transform", displayType: "box" },
  { name: "Transform Origin Spin", className: "roycss-transform-origin-spin", category: "transform", displayType: "box" },
  { name: "Fortune Teller", className: "roycss-fortune-teller", category: "unique", displayType: "box" },
  { name: "Kaleidoscope", className: "roycss-kaleidoscope", category: "unique", displayType: "box" },
  { name: "Morph Blob", className: "roycss-morph-blob", category: "unique", displayType: "box" },
  { name: "Origami Fold", className: "roycss-origami-fold", category: "unique", displayType: "box" },
  { name: "Paper Flip", className: "roycss-paper-flip", category: "unique", displayType: "box" },
  { name: "Roulette Spin", className: "roycss-roulette-spin", category: "unique", displayType: "box" },
  { name: "Slot Machine", className: "roycss-slot-machine", category: "unique", displayType: "box" },
  { name: "Visual Aurora Border", className: "roycss-visual-aurora-border", category: "visual-effects", displayType: "bg" },
  { name: "Visual Backdrop Blur Heavy", className: "roycss-visual-backdrop-blur-heavy", category: "visual-effects", displayType: "bg" },
  { name: "Visual Blend Mode Overlay", className: "roycss-visual-blend-mode-overlay", category: "visual-effects", displayType: "bg" },
  { name: "Visual Border Beam", className: "roycss-visual-border-beam", category: "visual-effects", displayType: "bg" },
  { name: "Visual Chrome", className: "roycss-visual-chrome", category: "visual-effects", displayType: "bg" },
  { name: "Visual Color Shift", className: "roycss-visual-color-shift", category: "visual-effects", displayType: "bg" },
  { name: "Visual Foil", className: "roycss-visual-foil", category: "visual-effects", displayType: "bg" },
  { name: "Visual Frost Blur", className: "roycss-visual-frost-blur", category: "visual-effects", displayType: "bg" },
  { name: "Visual Glass Reflection", className: "roycss-visual-glass-reflection", category: "visual-effects", displayType: "bg" },
  { name: "Visual Glitch Distort", className: "roycss-visual-glitch-distort", category: "visual-effects", displayType: "bg" },
  { name: "Visual Gradient Mesh", className: "roycss-visual-gradient-mesh", category: "visual-effects", displayType: "bg" },
  { name: "Visual Gradient Text Animated", className: "roycss-visual-gradient-text-animated", category: "visual-effects", displayType: "bg" },
  { name: "Visual Holographic", className: "roycss-visual-holographic", category: "visual-effects", displayType: "bg" },
  { name: "Visual Hue Rotate Loop", className: "roycss-visual-hue-rotate-loop", category: "visual-effects", displayType: "bg" },
  { name: "Visual Image Distortion", className: "roycss-visual-image-distortion", category: "visual-effects", displayType: "bg" },
  { name: "Visual Inner Glow", className: "roycss-visual-inner-glow", category: "visual-effects", displayType: "bg" },
  { name: "Visual Iridescent", className: "roycss-visual-iridescent", category: "visual-effects", displayType: "bg" },
  { name: "Visual Liquid Fill", className: "roycss-visual-liquid-fill", category: "visual-effects", displayType: "bg" },
  { name: "Visual Mask Fade", className: "roycss-visual-mask-fade", category: "visual-effects", displayType: "bg" },
  { name: "Visual Metallic", className: "roycss-visual-metallic", category: "visual-effects", displayType: "bg" },
  { name: "Visual Neon Pulse", className: "roycss-visual-neon-pulse", category: "visual-effects", displayType: "bg" },
  { name: "Visual Noise Overlay", className: "roycss-visual-noise-overlay", category: "visual-effects", displayType: "bg" },
  { name: "Visual Pixelate", className: "roycss-visual-pixelate", category: "visual-effects", displayType: "bg" },
  { name: "Visual Prism", className: "roycss-visual-prism", category: "visual-effects", displayType: "bg" },
  { name: "Visual Saturation Pulse", className: "roycss-visual-saturation-pulse", category: "visual-effects", displayType: "bg" },
  { name: "Visual Shadow Pulse", className: "roycss-visual-shadow-pulse", category: "visual-effects", displayType: "bg" },
  { name: "Visual Shimmer Sweep", className: "roycss-visual-shimmer-sweep", category: "visual-effects", displayType: "bg" },
  { name: "Visual Spotlight Follow", className: "roycss-visual-spotlight-follow", category: "visual-effects", displayType: "bg" },
];

// Empty secondary array (kept for backward compat with merge logic)
export const effectsIndex: FerrumEffectIndex[] = [];

export const categoryCounts: Record<string, number> = {
  "3d": 10,
  "attention": 19,
  "background": 25,
  "blend-modes": 2,
  "borders": 15,
  "buttons": 25,
  "cards": 24,
  "clip-path": 2,
  "cursor": 12,
  "design-presets": 37,
  "entrance": 36,
  "exit": 17,
  "filter": 15,
  "forms": 10,
  "glass": 14,
  "hover": 17,
  "image-hover": 7,
  "loading": 25,
  "mask": 3,
  "micro-interaction": 12,
  "misc": 30,
  "modern-css": 7,
  "next-gen-css": 26,
  "nature": 15,
  "navigation": 10,
  "offset-path": 3,
  "page-transition": 12,
  "particles": 12,
  "property": 7,
  "scroll": 21,
  "specialized": 21,
  "svg": 3,
  "text": 30,
  "transform": 9,
  "unique": 7,
  "visual-effects": 28,
};