// ─── Glass Worklet ──────────────────────────
// Glassmorphism effect with noise-like texture (pseudo-noise via small semi-transparent rects),
// subtle border highlight, responds to color/blur/saturation variables.

import type { PaintWorkletDescriptor } from "../types";

/**
 * Descriptor for the ferrum-glass paint worklet.
 */
export const glassDescriptor: PaintWorkletDescriptor = {
  name: "ferrum-glass" as const,
  inputProperties: [
    "--ferrum-glass-blur",
    "--ferrum-glass-saturation",
    "--ferrum-glass-opacity",
    "--ferrum-glass-border-opacity",
    "--ferrum-glass-color",
  ] as const,
  cssClass: ".fr-glass" as const,
  fallbackCSS: `/* fallback: semi-transparent overlay with backdrop-filter */
.fr-glass {
  --ferrum-glass-blur: 16px;
  --ferrum-glass-saturation: 1.2;
  --ferrum-glass-opacity: 0.12;
  --ferrum-glass-border-opacity: 0.18;
  --ferrum-glass-color: #ffffff;
  background: rgba(255, 255, 255, calc(var(--ferrum-glass-opacity) * 0.5));
  backdrop-filter: blur(var(--ferrum-glass-blur)) saturate(var(--ferrum-glass-saturation));
  -webkit-backdrop-filter: blur(var(--ferrum-glass-blur)) saturate(var(--ferrum-glass-saturation));
  border: 1px solid rgba(255, 255, 255, var(--ferrum-glass-border-opacity));
}`,
  workletCode: `
    // ferrum-glass worklet — Auto-generated by @ferrum/paint
    // Frosted glass with pseudo-noise texture and border highlight
    registerPaint('ferrum-glass', class {
      static get inputProperties() {
        return [
          '--ferrum-glass-blur',
          '--ferrum-glass-saturation',
          '--ferrum-glass-opacity',
          '--ferrum-glass-border-opacity',
          '--ferrum-glass-color',
        ];
      }

      paint(ctx, geom, properties) {
        const opacity = Math.min(1, Math.max(0, parseFloat(properties.get('--ferrum-glass-opacity')) || 0.12));
        const borderOp = Math.min(1, Math.max(0, parseFloat(properties.get('--ferrum-glass-border-opacity')) || 0.18));
        const color = (properties.get('--ferrum-glass-color')?.toString() || '#ffffff').trim();

        const { width, height } = geom;

        ctx.clearRect(0, 0, width, height);

        // Pseudo-noise texture using multiple small semi-transparent rects
        ctx.save();
        ctx.globalAlpha = opacity * 0.6;
        let seed = 12345;
        const cellSize = 4;
        const cols = Math.ceil(width / cellSize);
        const rows = Math.ceil(height / cellSize);
        for (let row = 0; row < rows; row++) {
          for (let col = 0; col < cols; col++) {
            seed = (seed * 16807 + 0) % 2147483647;
            const v = (seed / 2147483647);
            if (v > 0.5) {
              ctx.globalAlpha = opacity * 0.08 * v;
              ctx.fillStyle = color;
              ctx.fillRect(col * cellSize, row * cellSize, cellSize, cellSize);
            }
          }
        }
        ctx.restore();

        // Tinted overlay
        ctx.save();
        ctx.globalAlpha = opacity;
        ctx.fillStyle = color;
        ctx.fillRect(0, 0, width, height);
        ctx.restore();

        // Top highlight strip (glass reflection)
        ctx.save();
        const hlGrad = ctx.createLinearGradient(0, 0, 0, height * 0.4);
        hlGrad.addColorStop(0, 'rgba(255,255,255,0.18)');
        hlGrad.addColorStop(1, 'rgba(255,255,255,0)');
        ctx.fillStyle = hlGrad;
        ctx.fillRect(0, 0, width, height * 0.4);
        ctx.restore();

        // Subtle border highlight at edges
        ctx.save();
        ctx.globalAlpha = borderOp;
        ctx.strokeStyle = '#ffffff';
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.roundRect(0.5, 0.5, width - 1, height - 1, 8);
        ctx.stroke();
        ctx.restore();
      }
    });
  `,
};