// ─── Glow Worklet ──────────────────────────
// Dynamic glowing orb effect with shadow, supports 'round' and 'rect' shapes.
// Inner highlight for glassmorphism feel.

import type { PaintWorkletDescriptor } from "../types";

/**
 * Descriptor for the ferrum-glow paint worklet.
 */
export const glowDescriptor: PaintWorkletDescriptor = {
  name: "ferrum-glow" as const,
  inputProperties: [
    "--ferrum-color",
    "--ferrum-intensity",
    "--ferrum-blur",
    "--ferrum-shape",
  ] as const,
  cssClass: ".fr-glow" as const,
  fallbackCSS: `/* fallback: radial gradient approximation */
.fr-glow {
  --ferrum-color: #6366f1;
  --ferrum-intensity: 0.6;
  --ferrum-blur: 30;
  --ferrum-shape: round;
  background: radial-gradient(circle at 50% 50%, var(--ferrum-color) 0%, transparent 70%);
}`,
  workletCode: `
    // ferrum-glow worklet — Auto-generated by @ferrum/paint
    // Dynamic glowing orb with shadow, supports round/rect shapes
    registerPaint('ferrum-glow', class {
      static get inputProperties() {
        return [
          '--ferrum-color',
          '--ferrum-intensity',
          '--ferrum-blur',
          '--ferrum-shape',
        ];
      }

      paint(ctx, geom, properties) {
        const color = (properties.get('--ferrum-color')?.toString() || '#6366f1').trim();
        const intensity = Math.min(1, Math.max(0, parseFloat(properties.get('--ferrum-intensity')) || 0.6));
        const blur = Math.max(0, parseFloat(properties.get('--ferrum-blur')) || 30);
        const shape = (properties.get('--ferrum-shape')?.toString() || 'round').trim();

        const { width, height } = geom;
        const cx = width / 2;
        const cy = height / 2;
        const baseRadius = Math.max(1, Math.min(width, height) * 0.4);

        ctx.clearRect(0, 0, width, height);

        // Outer glow layer
        ctx.save();
        ctx.shadowColor = color;
        ctx.shadowBlur = blur * intensity;
        ctx.shadowOffsetX = 0;
        ctx.shadowOffsetY = 0;

        const gradient = ctx.createRadialGradient(cx, cy, 0, cx, cy, baseRadius);
        gradient.addColorStop(0, color);
        gradient.addColorStop(0.5, color);
        gradient.addColorStop(1, 'transparent');

        ctx.fillStyle = gradient;
        ctx.beginPath();

        if (shape === 'rect') {
          const rx = baseRadius * 0.75;
          const ry = baseRadius * 0.55;
          ctx.roundRect(cx - rx, cy - ry, rx * 2, ry * 2, baseRadius * 0.15);
        } else {
          ctx.arc(cx, cy, baseRadius, 0, Math.PI * 2);
        }

        ctx.fill();
        ctx.restore();

        // Inner highlight for glassmorphism feel
        ctx.save();
        ctx.globalAlpha = 0.25 * intensity;
        ctx.fillStyle = '#ffffff';
        const hlRadius = Math.max(1, baseRadius * 0.18);
        ctx.beginPath();
        ctx.arc(cx - baseRadius * 0.2, cy - baseRadius * 0.2, hlRadius, 0, Math.PI * 2);
        ctx.fill();
        ctx.restore();
      }
    });
  `,
};