// ─── Gradient Mesh Worklet ──────────────────────────
// Gradient mesh background with multiple radial gradients at different positions,
// soft blurred color blending, animated feel via angle variable.

import type { PaintWorkletDescriptor } from "../types";

/**
 * Descriptor for the ferrum-gradient-mesh paint worklet.
 */
export const gradientMeshDescriptor: PaintWorkletDescriptor = {
  name: "ferrum-gradient-mesh" as const,
  inputProperties: [
    "--ferrum-mesh-color-1",
    "--ferrum-mesh-color-2",
    "--ferrum-mesh-color-3",
    "--ferrum-mesh-angle",
    "--ferrum-mesh-blur",
  ] as const,
  cssClass: ".fr-gradient-mesh" as const,
  fallbackCSS: `/* fallback: multi-stop radial gradients */
.fr-gradient-mesh {
  --ferrum-mesh-color-1: #6366f1;
  --ferrum-mesh-color-2: #a855f7;
  --ferrum-mesh-color-3: #ec4899;
  --ferrum-mesh-angle: 0;
  --ferrum-mesh-blur: 60;
  background:
    radial-gradient(circle at 20% 30%, var(--ferrum-mesh-color-1) 0%, transparent 50%),
    radial-gradient(circle at 80% 30%, var(--ferrum-mesh-color-2) 0%, transparent 50%),
    radial-gradient(circle at 50% 80%, var(--ferrum-mesh-color-3) 0%, transparent 50%);
}`,
  workletCode: `
    // ferrum-gradient-mesh worklet — Auto-generated by @ferrum/paint
    // Multi-point gradient mesh with soft blending and angle animation
    registerPaint('ferrum-gradient-mesh', class {
      static get inputProperties() {
        return [
          '--ferrum-mesh-color-1',
          '--ferrum-mesh-color-2',
          '--ferrum-mesh-color-3',
          '--ferrum-mesh-angle',
          '--ferrum-mesh-blur',
        ];
      }

      paint(ctx, geom, properties) {
        var color1 = (properties.get('--ferrum-mesh-color-1')?.toString() || '#6366f1').trim();
        var color2 = (properties.get('--ferrum-mesh-color-2')?.toString() || '#a855f7').trim();
        var color3 = (properties.get('--ferrum-mesh-color-3')?.toString() || '#ec4899').trim();
        var angle = parseFloat(properties.get('--ferrum-mesh-angle')) || 0;
        var blur = Math.max(1, parseFloat(properties.get('--ferrum-mesh-blur')) || 60);

        var width = geom.width;
        var height = geom.height;

        ctx.clearRect(0, 0, width, height);

        // Angle rotates the positions of the color points for animated feel
        var rad = (angle * Math.PI) / 180;
        var cosA = Math.cos(rad);
        var sinA = Math.sin(rad);

        // Base positions distributed in a triangle
        var basePoints = [
          { bx: 0.2, by: 0.3 },
          { bx: 0.8, by: 0.3 },
          { bx: 0.5, by: 0.8 },
        ];
        var colors = [color1, color2, color3];

        var maxDim = Math.max(width, height);

        for (var i = 0; i < basePoints.length; i++) {
          var bp = basePoints[i];
          // Rotate position around center
          var cx = width / 2;
          var cy = height / 2;
          var dx = (bp.bx - 0.5) * width;
          var dy = (bp.by - 0.5) * height;
          var rx = cx + dx * cosA - dy * sinA;
          var ry = cy + dx * sinA + dy * cosA;

          var radius = Math.max(1, maxDim * 0.6);

          ctx.save();
          ctx.shadowColor = colors[i];
          ctx.shadowBlur = blur;

          var grad = ctx.createRadialGradient(rx, ry, 0, rx, ry, radius);
          grad.addColorStop(0, colors[i]);
          grad.addColorStop(0.4, colors[i]);
          grad.addColorStop(1, 'transparent');

          ctx.fillStyle = grad;
          ctx.fillRect(0, 0, width, height);
          ctx.restore();
        }
      }
    });
  `,
};