// ─── Neon Border Worklet ──────────────────────────
// Animated neon border with glowing border lines, shadow blur,
// angle-based gradient sweep, and multiple glow layers for depth.

import type { PaintWorkletDescriptor } from "../types";

/**
 * Descriptor for the ferrum-neon-border paint worklet.
 */
export const neonBorderDescriptor: PaintWorkletDescriptor = {
  name: "ferrum-neon-border" as const,
  inputProperties: [
    "--ferrum-neon-color",
    "--ferrum-neon-intensity",
    "--ferrum-neon-width",
    "--ferrum-neon-angle",
  ] as const,
  cssClass: ".fr-neon-border" as const,
  fallbackCSS: `/* fallback: border + box-shadow glow */
.fr-neon-border {
  --ferrum-neon-color: #06b6d4;
  --ferrum-neon-intensity: 0.7;
  --ferrum-neon-width: 2;
  --ferrum-neon-angle: 0;
  border: var(--ferrum-neon-width) solid var(--ferrum-neon-color);
  box-shadow: 0 0 calc(10px * var(--ferrum-neon-intensity)) var(--ferrum-neon-color),
              0 0 calc(20px * var(--ferrum-neon-intensity)) var(--ferrum-neon-color),
              inset 0 0 calc(5px * var(--ferrum-neon-intensity)) var(--ferrum-neon-color);
}`,
  workletCode: `
    // ferrum-neon-border worklet — Auto-generated by @ferrum/paint
    // Glowing border with multiple glow layers and angle-based gradient sweep
    registerPaint('ferrum-neon-border', class {
      static get inputProperties() {
        return [
          '--ferrum-neon-color',
          '--ferrum-neon-intensity',
          '--ferrum-neon-width',
          '--ferrum-neon-angle',
        ];
      }

      paint(ctx, geom, properties) {
        const color = (properties.get('--ferrum-neon-color')?.toString() || '#06b6d4').trim();
        const intensity = Math.min(1, Math.max(0, parseFloat(properties.get('--ferrum-neon-intensity')) || 0.7));
        const borderW = Math.max(0.5, parseFloat(properties.get('--ferrum-neon-width')) || 2);
        const angle = parseFloat(properties.get('--ferrum-neon-angle')) || 0;

        const { width, height } = geom;

        ctx.clearRect(0, 0, width, height);

        // Layer 1: Deep outer glow
        ctx.save();
        ctx.shadowColor = color;
        ctx.shadowBlur = (20 + 12 * intensity);
        ctx.strokeStyle = color;
        ctx.lineWidth = borderW;
        ctx.globalAlpha = intensity * 0.4;
        ctx.beginPath();
        ctx.roundRect(borderW / 2, borderW / 2, width - borderW, height - borderW, 8);
        ctx.stroke();
        ctx.restore();

        // Layer 2: Medium glow
        ctx.save();
        ctx.shadowColor = color;
        ctx.shadowBlur = (10 + 8 * intensity);
        ctx.strokeStyle = color;
        ctx.lineWidth = borderW;
        ctx.globalAlpha = intensity * 0.7;
        ctx.beginPath();
        ctx.roundRect(borderW / 2, borderW / 2, width - borderW, height - borderW, 8);
        ctx.stroke();
        ctx.restore();

        // Layer 3: Bright core border
        ctx.save();
        ctx.strokeStyle = color;
        ctx.lineWidth = borderW;
        ctx.globalAlpha = intensity;
        ctx.beginPath();
        ctx.roundRect(borderW / 2, borderW / 2, width - borderW, height - borderW, 8);
        ctx.stroke();
        ctx.restore();

        // Layer 4: Inner white highlight edge
        ctx.save();
        ctx.strokeStyle = '#ffffff';
        ctx.lineWidth = Math.max(0.5, borderW * 0.3);
        ctx.globalAlpha = 0.15 * intensity;
        ctx.beginPath();
        ctx.roundRect(borderW + 1, borderW + 1, width - (borderW + 1) * 2, height - (borderW + 1) * 2, 6);
        ctx.stroke();
        ctx.restore();

        // Angle-based gradient sweep for animated feel
        if (angle !== 0) {
          ctx.save();
          const rad = (angle * Math.PI) / 180;
          const cx = width / 2 + Math.cos(rad) * width * 0.35;
          const cy = height / 2 + Math.sin(rad) * height * 0.35;
          const sweepRadius = Math.max(1, Math.max(width, height) * 0.5);

          const hlGrad = ctx.createRadialGradient(cx, cy, 0, cx, cy, sweepRadius);
          hlGrad.addColorStop(0, 'rgba(255,255,255,0.2)');
          hlGrad.addColorStop(0.5, 'rgba(255,255,255,0.05)');
          hlGrad.addColorStop(1, 'rgba(255,255,255,0)');
          ctx.fillStyle = hlGrad;

          // Clip to border region
          ctx.beginPath();
          ctx.roundRect(0, 0, width, height, 8);
          ctx.roundRect(borderW, borderW, width - borderW * 2, height - borderW * 2, 6);
          ctx.fill('evenodd');
          ctx.restore();
        }
      }
    });
  `,
};