// ─── Noise Worklet ──────────────────────────
// Procedural noise texture using value noise. Tiled/repeatable across any size.
// Useful as overlay for glassmorphism.

import type { PaintWorkletDescriptor } from "../types";

/**
 * Descriptor for the ferrum-noise paint worklet.
 */
export const noiseDescriptor: PaintWorkletDescriptor = {
  name: "ferrum-noise" as const,
  inputProperties: [
    "--ferrum-noise-scale",
    "--ferrum-noise-opacity",
    "--ferrum-noise-color",
  ] as const,
  cssClass: ".fr-noise" as const,
  fallbackCSS: `/* fallback: SVG-based noise texture */
.fr-noise {
  --ferrum-noise-scale: 4;
  --ferrum-noise-opacity: 0.05;
  --ferrum-noise-color: #000000;
  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.05'/%3E%3C/svg%3E");
  background-repeat: repeat;
  background-size: 256px 256px;
}`,
  workletCode: `
    // ferrum-noise worklet — Auto-generated by @ferrum/paint
    // Tiled value noise texture for overlay effects
    registerPaint('ferrum-noise', class {
      static get inputProperties() {
        return [
          '--ferrum-noise-scale',
          '--ferrum-noise-opacity',
          '--ferrum-noise-color',
        ];
      }

      // Simple hash for deterministic pseudo-random
      _hash(x, y) {
        let h = x * 374761393 + y * 668265263;
        h = (h ^ (h >> 13)) * 1274126177;
        h = h ^ (h >> 16);
        return (h & 0x7fffffff) / 0x7fffffff;
      }

      // Smooth value noise with bilinear interpolation (tiles at tileW/tileH)
      _valueNoise(px, py, scale, tileW, tileH) {
        var sx = px / scale;
        var sy = py / scale;
        var x0 = Math.floor(sx) % tileW;
        var y0 = Math.floor(sy) % tileH;
        if (x0 < 0) x0 += tileW;
        if (y0 < 0) y0 += tileH;
        var x1 = (x0 + 1) % tileW;
        var y1 = (y0 + 1) % tileH;
        var fx = sx - Math.floor(sx);
        var fy = sy - Math.floor(sy);

        // Smoothstep
        var u = fx * fx * (3 - 2 * fx);
        var v = fy * fy * (3 - 2 * fy);

        var a = this._hash(x0, y0);
        var b = this._hash(x1, y0);
        var c = this._hash(x0, y1);
        var d = this._hash(x1, y1);

        return a + (b - a) * u + (c - a) * v + (a - b - c + d) * u * v;
      }

      paint(ctx, geom, properties) {
        var scale = Math.max(1, parseFloat(properties.get('--ferrum-noise-scale')) || 4);
        var opacity = Math.min(1, Math.max(0, parseFloat(properties.get('--ferrum-noise-opacity')) || 0.05));
        var color = (properties.get('--ferrum-noise-color')?.toString() || '#000000').trim();

        var width = geom.width;
        var height = geom.height;

        ctx.clearRect(0, 0, width, height);

        // Parse color to RGB
        var r = 0, g = 0, b = 0;
        if (color.startsWith('#') && color.length >= 7) {
          r = parseInt(color.slice(1, 3), 16);
          g = parseInt(color.slice(3, 5), 16);
          b = parseInt(color.slice(5, 7), 16);
        } else if (color.startsWith('#') && color.length === 4) {
          r = parseInt(color[1] + color[1], 16);
          g = parseInt(color[2] + color[2], 16);
          b = parseInt(color[3] + color[3], 16);
        }

        // Tiling dimensions — ensures seamless repeat
        var tileW = Math.max(1, Math.ceil(256 / scale));
        var tileH = Math.max(1, Math.ceil(256 / scale));

        // Generate tiled noise using dot-pattern approach for performance
        var cellSize = Math.max(2, Math.round(scale));
        var cols = Math.ceil(width / cellSize);
        var rows = Math.ceil(height / cellSize);

        ctx.save();
        for (var row = 0; row < rows; row++) {
          for (var col = 0; col < cols; col++) {
            var px = col * cellSize;
            var py = row * cellSize;
            var n = this._valueNoise(px, py, scale, tileW, tileH);
            var alpha = opacity * n;
            if (alpha < 0.005) continue;
            ctx.globalAlpha = alpha;
            ctx.fillStyle = color;
            ctx.fillRect(px, py, cellSize, cellSize);
          }
        }
        ctx.restore();
      }
    });
  `,
};