// ─── Ripple Worklet ──────────────────────────
// Interactive ripple effect. Draws expanding circle from center point,
// fades out as progress approaches 1. Uses progress (0-1) to control radius and opacity.

import type { PaintWorkletDescriptor } from "../types";

/**
 * Descriptor for the ferrum-ripple paint worklet.
 */
export const rippleDescriptor: PaintWorkletDescriptor = {
  name: "ferrum-ripple" as const,
  inputProperties: [
    "--ferrum-ripple-x",
    "--ferrum-ripple-y",
    "--ferrum-ripple-color",
    "--ferrum-ripple-progress",
    "--ferrum-ripple-size",
  ] as const,
  cssClass: ".fr-ripple" as const,
  fallbackCSS: `/* fallback: ripple hidden in non-Houdini browsers */
.fr-ripple {
  --ferrum-ripple-x: 50%;
  --ferrum-ripple-y: 50%;
  --ferrum-ripple-color: rgba(255, 255, 255, 0.3);
  --ferrum-ripple-progress: 0;
  --ferrum-ripple-size: 300;
  display: none;
}
@supports (background: paint(id)) {
  .fr-ripple { display: block; }
}`,
  workletCode: `
    // ferrum-ripple worklet — Auto-generated by @ferrum/paint
    // Expanding circle ripple from a center point, fading with progress
    registerPaint('ferrum-ripple', class {
      static get inputProperties() {
        return [
          '--ferrum-ripple-x',
          '--ferrum-ripple-y',
          '--ferrum-ripple-color',
          '--ferrum-ripple-progress',
          '--ferrum-ripple-size',
        ];
      }

      paint(ctx, geom, properties) {
        const x = parseFloat(properties.get('--ferrum-ripple-x')) || 0;
        const y = parseFloat(properties.get('--ferrum-ripple-y')) || 0;
        const color = (properties.get('--ferrum-ripple-color')?.toString() || 'rgba(255,255,255,0.3)').trim();
        const progress = Math.min(1, Math.max(0, parseFloat(properties.get('--ferrum-ripple-progress')) || 0));
        const size = Math.max(1, parseFloat(properties.get('--ferrum-ripple-size')) || 300);

        if (progress <= 0) return;

        const { width, height } = geom;

        // Calculate the radius needed to fill from the click point to all corners
        const distTopLeft = Math.sqrt(x * x + y * y);
        const distTopRight = Math.sqrt((width - x) * (width - x) + y * y);
        const distBottomLeft = Math.sqrt(x * x + (height - y) * (height - y));
        const distBottomRight = Math.sqrt((width - x) * (width - x) + (height - y) * (height - y));
        const fillRadius = Math.max(distTopLeft, distTopRight, distBottomLeft, distBottomRight);

        // Blend between size and fillRadius based on progress for natural feel
        const currentRadius = Math.max(1, fillRadius * progress);

        ctx.clearRect(0, 0, width, height);

        // Opacity fades as ripple expands toward completion
        ctx.save();
        ctx.globalAlpha = (1 - progress * progress) * 0.35;
        ctx.fillStyle = color;
        ctx.beginPath();
        ctx.arc(x, y, currentRadius, 0, Math.PI * 2);
        ctx.fill();
        ctx.restore();

        // Subtle ring at the edge for visual definition
        ctx.save();
        ctx.globalAlpha = (1 - progress) * 0.15;
        ctx.strokeStyle = color;
        ctx.lineWidth = 2;
        ctx.beginPath();
        ctx.arc(x, y, currentRadius, 0, Math.PI * 2);
        ctx.stroke();
        ctx.restore();
      }
    });
  `,
};