// ─── Skeleton Worklet ──────────────────────────
// Skeleton shimmer loader. Base color fill with moving highlight gradient.
// Linear gradient sweep for shimmer effect using angle to control direction.

import type { PaintWorkletDescriptor } from "../types";

/**
 * Descriptor for the ferrum-skeleton paint worklet.
 */
export const skeletonDescriptor: PaintWorkletDescriptor = {
  name: "ferrum-skeleton" as const,
  inputProperties: [
    "--ferrum-skeleton-color",
    "--ferrum-skeleton-highlight",
    "--ferrum-skeleton-speed",
    "--ferrum-skeleton-angle",
  ] as const,
  cssClass: ".fr-skeleton" as const,
  fallbackCSS: `/* fallback: CSS-only shimmer via gradient animation */
.fr-skeleton {
  --ferrum-skeleton-color: #e4e4e7;
  --ferrum-skeleton-highlight: #f4f4f5;
  --ferrum-skeleton-speed: 1.5s;
  --ferrum-skeleton-angle: -25;
  border-radius: 4px;
  min-height: 1em;
  min-width: 3em;
  background: linear-gradient(
    90deg,
    var(--ferrum-skeleton-color) 25%,
    var(--ferrum-skeleton-highlight) 50%,
    var(--ferrum-skeleton-color) 75%
  );
  background-size: 200% 100%;
  animation: fr-skeleton-shimmer var(--ferrum-skeleton-speed) ease-in-out infinite;
}
@keyframes fr-skeleton-shimmer {
  0% { background-position: 200% 0; }
  100% { background-position: -200% 0; }
}`,
  workletCode: `
    // ferrum-skeleton worklet — Auto-generated by @ferrum/paint
    // Skeleton shimmer with base fill and moving highlight gradient
    registerPaint('ferrum-skeleton', class {
      static get inputProperties() {
        return [
          '--ferrum-skeleton-color',
          '--ferrum-skeleton-highlight',
          '--ferrum-skeleton-speed',
          '--ferrum-skeleton-angle',
        ];
      }

      paint(ctx, geom, properties) {
        var baseColor = (properties.get('--ferrum-skeleton-color')?.toString() || '#e4e4e7').trim();
        var hlColor = (properties.get('--ferrum-skeleton-highlight')?.toString() || '#f4f4f5').trim();
        var angle = parseFloat(properties.get('--ferrum-skeleton-angle')) || -25;

        var width = geom.width;
        var height = geom.height;

        ctx.clearRect(0, 0, width, height);

        // Base fill
        ctx.save();
        ctx.fillStyle = baseColor;
        ctx.beginPath();
        ctx.roundRect(0, 0, width, height, 4);
        ctx.fill();
        ctx.restore();

        // Shimmer highlight band using angle for direction
        ctx.save();
        ctx.beginPath();
        ctx.roundRect(0, 0, width, height, 4);
        ctx.clip();

        var rad = (angle * Math.PI) / 180;
        var bandWidth = Math.max(1, width * 0.3);
        var offset = width * 0.8;

        var x1 = -bandWidth + offset * Math.cos(rad);
        var y1 = -bandWidth + offset * Math.sin(rad);
        var x2 = width + bandWidth + offset * Math.cos(rad);
        var y2 = height + bandWidth + offset * Math.sin(rad);

        var grad = ctx.createLinearGradient(x1, y1, x2, y2);
        grad.addColorStop(0, 'transparent');
        grad.addColorStop(0.35, hlColor);
        grad.addColorStop(0.65, hlColor);
        grad.addColorStop(1, 'transparent');

        ctx.fillStyle = grad;
        ctx.fillRect(-bandWidth * 2, -bandWidth * 2, width + bandWidth * 4, height + bandWidth * 4);
        ctx.restore();
      }
    });
  `,
};