// ===== Ferrum A11y — Main CSS Generator =====
//
// Orchestrates all accessibility CSS generation into organized
// @layer sections with section comments and optional minification.

import type { A11yConfig } from './types';
import { generateFocusCSS } from './focus';
import { generateKeyboardCSS } from './keyboard';
import { generateMotionA11yCSS } from './motion';

/** Default configuration values. */
const defaults: Required<A11yConfig> = {
  wcagLevel: 'AA',
  contrastRatio: { normal: 4.5, large: 3.0 },
  focusVisible: true,
  reducedMotion: true,
  touchTarget: { minSize: 44, unit: 'px' },
  skipLinks: true,
  screenReaderOnly: true,
};

/** Merge user config with defaults. */
function resolveConfig(config?: A11yConfig): A11yConfig {
  const cr = config?.contrastRatio;
  const tt = config?.touchTarget;
  return {
    wcagLevel: config?.wcagLevel ?? defaults.wcagLevel,
    contrastRatio: {
      normal: cr?.normal ?? defaults.contrastRatio.normal,
      large: cr?.large ?? defaults.contrastRatio.large,
    },
    focusVisible: config?.focusVisible ?? defaults.focusVisible,
    reducedMotion: config?.reducedMotion ?? defaults.reducedMotion,
    touchTarget: {
      minSize: tt?.minSize ?? defaults.touchTarget.minSize,
      unit: tt?.unit ?? defaults.touchTarget.unit,
    },
    skipLinks: config?.skipLinks ?? defaults.skipLinks,
    screenReaderOnly: config?.screenReaderOnly ?? defaults.screenReaderOnly,
  };
}

/** Simple CSS minifier — strips comments and excess whitespace. */
function minifyCSS(css: string): string {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\s+/g, ' ')
    .replace(/\s*([{}:;,>~+])\s*/g, '$1')
    .trim();
}

/**
 * Generate the complete accessibility CSS for the Ferrum Platform.
 *
 * Output is organized into CSS @layer sections:
 *   - `ferrum.a11y.focus`        — Focus visibility, skip links, sr-only
 *   - `ferrum.a11y.keyboard`     — Keyboard navigation, focus traps
 *   - `ferrum.a11y.motion`       — Reduced motion, motion preferences
 *   - `ferrum.a11y.screen-reader`— Screen reader utilities (layered alias)
 *   - `ferrum.a11y.touch`        — Touch target sizing
 *
 * @param config - Accessibility configuration. Uses defaults when omitted.
 * @param minify - Whether to minify the output (default: false).
 * @returns Complete accessibility CSS string.
 */
export function generateA11yCSS(config?: A11yConfig, minify?: boolean): string {
  const resolved = resolveConfig(config);
  const sections: string[] = [];

  // ---- Header ----
  sections.push(`/* ===== Ferrum A11y — Accessibility Engine =====
 *
 * WCAG ${resolved.wcagLevel} conformance helpers
 * Generated by @ferrum/a11y v0.0.1
 */`);

  // ---- Layer Imports (order matters — earlier layers have lower priority) ----
  sections.push(`@layer ferrum.a11y.focus, ferrum.a11y.keyboard, ferrum.a11y.screen-reader, ferrum.a11y.touch, ferrum.a11y.motion;`);

  // ---- CSS Custom Properties ----
  const thresholds = resolved.contrastRatio!;
  sections.push(`
/* ===== Ferrum A11y — Custom Properties ===== */
@layer ferrum.a11y.focus {
  :root {
    --fr-a11y-wcag-level: ${resolved.wcagLevel};
    --fr-a11y-contrast-normal: ${thresholds.normal};
    --fr-a11y-contrast-large: ${thresholds.large};
    --fr-focus-color: currentColor;
    --fr-focus-offset: 2px;
    --fr-focus-width: 3px;
    --fr-focus-radius: 2px;
    --fr-skip-link-bg: #000;
    --fr-skip-link-color: #fff;
  }
}`);

  // ---- Focus Visibility ----
  if (resolved.focusVisible !== false) {
    const focusCSS = generateFocusCSS(resolved);
    sections.push(`
/* ===== Ferrum A11y — Focus & Screen Reader ===== */
@layer ferrum.a11y.focus {
${indent(focusCSS, 2)}
}`);

    // Screen reader gets its own layer entry (but uses same CSS)
    if (resolved.screenReaderOnly !== false) {
      sections.push(`
@layer ferrum.a11y.screen-reader {
  /* Screen reader utilities are defined in ferrum.a11y.focus layer */
}`);
    }
  }

  // ---- Keyboard Navigation ----
  const keyboardCSS = generateKeyboardCSS();
  sections.push(`
/* ===== Ferrum A11y — Keyboard Navigation ===== */
@layer ferrum.a11y.keyboard {
${indent(keyboardCSS, 2)}
}`);

  // ---- Touch Targets ----
  if (resolved.touchTarget) {
    const { minSize, unit } = resolved.touchTarget;
    sections.push(`
/* ===== Ferrum A11y — Touch Targets ===== */
@layer ferrum.a11y.touch {
  /* Minimum touch target: ${minSize}${unit} (WCAG 2.5.8) */
  a,
  button,
  input[type="button"],
  input[type="submit"],
  input[type="reset"],
  [role="button"],
  [role="link"],
  [role="tab"] {
    min-height: ${minSize}${unit};
    min-width: ${minSize}${unit};
  }

  /* Ensure adequate spacing between touch targets */
  .fr-touch-group > * + * {
    margin-top: 0.5rem;
  }
}`);
  }

  // ---- Motion Accessibility ----
  if (resolved.reducedMotion !== false) {
    const motionCSS = generateMotionA11yCSS();
    sections.push(`
/* ===== Ferrum A11y — Motion Safety ===== */
@layer ferrum.a11y.motion {
${indent(motionCSS, 2)}
}`);
  }

  let combined = sections.join('\n\n');

  if (minify) {
    combined = minifyCSS(combined);
  }

  return combined;
}

/** Indent every line of CSS by a given number of spaces. */
function indent(css: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return css
    .split('\n')
    .map((line) => (line.trim() ? pad + line : line))
    .join('\n');
}