import fs from 'fs-extra';
import path from 'path';
import { execaCommand } from 'execa';
import { detectPackageManager } from 'detect-package-manager';
import inquirer from 'inquirer';
import chalk from 'chalk';
import { info, success, warn, error, step, spinner, succeedSpinner, failSpinner } from '../utils/logger';
import { detectFramework, getDefaultConfig, type FrameworkType, type FerrumConfig } from '../utils/config';
import {
  getPackagesForFramework,
  getInstallCommand,
  getImportStatement,
  getProviderSetup,
  getEntryFiles,
  getCSSImportStatement,
} from '../utils/frameworks';

// --- Types ---

interface InitAnswers {
  framework: FrameworkType;
  cssOnly: boolean;
  theme: 'light' | 'dark' | 'system';
  installPackages: boolean;
  addImports: boolean;
}

// --- Command ---

export async function initCommand(): Promise<void> {
  info('Welcome to Ferrum! Let\'s set up your project.');

  const cwd = process.cwd();
  const detectedFramework = detectFramework(cwd);

  // Check if already configured
  const existingConfig = [
    'ferrum.config.ts',
    'ferrum.config.js',
    'ferrum.config.json',
  ].find((f) => fs.existsSync(path.join(cwd, f)));

  if (existingConfig) {
    const { overwrite } = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'overwrite',
        message: `Found ${existingConfig}. Overwrite?`,
        default: false,
      },
    ]);

    if (!overwrite) {
      info('Aborted. Your existing config was preserved.');
      return;
    }
  }

  // Prompt for configuration
  const answers: InitAnswers = await inquirer.prompt([
    {
      type: 'list',
      name: 'framework',
      message: 'Which framework are you using?',
      choices: [
        { name: 'React', value: 'react' },
        { name: 'Next.js', value: 'next' },
        { name: 'Vue', value: 'vue' },
        { name: 'Angular', value: 'angular' },
        { name: 'Svelte', value: 'svelte' },
        { name: 'Vanilla JS/TS', value: 'vanilla' },
      ],
      default: detectedFramework ?? 'react',
    },
    {
      type: 'confirm',
      name: 'cssOnly',
      message: 'Use CSS-only mode (no JS components/hooks)?',
      default: false,
    },
    {
      type: 'list',
      name: 'theme',
      message: 'Which theme mode?',
      choices: [
        { name: 'System (follows OS preference)', value: 'system' },
        { name: 'Light', value: 'light' },
        { name: 'Dark', value: 'dark' },
      ],
      default: 'system',
    },
    {
      type: 'confirm',
      name: 'installPackages',
      message: 'Install @ferrum packages now?',
      default: true,
    },
    {
      type: 'confirm',
      name: 'addImports',
      message: 'Add imports to your entry file?',
      default: true,
      when: (ans: InitAnswers) => ans.installPackages,
    },
  ]);

  const { framework, cssOnly, theme, installPackages, addImports } = answers;

  // --- Step 1: Create ferrum.config.ts ---

  step('Creating ferrum.config.ts...');
  const config: FerrumConfig = {
    framework,
    theme,
    cssOnly,
  };

  if (!cssOnly) {
    const frameworkPackageMap: Record<string, string> = {
      react: '@ferrum/react',
      next: '@ferrum/next',
      vue: '@ferrum/vue',
      angular: '@ferrum/tokens',
      svelte: '@ferrum/tokens',
      vanilla: '@ferrum/tokens',
    };
    config.importPath = frameworkPackageMap[framework];
  }

  config.cssPath = '@ferrum/tokens/css';
  config.motionPath = '@ferrum/motion/css';

  const configContent = `// Ferrum Platform Configuration
// Generated by \`ferrum init\`

import type { FerrumConfig } from '@ferrum/cli';

export default {
  framework: '${framework}',
  theme: '${theme}',
  cssOnly: ${cssOnly},
${!cssOnly ? `  importPath: '${config.importPath}',\n` : ''}  cssPath: '${config.cssPath}',
  motionPath: '${config.motionPath}',
} satisfies FerrumConfig;
`;

  fs.writeFileSync(path.join(cwd, 'ferrum.config.ts'), configContent, 'utf-8');
  success('Created ferrum.config.ts');

  // --- Step 2: Install packages ---

  if (installPackages) {
    const spin = spinner('Detecting package manager...');
    let pm: string;
    try {
      pm = await detectPackageManager(cwd);
    } catch {
      pm = 'npm';
    }
    succeedSpinner(`Detected ${chalk.cyan(pm)}`);

    const packages = getPackagesForFramework(framework, cssOnly);
    const installCmd = getInstallCommand(pm, packages);

    step(`Installing packages: ${chalk.cyan(packages.join(', '))}`);
    const installSpin = spinner(`Running: ${installCmd}`);

    try {
      await execaCommand(installCmd, {
        cwd,
        timeout: 120000,
        stdio: 'pipe',
      });
      succeedSpinner('Packages installed');
    } catch (err: unknown) {
      const errMsg = err instanceof Error ? err.message : String(err);
      failSpinner('Package installation failed');
      error(`Error: ${errMsg}`);
      warn('You can install manually:');
      warn(`  ${installCmd}`);
      return;
    }
  }

  // --- Step 3: Add imports to entry file ---

  if (addImports) {
    step('Looking for entry file...');
    const entryFiles = getEntryFiles(framework);
    let foundEntryFile: string | null = null;

    for (const entry of entryFiles) {
      if (fs.existsSync(path.join(cwd, entry))) {
        foundEntryFile = entry;
        break;
      }
    }

    if (foundEntryFile) {
      const importCode = getImportStatement(framework, cssOnly ? '@ferrum/tokens' : `@ferrum/${framework === 'next' ? 'next' : framework}`);
      const cssImport = getCSSImportStatement(cssOnly);
      const providerCode = !cssOnly ? getProviderSetup(framework) : '';

      // Read the entry file
      const entryPath = path.join(cwd, foundEntryFile);
      const entryContent = fs.readFileSync(entryPath, 'utf-8');

      // Check if ferrum imports already exist
      if (entryContent.includes('@ferrum/')) {
        warn(`Entry file ${chalk.cyan(foundEntryFile)} already contains @ferrum imports. Skipping.`);
      } else {
        // Prepend the import
        const newContent = `${importCode}\n${cssImport}\n\n${entryContent}`;
        fs.writeFileSync(entryPath, newContent, 'utf-8');
        success(`Added imports to ${chalk.cyan(foundEntryFile)}`);
      }

      if (providerCode && !entryContent.includes('FerrumProvider') && !entryContent.includes('createFerrum')) {
        info('\nTo activate Ferrum, update your provider setup:');
        console.log(chalk.gray('─'.repeat(50)));
        console.log(providerCode);
        console.log(chalk.gray('─'.repeat(50)));
      }
    } else {
      warn('Could not find an entry file. Add the imports manually:');
      const importCode = getImportStatement(framework, cssOnly ? '@ferrum/tokens' : `@ferrum/${framework === 'next' ? 'next' : framework}`);
      console.log(chalk.gray('─'.repeat(50)));
      console.log(importCode);
      const providerCode = !cssOnly ? getProviderSetup(framework) : '';
      if (providerCode) {
        console.log();
        console.log(providerCode);
      }
      console.log(chalk.gray('─'.repeat(50)));
    }
  }

  // --- Done ---

  console.log();
  success(chalk.bold('Ferrum is configured and ready!'));
  console.log();
  info('Next steps:');
  console.log(`  ${chalk.cyan('1.')} Import the CSS in your entry file:`);
  console.log(`     ${chalk.gray(`import '@ferrum/tokens/css';`)}`);
  console.log(`     ${chalk.gray(`import '@ferrum/motion/css';`)}`);

  if (!cssOnly) {
    console.log(`  ${chalk.cyan('2.')} Wrap your app with the Ferrum provider`);
    console.log(`     ${chalk.gray(getProviderSetup(framework).split('\n')[0])}`);
  }

  console.log(`  ${chalk.cyan('3.')} Start using Ferrum tokens and animations!`);
  console.log(`     ${chalk.gray('https://ferrum.dev/docs')} `);
  console.log();
}