#!/usr/bin/env python3
"""Consolidate all audit zone findings into master backlog JSON."""
import json
from pathlib import Path
from datetime import datetime, timezone

# All findings from the 5 audit agents
findings = [
    # === ZONE A: Core App (25 findings) ===
    {"id":"AUDIT-A-001","zone":"A-CoreApp","file":"src/app/home-client.tsx","line":332,"severity":"HIGH","category":"dead-code","title":"setMeta regex uses double quotes but callers use single quotes","description":"The setMeta helper regex /^(name|property|http-equiv)=\"(.+)\"$/ requires double quotes but all call sites use single quotes. Regex never matches — orphan meta tags created.","recommendation":"Change regex to accept both quote styles: /^(name|property|http-equiv)=[\"\'](.+?)[\"\']$/","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-A-002","zone":"A-CoreApp","file":"src/app/layout.tsx","line":148,"severity":"MEDIUM","category":"broken-ref","title":"BreadcrumbList JSON-LD misuses schema — lists all top-level pages","description":"BreadcrumbList has 7 ListItem entries each pointing to different pages. A BreadcrumbList represents a single navigation path, not a sitemap.","recommendation":"Remove BreadcrumbList and ItemList JSON-LD, keep only WebSite + SoftwareApplication + Organization schemas.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-A-003","zone":"A-CoreApp","file":"src/app/layout.tsx","line":162,"severity":"LOW","category":"dead-code","title":"ItemList JSON-LD has 12 items all pointing to same /effects URL","description":"All 12 items have url: /effects providing zero SEO value.","recommendation":"Remove ItemList JSON-LD entirely.","effort":"TRIVIAL","team":"Alpha"},
    {"id":"AUDIT-A-004","zone":"A-CoreApp","file":"src/app/layout.tsx","line":195,"severity":"LOW","category":"performance","title":"Five separate JSON-LD script tags should be consolidated","description":"Five <script type=application/ld+json> tags could be merged into single @graph block.","recommendation":"Merge into single @graph JSON-LD block.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-A-005","zone":"A-CoreApp","file":"src/app/layout.tsx","line":142,"severity":"LOW","category":"consistency","title":"softwareLd version hardcoded as 1.0.0 — drifts from package.json","description":"SoftwareApplication JSON-LD has version hardcoded.","recommendation":"Import version from package.json.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-A-006","zone":"A-CoreApp","file":"src/app/cloud/page.tsx","line":256,"severity":"LOW","category":"dead-code","title":"void tokens.length / void components.length are no-op dead code","description":"Void statements serve no purpose — variables are used elsewhere in the component.","recommendation":"Remove both void statements and the associated comment.","effort":"TRIVIAL","team":"Alpha"},
    {"id":"AUDIT-A-007","zone":"A-CoreApp","file":"src/app/cloud/page.tsx","line":136,"severity":"MEDIUM","category":"accessibility","title":"Login form missing form element — no proper submission semantics","description":"Login gate uses bare Input and Button without wrapping in form element.","recommendation":"Wrap login fields in <form onSubmit={handleSubmit}>.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-A-008","zone":"A-CoreApp","file":"src/app/cloud/page.tsx","line":682,"severity":"MEDIUM","category":"accessibility","title":"All four cloud modals lack focus trapping and ARIA attributes","description":"Create Team, Create Project, Create Token, Edit Token modals lack focus traps, aria-modal, role=dialog.","recommendation":"Add role=dialog, aria-modal=true, aria-labelledby, focus trap, Escape handler to each modal.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-A-009","zone":"A-CoreApp","file":"src/app/cloud/page.tsx","line":388,"severity":"LOW","category":"accessibility","title":"Cloud tab bar lacks ARIA tab pattern","description":"CSS-based tab bar uses plain buttons without tablist/tab/tabpanel ARIA pattern.","recommendation":"Add ARIA tab pattern with role, aria-selected, keyboard arrow navigation.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-A-010","zone":"A-CoreApp","file":"src/app/home-client.tsx","line":161,"severity":"LOW","category":"type-safety","title":"Double type assertion in pathnameToView — should use type guard","description":"Segment cast as ViewId twice instead of proper type guard.","recommendation":"Create isViewId() type guard function.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-A-011","zone":"A-CoreApp","file":"src/app/not-found.tsx","line":1,"severity":"LOW","category":"dead-code","title":"not-found.tsx is unreachable for SPA client-side routes","description":"SPA handles 404s internally; not-found.tsx only triggers for non-SPA paths.","recommendation":"Accept as safety net. No action needed.","effort":"N/A","team":"Alpha"},
    {"id":"AUDIT-A-012","zone":"A-CoreApp","file":"src/app/not-found.tsx","line":29,"severity":"LOW","category":"accessibility","title":"Reload Page button on 404 is unhelpful","description":"Reloading a 404 shows the same 404 again.","recommendation":"Replace with Back button (history.back()) or remove.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-A-013","zone":"A-CoreApp","file":"src/proxy.ts","line":1,"severity":"MEDIUM","category":"type-safety","title":"@ts-nocheck on security-critical proxy.ts","description":"Disables all type checking on auth/rate-limiting code.","recommendation":"Remove @ts-nocheck and fix underlying type errors.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-A-014","zone":"A-CoreApp","file":"next.config.ts","line":46,"severity":"MEDIUM","category":"security","title":"CSP allows unsafe-eval — weakens XSS protection","description":"script-src includes unsafe-eval which allows eval() and new Function().","recommendation":"Test removing unsafe-eval in production builds. Document any remaining requirement.","effort":"LARGE","team":"Alpha"},
    {"id":"AUDIT-A-015","zone":"A-CoreApp","file":"Caddyfile","line":1,"severity":"MEDIUM","category":"security","title":"Caddyfile listens on port 81 without TLS","description":"Plain HTTP reverse proxy on non-standard port.","recommendation":"If edge server, use :443 with auto-TLS. If behind proxy, document architecture.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-A-016","zone":"A-CoreApp","file":"next.config.ts","line":46,"severity":"LOW","category":"security","title":"CSP missing wasm-unsafe-eval for future WASM support","description":"If WASM is needed later, it will be blocked by current CSP.","recommendation":"Informational only — no current code uses WASM.","effort":"TRIVIAL","team":"Alpha"},
    {"id":"AUDIT-A-017","zone":"A-CoreApp","file":"src/app/home-client.tsx","line":342,"severity":"LOW","category":"consistency","title":"Hardcoded SITE_URL in client-side meta tag updates","description":"URL hardcoded in home-client.tsx instead of shared constant.","recommendation":"Extract SITE_URL to shared constants file.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-A-018","zone":"A-CoreApp","file":"src/app/globals.css","line":511,"severity":"LOW","category":"dead-code","title":"Stale comment references nothing","description":"Orphaned 'scroll-behavior declared above' comment.","recommendation":"Remove stale comment.","effort":"TRIVIAL","team":"Alpha"},
    {"id":"AUDIT-A-019","zone":"A-CoreApp","file":"src/app/cloud/page.tsx","line":43,"severity":"LOW","category":"accessibility","title":"Color-only status badges may fail WCAG contrast","description":"Low-opacity color backgrounds (15%) with small text may fail contrast requirements.","recommendation":"Add aria-label attributes to badges.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-A-020","zone":"A-CoreApp","file":"next.config.ts","line":3,"severity":"LOW","category":"consistency","title":"SPA_ROUTES must stay in sync with VALID_VIEWS — no automated check","description":"Adding a new view requires updating both files with no validation.","recommendation":"Extract route list to shared constant or add a test.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-A-021","zone":"A-CoreApp","file":"src/app/layout.tsx","line":229,"severity":"LOW","category":"performance","title":"SW registration via inline script parsed on every page load","description":"Inline script registers load listener on every navigation.","recommendation":"Move SW registration into WebVitalsReporter component.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-A-022","zone":"A-CoreApp","file":"vitest.config.ts","line":12,"severity":"LOW","category":"consistency","title":"css: true in Vitest may cause issues with Tailwind v4","description":"Tailwind v4 @import directives may cause test flakiness.","recommendation":"Verify tests pass or set css: false.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-A-023","zone":"A-CoreApp","file":"src/app/error.tsx","line":1,"severity":"LOW","category":"consistency","title":"error.tsx and global-error.tsx duplicate icon imports and styling","description":"Nearly identical error pages — any change must be applied twice.","recommendation":"Extract shared ErrorPageContent component.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-A-024","zone":"A-CoreApp","file":"src/app/global-error.tsx","line":13,"severity":"LOW","category":"consistency","title":"global-error.tsx logs error without useEffect — may log during SSR","description":"console.error in component body vs error.tsx which uses useEffect.","recommendation":"Wrap in useEffect to match error.tsx pattern.","effort":"TRIVIAL","team":"Alpha"},
    {"id":"AUDIT-A-025","zone":"A-CoreApp","file":"src/app/cloud/page.tsx","line":1,"severity":"MEDIUM","category":"performance","title":"Cloud dashboard is single 820-line component with no code splitting","description":"All imports loaded even on login screen. No lazy loading.","recommendation":"Split into CloudLoginPage, CloudDashboard, individual tab views.","effort":"LARGE","team":"Alpha"},

    # === ZONE B: Sections (58 findings) ===
    {"id":"AUDIT-B-001","zone":"B-Sections","file":"src/components/ferrum/sections/hall-of-fame.tsx","line":108,"severity":"HIGH","category":"placeholder","title":"All 5 Hall of Fame demos show Coming Soon placeholders","description":"Every demo renders placeholder with Coming Soon text.","recommendation":"Implement actual demo previews or replace with static screenshots.","effort":"LARGE","team":"Charlie"},
    {"id":"AUDIT-B-002","zone":"B-Sections","file":"src/components/ferrum/sections/showcase-gallery.tsx","line":32,"severity":"HIGH","category":"placeholder","title":"All 8 showcase projects are coming-soon — zero live demos","description":"Every project has status coming-soon. The page proves nothing.","recommendation":"Implement at least 2-3 live demos or add screenshots.","effort":"LARGE","team":"Charlie"},
    {"id":"AUDIT-B-003","zone":"B-Sections","file":"src/components/ferrum/sections/enterprise-components.tsx","line":160,"severity":"HIGH","category":"placeholder","title":"11 of 12 enterprise components are planned — page is aspirational","description":"Only Command Palette is beta. Rest are planned.","recommendation":"Reframe as roadmap or implement more components.","effort":"LARGE","team":"Foxtrot"},
    {"id":"AUDIT-B-004","zone":"B-Sections","file":"src/components/ferrum/sections/enterprise.tsx","line":97,"severity":"HIGH","category":"placeholder","title":"Enterprise page admits nothing is built yet","description":"Status badge: Designed but not yet built. All features describe future capabilities.","recommendation":"Reframe as roadmap/vision page or implement core features.","effort":"LARGE","team":"Foxtrot"},
    {"id":"AUDIT-B-005","zone":"B-Sections","file":"src/components/ferrum/sections/home/enterprise-section.tsx","line":9,"severity":"HIGH","category":"content","title":"Enterprise section claims SOC 2 / 99.9% uptime — contradicts enterprise.tsx","description":"Home enterprise section makes false claims about existing capabilities.","recommendation":"Update descriptions to future tense or remove unverified claims.","effort":"MEDIUM","team":"India"},
    {"id":"AUDIT-B-006","zone":"B-Sections","file":"src/components/ferrum/sections/showcase-gallery.tsx","line":224,"severity":"HIGH","category":"missing-feature","title":"Submit Project button is non-functional div","description":"CTA rendered as div with no onClick, href, or form action.","recommendation":"Link to GitHub issue template or remove.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-B-007","zone":"B-Sections","file":"src/components/ferrum/sections/showcase-gallery.tsx","line":140,"severity":"MEDIUM","category":"missing-feature","title":"Showcase category filters are non-functional spans","description":"Filter buttons are spans with cursor-default that do nothing.","recommendation":"Implement filtering or remove category bar.","effort":"MEDIUM","team":"Delta"},
    {"id":"AUDIT-B-008","zone":"B-Sections","file":"src/components/ferrum/sections/enterprise-components.tsx","line":167,"severity":"MEDIUM","category":"missing-feature","title":"Enterprise component category filters are non-functional","description":"Category filter bar uses spans that look interactive but do nothing.","recommendation":"Implement filtering or remove.","effort":"MEDIUM","team":"Delta"},
    {"id":"AUDIT-B-009","zone":"B-Sections","file":"src/components/ferrum/sections/home/live-examples-section.tsx","line":14,"severity":"MEDIUM","category":"dead-code","title":"Unused preview field in exampleCategories data","description":"preview field never referenced in JSX.","recommendation":"Remove unused field or implement category deep linking.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-B-010","zone":"B-Sections","file":"src/components/ferrum/sections/platform-architecture.tsx","line":7,"severity":"MEDIUM","category":"dead-code","title":"Unused imports: GitBranch and Package","description":"Imported from lucide-react but never used.","recommendation":"Remove unused imports.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-B-011","zone":"B-Sections","file":"src/components/ferrum/sections/enterprise-components.tsx","line":5,"severity":"MEDIUM","category":"dead-code","title":"Unused import: ArrowRight","description":"Imported but never used.","recommendation":"Remove unused import.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-B-012","zone":"B-Sections","file":"src/components/ferrum/sections/ferrum-principles.tsx","line":78,"severity":"MEDIUM","category":"accessibility","title":"Heading hierarchy skips h2 — goes from h1 to h3","description":"No h2 element, violating WCAG heading hierarchy.","recommendation":"Change h3 to h2 or add h2 section heading.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-013","zone":"B-Sections","file":"src/components/ferrum/sections/hall-of-fame.tsx","line":80,"severity":"MEDIUM","category":"accessibility","title":"Heading hierarchy skips h2","description":"Uses h1 then h3 without h2.","recommendation":"Promote to h2 or add h2.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-014","zone":"B-Sections","file":"src/components/ferrum/sections/showcase-gallery.tsx","line":126,"severity":"MEDIUM","category":"accessibility","title":"Heading hierarchy skips h2","description":"Uses h1 then h3 without h2.","recommendation":"Promote to h2 or add h2.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-015","zone":"B-Sections","file":"src/components/ferrum/sections/learning-center.tsx","line":129,"severity":"MEDIUM","category":"accessibility","title":"Heading hierarchy skips h2","description":"Uses h1 then h3 without h2.","recommendation":"Promote to h2 or add h2.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-016","zone":"B-Sections","file":"src/components/ferrum/sections/ferrum-story.tsx","line":79,"severity":"MEDIUM","category":"accessibility","title":"Heading hierarchy skips h2","description":"Uses h1 then h3 without h2.","recommendation":"Promote to h2 or add h2.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-017","zone":"B-Sections","file":"src/components/ferrum/sections/enterprise-components.tsx","line":144,"severity":"MEDIUM","category":"accessibility","title":"Heading hierarchy skips h2","description":"Uses h1 then h3 without h2.","recommendation":"Promote to h2 or add h2.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-018","zone":"B-Sections","file":"src/components/ferrum/sections/vision-manifesto.tsx","line":75,"severity":"MEDIUM","category":"accessibility","title":"Heading hierarchy skips h2","description":"Uses h1 then h3 without h2.","recommendation":"Promote to h2 or add h2.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-019","zone":"B-Sections","file":"src/components/ferrum/sections/platform-architecture.tsx","line":181,"severity":"MEDIUM","category":"accessibility","title":"Heading hierarchy skips h2","description":"Uses h1 then h3 without h2.","recommendation":"Promote to h2 or add h2.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-020","zone":"B-Sections","file":"src/components/ferrum/sections/enterprise.tsx","line":81,"severity":"MEDIUM","category":"accessibility","title":"Heading hierarchy skips h2","description":"Uses h1 then h3 without h2.","recommendation":"Promote to h2 or add h2.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-021","zone":"B-Sections","file":"src/components/ferrum/sections/learning-center.tsx","line":164,"severity":"HIGH","category":"accessibility","title":"Accordion button missing aria-expanded and aria-controls","description":"Learning path toggle has no ARIA attributes.","recommendation":"Add aria-expanded, aria-controls, id attributes.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-022","zone":"B-Sections","file":"src/components/ferrum/sections/home/counter.tsx","line":21,"severity":"MEDIUM","category":"accessibility","title":"Animated counter lacks aria-live for screen reader announcements","description":"Screen readers read initial 0 and never update.","recommendation":"Wrap in aria-live=polite aria-atomic=true.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-023","zone":"B-Sections","file":"src/components/ferrum/sections/home/marquee-section.tsx","line":15,"severity":"MEDIUM","category":"accessibility","title":"Marquee content quadruplicated without screen reader protection","description":"64 items (4x duplication) all accessible to screen readers.","recommendation":"Add aria-hidden to 3 duplicate sets or entire marquee.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-024","zone":"B-Sections","file":"src/components/ferrum/sections/home/playground-section.tsx","line":139,"severity":"MEDIUM","category":"accessibility","title":"Playground selectors act as radio buttons without ARIA role","description":"Button groups function as radios but lack ARIA pattern.","recommendation":"Add role=radiogroup and role=radio aria-checked.","effort":"MEDIUM","team":"Hotel"},
    {"id":"AUDIT-B-025","zone":"B-Sections","file":"src/components/ferrum/sections/home/hero-section.tsx","line":157,"severity":"LOW","category":"performance","title":"badges array recreated on every render","description":"Static array defined inside component body.","recommendation":"Move to module scope.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-B-026","zone":"B-Sections","file":"src/components/ferrum/sections/home/playground-section.tsx","line":41,"severity":"LOW","category":"performance","title":"effectStyles object recreated on every render","description":"Static Record defined inside component body.","recommendation":"Move to module scope.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-B-027","zone":"B-Sections","file":"src/components/ferrum/sections/home/playground-section.tsx","line":49,"severity":"LOW","category":"performance","title":"codeOutput string recomputed on every render","description":"Template literal computed on every render.","recommendation":"Wrap in useMemo.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-B-028","zone":"B-Sections","file":"src/components/ferrum/sections/home/playground-section.tsx","line":37,"severity":"LOW","category":"content","title":"Dashboard preview shows random fake stats on every mount","description":"Random percentages change on every page mount.","recommendation":"Replace with fixed demo data.","effort":"SMALL","team":"India"},
    {"id":"AUDIT-B-029","zone":"B-Sections","file":"src/components/ferrum/sections/home/counter.tsx","line":18,"severity":"MEDIUM","category":"dead-code","title":"Counter never re-animates if target prop changes","description":"started ref prevents re-animation on prop change.","recommendation":"Reset started when target changes.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-B-030","zone":"B-Sections","file":"src/components/ferrum/sections/home/platform-footer-section.tsx","line":17,"severity":"MEDIUM","category":"broken-ref","title":"Hash scroll uses fragile 500ms setTimeout","description":"Magic number assumes navigation completes in exactly 500ms.","recommendation":"Use router.push().then(requestAnimationFrame).","effort":"MEDIUM","team":"Golf"},
    {"id":"AUDIT-B-031","zone":"B-Sections","file":"src/components/ferrum/sections/footer.tsx","line":9,"severity":"LOW","category":"content","title":"Duplicate /docs link under two different labels","description":"Resources 'Quick Start' and Developers 'Documentation' both link /docs.","recommendation":"Consolidate or change Quick Start link target.","effort":"SMALL","team":"India"},
    {"id":"AUDIT-B-032","zone":"B-Sections","file":"src/components/ferrum/sections/footer.tsx","line":1,"severity":"MEDIUM","category":"consistency","title":"Two duplicate footer components with divergent content","description":"footer.tsx and platform-footer-section.tsx are nearly identical.","recommendation":"Extract shared footer logic into single component.","effort":"MEDIUM","team":"Echo"},
    {"id":"AUDIT-B-033","zone":"B-Sections","file":"src/components/ferrum/sections/home/overview-section.tsx","line":1,"severity":"LOW","category":"type-safety","title":"@ts-nocheck on overview-section.tsx","description":"Disables all type checking.","recommendation":"Replace with targeted @ts-expect-error or fix strict errors.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-B-034","zone":"B-Sections","file":"src/components/ferrum/sections/showcase-gallery.tsx","line":1,"severity":"LOW","category":"type-safety","title":"@ts-nocheck on showcase-gallery.tsx","description":"Disables all type checking.","recommendation":"Replace with targeted @ts-expect-error or fix strict errors.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-B-035","zone":"B-Sections","file":"src/components/ferrum/sections/learning-center.tsx","line":1,"severity":"LOW","category":"type-safety","title":"@ts-nocheck on learning-center.tsx","description":"Disables all type checking.","recommendation":"Replace with targeted @ts-expect-error or fix strict errors.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-B-036","zone":"B-Sections","file":"src/components/ferrum/sections/enterprise-components.tsx","line":1,"severity":"LOW","category":"type-safety","title":"@ts-nocheck on enterprise-components.tsx","description":"Disables all type checking.","recommendation":"Replace with targeted @ts-expect-error or fix strict errors.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-B-037","zone":"B-Sections","file":"src/components/ferrum/sections/vision-manifesto.tsx","line":1,"severity":"LOW","category":"type-safety","title":"@ts-nocheck on vision-manifesto.tsx","description":"Disables all type checking.","recommendation":"Replace with targeted @ts-expect-error or fix strict errors.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-B-038","zone":"B-Sections","file":"src/components/ferrum/sections/platform-architecture.tsx","line":1,"severity":"LOW","category":"type-safety","title":"@ts-nocheck on platform-architecture.tsx","description":"Disables all type checking.","recommendation":"Replace with targeted @ts-expect-error or fix strict errors.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-B-039","zone":"B-Sections","file":"src/components/ferrum/sections/home/architecture-section.tsx","line":9,"severity":"MEDIUM","category":"content","title":"Framework adapter list inconsistent across 3 sources","description":"Hero (8 items incl Lit), architecture-section (8 items incl Lit), platform-architecture (9 items incl Nuxt/Vanilla, no Lit).","recommendation":"Establish single source of truth and update all 3 locations.","effort":"SMALL","team":"India"},
    {"id":"AUDIT-B-040","zone":"B-Sections","file":"src/components/ferrum/sections/home/playground-section.tsx","line":44,"severity":"LOW","category":"dark-mode","title":"Metal effect uses hardcoded dark colors — broken in light mode","description":"from-gray-700 to-gray-900 creates dark blob in light mode.","recommendation":"Add light/dark mode variants.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-B-041","zone":"B-Sections","file":"src/components/ferrum/sections/home/playground-section.tsx","line":45,"severity":"LOW","category":"dark-mode","title":"Depth effect shadow invisible in dark mode","description":"shadow with rgba(0,0,0,0.5) invisible on dark backgrounds.","recommendation":"Use dark-mode aware shadow.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-B-042","zone":"B-Sections","file":"src/components/ferrum/sections/home/playground-section.tsx","line":45,"severity":"LOW","category":"dark-mode","title":"Blur effect uses bg-white/5 without dark variant","description":"Nearly invisible in dark mode.","recommendation":"Use dark: variant.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-B-043","zone":"B-Sections","file":"src/components/ferrum/sections/home/platform-footer-section.tsx","line":47,"severity":"LOW","category":"accessibility","title":"Footer link columns lack nav landmarks","description":"Three link columns without nav elements or aria-labels.","recommendation":"Wrap each column in nav with aria-label.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-044","zone":"B-Sections","file":"src/components/ferrum/sections/footer.tsx","line":58,"severity":"LOW","category":"accessibility","title":"Footer link columns lack nav landmarks","description":"Three link columns without nav elements or aria-labels.","recommendation":"Wrap each column in nav with aria-label.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-045","zone":"B-Sections","file":"src/components/ferrum/sections/home/hero-section.tsx","line":175,"severity":"LOW","category":"style","title":"Static keyframes injected via style tag on every render","description":"4 @keyframes in JSX style element — static CSS.","recommendation":"Move to globals.css.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-B-046","zone":"B-Sections","file":"src/components/ferrum/sections/hall-of-fame.tsx","line":73,"severity":"LOW","category":"accessibility","title":"Page wrapper uses div instead of semantic main","description":"Root div should be main element.","recommendation":"Change div to main.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-047","zone":"B-Sections","file":"src/components/ferrum/sections/showcase-gallery.tsx","line":114,"severity":"LOW","category":"accessibility","title":"Page wrapper uses div instead of semantic main","description":"Root div should be main element.","recommendation":"Change div to main.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-048","zone":"B-Sections","file":"src/components/ferrum/sections/learning-center.tsx","line":117,"severity":"LOW","category":"accessibility","title":"Page wrapper uses div instead of semantic main","description":"Root div should be main element.","recommendation":"Change div to main.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-049","zone":"B-Sections","file":"src/components/ferrum/sections/ferrum-story.tsx","line":72,"severity":"LOW","category":"accessibility","title":"Page wrapper uses div instead of semantic main","description":"Root div should be main element.","recommendation":"Change div to main.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-050","zone":"B-Sections","file":"src/components/ferrum/sections/enterprise-components.tsx","line":132,"severity":"LOW","category":"accessibility","title":"Page wrapper uses div instead of semantic main","description":"Root div should be main element.","recommendation":"Change div to main.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-051","zone":"B-Sections","file":"src/components/ferrum/sections/vision-manifesto.tsx","line":63,"severity":"LOW","category":"accessibility","title":"Page wrapper uses div instead of semantic main","description":"Root div should be main element.","recommendation":"Change div to main.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-052","zone":"B-Sections","file":"src/components/ferrum/sections/platform-architecture.tsx","line":174,"severity":"LOW","category":"accessibility","title":"Page wrapper uses div instead of semantic main","description":"Root div should be main element.","recommendation":"Change div to main.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-053","zone":"B-Sections","file":"src/components/ferrum/sections/enterprise.tsx","line":74,"severity":"LOW","category":"accessibility","title":"Page wrapper uses div instead of semantic main","description":"Root div should be main element.","recommendation":"Change div to main.","effort":"SMALL","team":"Hotel"},
    {"id":"AUDIT-B-054","zone":"B-Sections","file":"src/components/ferrum/sections/home/playground-section.tsx","line":86,"severity":"LOW","category":"mobile","title":"Playground grid may be cramped on medium screens","description":"No medium breakpoint between md and lg.","recommendation":"Add md breakpoint for compact layout.","effort":"SMALL","team":"Golf"},
    {"id":"AUDIT-B-055","zone":"B-Sections","file":"src/components/ferrum/sections/platform-architecture.tsx","line":268,"severity":"LOW","category":"content","title":"Framework count 8 stable + 1 beta contradicts hero badge 8","description":"Three different sources list different framework counts.","recommendation":"Align hero badge or clarify stable vs total.","effort":"SMALL","team":"India"},
    {"id":"AUDIT-B-056","zone":"B-Sections","file":"src/components/ferrum/sections/home/hero-section.tsx","line":33,"severity":"LOW","category":"accessibility","title":"Hero grid overlay uses hardcoded rgba assuming light background","description":"rgba(255,255,255,0.1) may look wrong in dark mode.","recommendation":"Use CSS custom properties or dark: variants.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-B-057","zone":"B-Sections","file":"src/components/ferrum/sections/learning-center.tsx","line":223,"severity":"LOW","category":"placeholder","title":"Bottom CTA mentions coming soon learning paths","description":"Indicates page is incomplete.","recommendation":"Remove coming-soon text or add timeline.","effort":"SMALL","team":"India"},
    {"id":"AUDIT-B-058","zone":"B-Sections","file":"src/components/ferrum/sections/home/roadmap-section.tsx","line":27,"severity":"LOW","category":"content","title":"Roadmap legend missing Planned status indicator","description":"5 status styles but legend shows only 4.","recommendation":"Add Planned entry to legend.","effort":"SMALL","team":"India"},

    # === ZONE C: Views (37 findings) ===
    {"id":"AUDIT-C-001","zone":"C-Views","file":"src/components/ferrum/nav.tsx","line":463,"severity":"MEDIUM","category":"missing-feature","title":"Search button disabled with coming soon label","description":"Permanently disabled, invisible to keyboard users.","recommendation":"Implement search or use aria-disabled for discoverability.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-002","zone":"C-Views","file":"src/components/ferrum/nav.tsx","line":587,"severity":"LOW","category":"placeholder","title":"Multiple nav menu items show Coming soon in mobile view","description":"7 of 8 platform menu items have no navigation target.","recommendation":"Add view targets or consolidate under Roadmap.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-C-003","zone":"C-Views","file":"src/components/ferrum/nav.tsx","line":230,"severity":"LOW","category":"performance","title":"Nav scroll listener lacks rAF throttling","description":"Direct setState on every scroll event.","recommendation":"Add requestAnimationFrame throttling.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-004","zone":"C-Views","file":"src/components/ferrum/nav-data.ts","line":15,"severity":"LOW","category":"missing-feature","title":"Most platform menu items lack navigation targets","description":"7 of 8 items have neither view nor href.","recommendation":"Add navigation targets or consolidate.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-C-005","zone":"C-Views","file":"src/components/ferrum/effects-view.tsx","line":12,"severity":"LOW","category":"dead-code","title":"Module-level alias effectsIndex duplicates effects import","description":"Type-cast alias could use import as syntax.","recommendation":"Remove alias, use import as.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-006","zone":"C-Views","file":"src/components/ferrum/effects-view.tsx","line":749,"severity":"MEDIUM","category":"dead-code","title":"useEffectsState() hook duplicates AppContext functionality","description":"Likely leftover from prior refactor.","recommendation":"Remove if unused, or migrate to AppContext.","effort":"MEDIUM","team":"Bravo"},
    {"id":"AUDIT-C-007","zone":"C-Views","file":"src/components/ferrum/effects-view.tsx","line":633,"severity":"LOW","category":"dead-code","title":"EffectsView destructures unused props","description":"collectionOpen, remove, clear accepted but unused.","recommendation":"Remove unused props from interface and call site.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-008","zone":"C-Views","file":"src/components/ferrum/effects-view.tsx","line":772,"severity":"MEDIUM","category":"performance","title":"useEffectsState localStorage calls lack try/catch","description":"Will crash in Safari private mode or quota exceeded.","recommendation":"Wrap localStorage calls in try/catch.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-009","zone":"C-Views","file":"src/components/ferrum/effects-view.tsx","line":444,"severity":"LOW","category":"accessibility","title":"PlaygroundPanel select elements lack proper labeling","description":"No id/htmlFor association or aria-label.","recommendation":"Add id and htmlFor or aria-label.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-010","zone":"C-Views","file":"src/components/ferrum/effects-view.tsx","line":229,"severity":"LOW","category":"dead-code","title":"HeartButton compact ternary always returns same size","description":"Both branches of ternary are identical.","recommendation":"Remove ternary or make compact change the size.","effort":"TRIVIAL","team":"Alpha"},
    {"id":"AUDIT-C-011","zone":"C-Views","file":"src/components/ferrum/docs-view.tsx","line":331,"severity":"LOW","category":"content","title":"Docs sidebar shows hardcoded v1.0 version","description":"Will drift from actual version.","recommendation":"Extract from package.json.","effort":"TRIVIAL","team":"Alpha"},
    {"id":"AUDIT-C-012","zone":"C-Views","file":"src/components/ferrum/docs-view.tsx","line":231,"severity":"LOW","category":"content","title":"Docs sidebar shows MIT License without link","description":"No link to actual license file.","recommendation":"Link to LICENSE or remove.","effort":"TRIVIAL","team":"Alpha"},
    {"id":"AUDIT-C-013","zone":"C-Views","file":"src/components/ferrum/architecture-deep-dive.tsx","line":348,"severity":"LOW","category":"dead-code","title":"sidebarOpen state always true, setter unused","description":"Dead state — never changes.","recommendation":"Replace with constant or wire up toggle.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-014","zone":"C-Views","file":"src/components/ferrum/architecture-deep-dive.tsx","line":519,"severity":"MEDIUM","category":"performance","title":"Inline color-to-RGB ternary chain is unmaintainable","description":"9-color ternary duplicates COLOR_STYLES data.","recommendation":"Add rgb field to ColorStyle and use directly.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-015","zone":"C-Views","file":"src/components/ferrum/architecture-deep-dive.tsx","line":60,"severity":"LOW","category":"dead-code","title":"getColor fallback chain has redundant null coalescing","description":"Third fallback is unreachable.","recommendation":"Simplify to two-operand chain.","effort":"TRIVIAL","team":"Alpha"},
    {"id":"AUDIT-C-016","zone":"C-Views","file":"src/components/ferrum/architecture-deep-dive.tsx","line":152,"severity":"LOW","category":"performance","title":"231 individual SVG circles for grid dots","description":"Re-rendered on every diagram update.","recommendation":"Use SVG pattern element or memoize.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-017","zone":"C-Views","file":"src/components/ferrum/architecture-deep-dive.tsx","line":12,"severity":"LOW","category":"style","title":"NoScrollbarStyles uses imperative DOM style injection","description":"Fragile, doesn't integrate with Tailwind v4.","recommendation":"Move to globals.css or Tailwind utility.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-018","zone":"C-Views","file":"src/components/ferrum/architecture-data.ts","line":1,"severity":"MEDIUM","category":"performance","title":"120KB architecture data file loaded for single view","description":"Large inline data imported synchronously.","recommendation":"Extract per-subsystem or lazy load.","effort":"LARGE","team":"Bravo"},
    {"id":"AUDIT-C-019","zone":"C-Views","file":"src/components/ferrum/playground-v2-data.ts","line":1,"severity":"HIGH","category":"type-safety","title":"@ts-nocheck on 804-line playground data file","description":"Disables all type checking including code generation.","recommendation":"Fix strict errors and remove @ts-nocheck.","effort":"MEDIUM","team":"Bravo"},
    {"id":"AUDIT-C-020","zone":"C-Views","file":"src/components/ferrum/playground-v2-data.ts","line":727,"severity":"LOW","category":"security","title":"Generated Web Component code uses innerHTML","description":"XSS vector if users deploy generated code without sanitizing.","recommendation":"Add XSS warning comment or use safer DOM approach.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-021","zone":"C-Views","file":"src/components/ferrum/playground-v2-data.ts","line":163,"severity":"LOW","category":"consistency","title":"EXPORT_FORMATS uses string names vs LucideIcon references","description":"Inconsistent with PLAYGROUND_COMPONENTS pattern.","recommendation":"Use actual LucideIcon references or document.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-022","zone":"C-Views","file":"src/components/ferrum/app-context.tsx","line":12,"severity":"MEDIUM","category":"consistency","title":"AppContext imports type from effects-view instead of lib","description":"Layering violation — context depends on view component.","recommendation":"Import from @/lib/ferrum-effects-index.","effort":"TRIVIAL","team":"Alpha"},
    {"id":"AUDIT-C-023","zone":"C-Views","file":"src/components/ferrum/app-context.tsx","line":99,"severity":"LOW","category":"performance","title":"isInCollection uses O(n) array.includes","description":"Called for every visible effect card.","recommendation":"Convert to Set for O(1) lookups.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-024","zone":"C-Views","file":"src/components/ferrum/color-customizer.tsx","line":196,"severity":"LOW","category":"accessibility","title":"Hex input field lacks proper label association","description":"No id or associated label element.","recommendation":"Add aria-label to input.","effort":"TRIVIAL","team":"Alpha"},
    {"id":"AUDIT-C-025","zone":"C-Views","file":"src/components/ferrum/color-customizer.tsx","line":86,"severity":"LOW","category":"accessibility","title":"Color picker panel lacks ARIA dialog role","description":"No role=dialog or aria-modal.","recommendation":"Add role=dialog aria-label.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-026","zone":"C-Views","file":"src/components/ferrum/seo-content.tsx","line":49,"severity":"LOW","category":"content","title":"SEO links use hard-coded paths not matching SPA routing","description":"Paths don't resolve for crawlers.","recommendation":"Add nofollow or use fragment identifiers.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-027","zone":"C-Views","file":"src/components/ferrum/icons.ts","line":201,"severity":"LOW","category":"consistency","title":"ICON_COUNT (113) may be stale — no automated verification","description":"Hardcoded count with no CI check.","recommendation":"Add build-time verification or remove constant.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-C-028","zone":"C-Views","file":"src/components/ferrum/scroll-reveal.tsx","line":236,"severity":"LOW","category":"accessibility","title":"StaggerItem uses Math.random for ID instead of useId","description":"Potentially unstable in React strict mode.","recommendation":"Use React useId().","effort":"TRIVIAL","team":"Alpha"},
    {"id":"AUDIT-C-029","zone":"C-Views","file":"src/components/ferrum/scroll-reveal.tsx","line":19,"severity":"LOW","category":"style","title":"Keyframes injected imperatively at module scope","description":"SSR-incompatible, fragile.","recommendation":"Move to globals.css.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-030","zone":"C-Views","file":"src/components/ferrum/scroll-progress.tsx","line":59,"severity":"LOW","category":"accessibility","title":"Scroll-to-top SVG lacks aria-hidden","description":"Decorative SVG should be hidden.","recommendation":"Add aria-hidden=true to SVG.","effort":"TRIVIAL","team":"Alpha"},
    {"id":"AUDIT-C-031","zone":"C-Views","file":"src/components/ferrum/animated-components.tsx","line":82,"severity":"LOW","category":"performance","title":"shouldReducMotion() not reactive to runtime preference changes","description":"No change listener on matchMedia.","recommendation":"Add change event listener.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-032","zone":"C-Views","file":"src/components/ferrum/sections/index.ts","line":1,"severity":"LOW","category":"consistency","title":"Barrel file comment references wrong file","description":"Comment about platform-homepage.tsx is inaccurate.","recommendation":"Update or remove comment.","effort":"TRIVIAL","team":"Alpha"},
    {"id":"AUDIT-C-033","zone":"C-Views","file":"src/components/ferrum/docs-view.tsx","line":211,"severity":"LOW","category":"accessibility","title":"DocContent list items render plain text only","description":"No inline markup support in lists.","recommendation":"Extend type to support rich inline content.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-C-034","zone":"C-Views","file":"src/components/ferrum/architecture-deep-dive.tsx","line":389,"severity":"MEDIUM","category":"accessibility","title":"Architecture deep-dive overlay has autoFocus but no focus trap","description":"Tab can escape the overlay to background content.","recommendation":"Implement focus trap.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-C-035","zone":"C-Views","file":"src/components/ferrum/playground-v2.tsx","line":1,"severity":"LOW","category":"consistency","title":"playground-v2.tsx is a trivial re-export file","description":"One-line re-export adds indirection.","recommendation":"Import directly or add versioning comment.","effort":"TRIVIAL","team":"Alpha"},
    {"id":"AUDIT-C-036","zone":"C-Views","file":"src/components/ferrum/effects-view.tsx","line":375,"severity":"LOW","category":"performance","title":"EffectDetailModal re-imports effects data on every open","description":"Dynamic import unnecessary overhead for already-loaded module.","recommendation":"Import at module level or cache reference.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-C-037","zone":"C-Views","file":"src/components/ferrum/architecture-deep-dive.tsx","line":325,"severity":"LOW","category":"type-safety","title":"TabContent unsafe string index access on subsystem","description":"as string cast hides potential undefined.","recommendation":"Use proper type-safe accessor.","effort":"SMALL","team":"Alpha"},

    # === ZONE D: Lib/Utils (16 findings) ===
    {"id":"AUDIT-D-001","zone":"D-LibUtils","file":"src/lib/cloud-store.ts","line":1,"severity":"MEDIUM","category":"type-safety","title":"@ts-nocheck on cloud-store.ts","description":"Disables type safety for entire CloudStore class.","recommendation":"Fix strict errors and remove @ts-nocheck.","effort":"MEDIUM","team":"Delta"},
    {"id":"AUDIT-D-002","zone":"D-LibUtils","file":"src/lib/ferrum-effects-loader.ts","line":1,"severity":"MEDIUM","category":"type-safety","title":"@ts-nocheck on ferrum-effects-loader.ts","description":"Unsafe double-cast hidden.","recommendation":"Fix strict errors and remove @ts-nocheck.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-D-003","zone":"D-LibUtils","file":"src/lib/types.ts","line":78,"severity":"MEDIUM","category":"consistency","title":"Duplicate type definitions across three files","description":"Types defined identically in types.ts, cloud-store.ts, and effects files.","recommendation":"Import from types.ts as single source of truth.","effort":"MEDIUM","team":"Delta"},
    {"id":"AUDIT-D-004","zone":"D-LibUtils","file":"src/lib/web-vitals.tsx","line":8,"severity":"CRITICAL","category":"broken-ref","title":"Web vitals payload missing navigationType — analytics always rejects","description":"Analytics endpoint requires navigationType field that web vitals don't provide. All vitals silently dropped.","recommendation":"Remove navigationType from EXPECTED_FIELDS in analytics/route.ts.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-D-005","zone":"D-LibUtils","file":"src/lib/web-vitals.tsx","line":8,"severity":"MEDIUM","category":"placeholder","title":"Analytics endpoint is no-op — no data persisted","description":"Only console.log, no storage. Combined with D-004, completely non-functional.","recommendation":"Add actual storage or document as intentional.","effort":"LARGE","team":"Delta"},
    {"id":"AUDIT-D-006","zone":"D-LibUtils","file":"src/lib/docs-data.ts","line":144,"severity":"MEDIUM","category":"content","title":"Category count table sums to 806, not stated 542; shows 11 not 35 categories","description":"Table is factually incorrect.","recommendation":"Update table to match actual 35 categories and 542 effects.","effort":"MEDIUM","team":"Delta"},
    {"id":"AUDIT-D-007","zone":"D-LibUtils","file":"src/lib/cloud-store.ts","line":373,"severity":"MEDIUM","category":"error-handling","title":"__resetCloudStoreForTests comment says it clears file but it does not","description":"Only sets store=null, file persists.","recommendation":"Add fs.unlinkSync or fix comment.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-D-008","zone":"D-LibUtils","file":"src/lib/cloud-store.ts","line":293,"severity":"MEDIUM","category":"missing-feature","title":"deleteTeam does not cascade — orphaned data remains","description":"Projects, tokens, components, members not cleaned up.","recommendation":"Add cascade deletion.","effort":"MEDIUM","team":"Delta"},
    {"id":"AUDIT-D-009","zone":"D-LibUtils","file":"src/lib/persist.ts","line":64,"severity":"LOW","category":"style","title":"Mixed import styles — require() alongside ES module import","description":"Inconsistent require vs import.","recommendation":"Use ES module imports consistently.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-D-010","zone":"D-LibUtils","file":"src/hooks/use-effect-once.ts","line":10,"severity":"LOW","category":"performance","title":"fn in useEffect dependency array causes unnecessary effect re-runs","description":"New function ref each render despite ran.current guard.","recommendation":"Remove fn from deps or require memoized callback.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-D-011","zone":"D-LibUtils","file":"src/lib/ferrum-effects-loader.ts","line":19,"severity":"LOW","category":"style","title":"Unnecessary non-null assertion on cached return","description":"_cache! assertion is redundant after early return guard.","recommendation":"Change to return _cache.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-D-012","zone":"D-LibUtils","file":"src/lib/ferrum-effects-data.ts","line":7,"severity":"LOW","category":"consistency","title":"FerrumCSSEffect and Category redefined locally instead of imported from types.ts","description":"Duplicate interface definitions.","recommendation":"Import from types.ts.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-D-013","zone":"D-LibUtils","file":"src/lib/ferrum-effects-index.ts","line":7,"severity":"LOW","category":"consistency","title":"ferrum-effects-index.ts redefines interfaces already in types.ts","description":"Third location for same interfaces.","recommendation":"Import from types.ts.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-D-014","zone":"D-LibUtils","file":"src/lib/cloud-store.ts","line":82,"severity":"LOW","category":"security","title":"ID generation uses Math.random() — not cryptographically secure","description":"Predictable IDs could be enumerated.","recommendation":"Use crypto.randomUUID().","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-D-015","zone":"D-LibUtils","file":"src/lib/animation-colors.ts","line":1,"severity":"LOW","category":"content","title":"Hardcoded RGBA color values should use design tokens","description":"Duplicates Tailwind palette, won't update with theme.","recommendation":"Generate from design token system.","effort":"MEDIUM","team":"Delta"},
    {"id":"AUDIT-D-016","zone":"D-LibUtils","file":"src/lib/performance-budget.ts","line":36,"severity":"LOW","category":"content","title":"CSS soft limit (200KB) exceeds hard limit (80KB) — values likely swapped","description":"Soft limit should be <= hard limit.","recommendation":"Swap values or correct naming.","effort":"SMALL","team":"Delta"},

    # === ZONE E: API Routes (20 findings) ===
    {"id":"AUDIT-E-001","zone":"E-API","file":"src/app/api/cloud/auth/route.ts","line":59,"severity":"HIGH","category":"error-handling","title":"Auth catch block masks missing env var error as Invalid request body","description":"Server misconfiguration hidden behind 400 client error.","recommendation":"Separate JSON parse errors from config errors.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-002","zone":"E-API","file":"src/app/api/cloud/auth/route.ts","line":45,"severity":"HIGH","category":"security","title":"Auth returns static shared secret as bearer token — no expiry or rotation","description":"Fake expires_in: 86400. Token never expires.","recommendation":"Use JWT or per-session tokens, or document limitation.","effort":"LARGE","team":"Delta"},
    {"id":"AUDIT-E-003","zone":"E-API","file":"src/app/api/cloud/teams/route.ts","line":15,"severity":"MEDIUM","category":"error-handling","title":"POST /teams does not handle JSON parse errors","description":"Malformed JSON causes 500 instead of 400.","recommendation":"Wrap req.json() in try/catch. Applies to 6 endpoints.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-004","zone":"E-API","file":"src/app/api/cloud/teams/[teamId]/projects/route.ts","line":27,"severity":"MEDIUM","category":"missing-feature","title":"createProject does not validate parent team exists","description":"Can create project with nonexistent teamId.","recommendation":"Add team existence check.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-005","zone":"E-API","file":"src/app/api/cloud/projects/[projectId]/tokens/route.ts","line":31,"severity":"MEDIUM","category":"missing-feature","title":"createToken does not validate parent project exists","description":"Can create token with nonexistent projectId.","recommendation":"Add project existence check.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-006","zone":"E-API","file":"src/app/api/cloud/tokens/[tokenId]/route.ts","line":8,"severity":"MEDIUM","category":"security","title":"Token update endpoint has no input validation","description":"Raw body passed directly to store with @ts-nocheck.","recommendation":"Validate fields before passing to store.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-007","zone":"E-API","file":"src/app/api/route.ts","line":13,"severity":"MEDIUM","category":"content","title":"API root examples use wrong effect name prefix and format","description":"fade-in should be rc-fade-up; format=minified should be minified=true.","recommendation":"Fix example URLs.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-008","zone":"E-API","file":"src/app/api/health/route.ts","line":41,"severity":"LOW","category":"dead-code","title":"Duplicate getTeams() call — second is dead code","description":"Return value discarded.","recommendation":"Remove duplicate call.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-009","zone":"E-API","file":"src/app/api/health/route.ts","line":28,"severity":"LOW","category":"consistency","title":"VERSION 1.0.0 in health vs 0.0.1 in tokens endpoint","description":"Two different hardcoded versions.","recommendation":"Read from package.json.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-010","zone":"E-API","file":"src/app/api/route.ts","line":2,"severity":"HIGH","category":"performance","title":"API root imports full 3854-line effects data file just for counts","description":"Only needs effects.length and categories.length.","recommendation":"Import from ferrum-effects-index instead.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-011","zone":"E-API","file":"src/app/api/tokens/route.ts","line":6,"severity":"MEDIUM","category":"type-safety","title":"Excessive as Record<string, unknown> casts bypass type safety","description":"Tokens module has proper types.","recommendation":"Use proper typing from token definitions.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-012","zone":"E-API","file":"src/app/api/tokens/route.ts","line":25,"severity":"MEDIUM","category":"performance","title":"Token samples response dumps full color/spacing objects","description":"Large payload on every request.","recommendation":"Make samples opt-in via query parameter.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-013","zone":"E-API","file":"src/app/api/analytics/route.ts","line":4,"severity":"MEDIUM","category":"performance","title":"Analytics rate limiter has no cleanup — memory leak","description":"Map grows unbounded with no expiry.","recommendation":"Add periodic cleanup like proxy.ts.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-014","zone":"E-API","file":"src/app/api/cloud/teams/[teamId]/route.ts","line":20,"severity":"LOW","category":"security","title":"PUT team passes raw body to updateTeam without validation","description":"Extra fields silently ignored.","recommendation":"Extract and validate only expected fields.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-015","zone":"E-API","file":"src/app/api/cloud/audit/route.ts","line":7,"severity":"LOW","category":"consistency","title":"Audit endpoint uses unusual double-fallback parseInt pattern","description":"Works correctly but worth documenting.","recommendation":"Add explanatory comment.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-016","zone":"E-API","file":"src/app/api/css/route.ts","line":63,"severity":"LOW","category":"performance","title":"Category count O(categories x effects) instead of O(effects)","description":"~19K iterations instead of 542.","recommendation":"Use single-pass reduce with Map.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-017","zone":"E-API","file":"src/app/api/cloud/projects/[projectId]/tokens/route.ts","line":26,"severity":"LOW","category":"consistency","title":"Token type validation duplicates TokenType union","description":"Hardcoded array duplicates type definition.","recommendation":"Import from types.ts.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-018","zone":"E-API","file":"src/app/api/cloud/tokens/[tokenId]/route.ts","line":1,"severity":"LOW","category":"consistency","title":"Token update route has no JSON parse error handling","description":"Malformed JSON causes 500.","recommendation":"Wrap req.json() in try/catch.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-019","zone":"E-API","file":"src/app/api/css/route.ts","line":104,"severity":"LOW","category":"consistency","title":"JSON response from /api/css lacks CORS header","description":"CSS response has CORS but JSON doesn't.","recommendation":"Add CORS header to JSON response.","effort":"SMALL","team":"Delta"},
    {"id":"AUDIT-E-020","zone":"E-API","file":"src/app/api/cloud/teams/[teamId]/route.ts","line":1,"severity":"LOW","category":"error-handling","title":"PUT team handler does not handle JSON parse errors","description":"Malformed JSON causes 500.","recommendation":"Wrap req.json() in try/catch.","effort":"SMALL","team":"Delta"},

    # === ZONE F: UI + Playground (30 findings) ===
    {"id":"AUDIT-F-001","zone":"F-UI","file":"src/components/ui/tooltip.tsx","line":1,"severity":"CRITICAL","category":"placeholder","title":"Tooltip is non-functional stub — REM-002 confirmed open","description":"Pure passthrough fragments. Tooltips never appear.","recommendation":"Replace with @radix-ui/react-tooltip.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-F-002","zone":"F-UI","file":"src/components/ui/select.tsx","line":1,"severity":"HIGH","category":"placeholder","title":"Select has fake compound component API — REM-002 confirmed open","description":"SelectTrigger/Content/Item render nothing. Only native select works.","recommendation":"Replace with @radix-ui/react-select or document limitation.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-F-003","zone":"F-UI","file":"src/components/ui/scroll-area.tsx","line":5,"severity":"HIGH","category":"placeholder","title":"ScrollArea is minimal stub — just overflow-y-auto div","description":"No sub-components, no custom scrollbar.","recommendation":"Replace with @radix-ui/react-scroll-area.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-F-004","zone":"F-UI","file":"src/components/ui/slider.tsx","line":5,"severity":"HIGH","category":"placeholder","title":"Slider is native range input stub — REM-002 confirmed open","description":"Vertical orientation broken, multi-thumb API fake, hardcoded color.","recommendation":"Replace with @radix-ui/react-slider.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-F-005","zone":"F-Playground","file":"src/components/ferrum/playground/index.tsx","line":95,"severity":"HIGH","category":"dead-code","title":"showA11y/showMetrics/showAI props accepted but never used","description":"Dead circuit: state toggled but never read.","recommendation":"Wire up conditional rendering or remove.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-006","zone":"F-Playground","file":"src/components/ferrum/playground/index.tsx","line":731,"severity":"MEDIUM","category":"missing-feature","title":"Two resize handles have noop callbacks — panels not resizable","description":"Users try to drag but nothing happens.","recommendation":"Implement resize state and handlers.","effort":"MEDIUM","team":"Echo"},
    {"id":"AUDIT-F-007","zone":"F-Playground","file":"src/components/ferrum/playground/code-editor.tsx","line":95,"severity":"HIGH","category":"security","title":"dangerouslySetInnerHTML without sanitization for user-edited code","description":"XSS risk if syntaxHighlight doesn't escape properly.","recommendation":"Audit syntaxHighlight for proper HTML escaping.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-008","zone":"F-Playground","file":"src/components/ferrum/playground/index.tsx","line":1,"severity":"HIGH","category":"type-safety","title":"@ts-nocheck on 829-line playground index","description":"All type checking disabled for complex component.","recommendation":"Remove @ts-nocheck and fix strict errors.","effort":"LARGE","team":"Echo"},
    {"id":"AUDIT-F-009","zone":"F-UI","file":"src/components/ui/select.tsx","line":1,"severity":"MEDIUM","category":"type-safety","title":"@ts-nocheck on Select hides deeper type unsafety","description":"Child.type comparison and child.props casting unsafe.","recommendation":"Remove @ts-nocheck, add proper type guards.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-F-010","zone":"F-UI","file":"src/components/ui/tooltip.tsx","line":1,"severity":"MEDIUM","category":"type-safety","title":"@ts-nocheck on Tooltip stub","description":"All type checking disabled.","recommendation":"Remove @ts-nocheck or replace with Radix.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-F-011","zone":"F-Playground","file":"src/components/ferrum/playground/preview-panel.tsx","line":1,"severity":"MEDIUM","category":"type-safety","title":"@ts-nocheck on preview panel","description":"82 lines untyped.","recommendation":"Remove @ts-nocheck and fix strict errors.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-012","zone":"F-Playground","file":"src/components/ferrum/playground/effect-sidebar.tsx","line":1,"severity":"MEDIUM","category":"type-safety","title":"@ts-nocheck on effect sidebar","description":"250 lines untyped.","recommendation":"Remove @ts-nocheck and fix strict errors.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-013","zone":"F-Playground","file":"src/components/ferrum/playground/effect-sidebar.tsx","line":19,"severity":"MEDIUM","category":"dead-code","title":"ACTIVITY_ICONS constant declared but never used","description":"Unused constant.","recommendation":"Delete unused constant.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-014","zone":"F-Playground","file":"src/components/ferrum/playground/toolbar.tsx","line":32,"severity":"MEDIUM","category":"dead-code","title":"exportRef and shortcutsRef created but never read","description":"Write-only refs — no click-outside handler.","recommendation":"Implement click-outside or remove refs.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-015","zone":"F-Playground","file":"src/components/ferrum/playground/index.tsx","line":164,"severity":"MEDIUM","category":"dark-mode","title":"Easing curve SVG grid uses hardcoded white rgba — invisible in light mode","description":"Grid lines invisible on light background.","recommendation":"Use CSS variable or conditional color.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-016","zone":"F-Playground","file":"src/components/ferrum/playground/preview-panel.tsx","line":63,"severity":"MEDIUM","category":"dark-mode","title":"Checkerboard background uses hardcoded white rgba — invisible in light mode","description":"White-on-white at 2% opacity imperceptible.","recommendation":"Use dark: variant or conditional.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-017","zone":"F-Playground","file":"src/components/ferrum/playground/index.tsx","line":395,"severity":"MEDIUM","category":"accessibility","title":"Reduced motion toggle lacks ARIA switch semantics","description":"No role=switch, aria-checked, or aria-label.","recommendation":"Add role=switch, aria-checked, aria-label.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-018","zone":"F-Playground","file":"src/components/ferrum/playground/index.tsx","line":76,"severity":"MEDIUM","category":"accessibility","title":"Controls panel sections lack aria-expanded","description":"Toggle buttons missing aria-expanded.","recommendation":"Add aria-expanded to section toggles.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-019","zone":"F-Playground","file":"src/components/ferrum/playground/toolbar.tsx","line":122,"severity":"MEDIUM","category":"accessibility","title":"Export dropdown has no keyboard nav or focus management","description":"No role=menu, no role=menuitem, no focus trap.","recommendation":"Add ARIA menu pattern and focus management.","effort":"MEDIUM","team":"Echo"},
    {"id":"AUDIT-F-020","zone":"F-Playground","file":"src/components/ferrum/playground/effect-sidebar.tsx","line":62,"severity":"LOW","category":"missing-feature","title":"Settings button in ActivityBar has no onClick handler","description":"Placeholder button does nothing.","recommendation":"Implement settings or remove button.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-021","zone":"F-UI","file":"src/components/ui/skeleton.tsx","line":3,"severity":"LOW","category":"consistency","title":"Skeleton uses React.ComponentProps without importing React","description":"Inconsistent with all other UI components.","recommendation":"Add React import for consistency.","effort":"SMALL","team":"Alpha"},
    {"id":"AUDIT-F-022","zone":"F-Playground","file":"src/components/ferrum/playground/index.tsx","line":824,"severity":"LOW","category":"consistency","title":"Status bar hardcodes 542+ effects instead of using actual count","description":"Static string won't update if effects change.","recommendation":"Use effectsList.length.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-023","zone":"F-Playground","file":"src/components/ferrum/playground/preview-panel.tsx","line":72,"severity":"MEDIUM","category":"security","title":"iframe sandbox allows scripts — potential XSS if custom code reflected","description":"allow-scripts permits JS execution in preview.","recommendation":"Evaluate if allow-scripts is needed for CSS animations.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-024","zone":"F-Playground","file":"src/components/ferrum/playground/index.tsx","line":637,"severity":"LOW","category":"performance","title":"Metrics computation runs DOMParser on every preview change","description":"Expensive parsing on every state change.","recommendation":"Debounce metrics computation.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-025","zone":"F-Playground","file":"src/components/ferrum/playground/types.ts","line":15,"severity":"LOW","category":"type-safety","title":"computeContrast crashes on non-hex color input","description":"parseInt on non-hex returns NaN.","recommendation":"Add input validation for hex format.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-026","zone":"F-UI","file":"src/components/ui/select.tsx","line":27,"severity":"MEDIUM","category":"consistency","title":"Select breaks if SelectItem wrapped in fragment or HOC","description":"child.type comparison is fragile.","recommendation":"Use more robust extraction or replace with Radix.","effort":"MEDIUM","team":"Alpha"},
    {"id":"AUDIT-F-027","zone":"F-Playground","file":"src/components/ferrum/playground/index.tsx","line":470,"severity":"LOW","category":"placeholder","title":"AI Assistant section is non-functional placeholder","description":"Coming in v2.1 with disabled input.","recommendation":"Hide until v2.1 or don't expand by default.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-028","zone":"F-Playground","file":"src/components/ferrum/playground/index.tsx","line":404,"severity":"LOW","category":"consistency","title":"First contrast ratio entry uses hardcoded fake data","description":"14.2:1 AAA doesn't update with theme colors.","recommendation":"Compute dynamically from theme colors.","effort":"SMALL","team":"Echo"},
    {"id":"AUDIT-F-029","zone":"F-Playground","file":"src/components/ferrum/playground/toolbar.tsx","line":150,"severity":"LOW","category":"accessibility","title":"Shortcuts dialog does not trap focus","description":"Has role=dialog but no focus trap.","recommendation":"Add focus trap effect.","effort":"MEDIUM","team":"Echo"},
    {"id":"AUDIT-F-030","zone":"F-Playground","file":"src/components/ferrum/playground/toolbar.tsx","line":155,"severity":"LOW","category":"accessibility","title":"Keyboard shortcuts dialog uses Mac-only Command symbol","description":"Windows/Linux users see incorrect shortcut labels.","recommendation":"Detect OS or use universal Mod+ format.","effort":"SMALL","team":"Echo"},
]

# Build the master backlog
backlog = {
    "meta": {
        "generated": datetime.now(timezone.utc).isoformat(),
        "version": "2.0",
        "priorFixes": 58,
        "priorAccepted": 10,
        "totalNewFindings": len(findings),
    },
    "summary": {
        "by_severity": {},
        "by_zone": {},
        "by_category": {},
        "by_team": {},
    },
    "findings": findings,
}

for f in findings:
    s = f["severity"]
    backlog["summary"]["by_severity"][s] = backlog["summary"]["by_severity"].get(s, 0) + 1
    z = f["zone"]
    backlog["summary"]["by_zone"][z] = backlog["summary"]["by_zone"].get(z, 0) + 1
    c = f["category"]
    backlog["summary"]["by_category"][c] = backlog["summary"]["by_category"].get(c, 0) + 1
    t = f["team"]
    backlog["summary"]["by_team"][t] = backlog["summary"]["by_team"].get(t, 0) + 1

# Categorize for action
actionable = [f for f in findings if f["effort"] != "N/A"]
by_effort = {}
for f in actionable:
    e = f["effort"]
    by_effort[e] = by_effort.get(e, 0) + 1
backlog["summary"]["by_effort"] = by_effort
backlog["summary"]["actionable"] = len(actionable)

out = Path("/home/z/my-project/download/master-backlog.json")
out.parent.mkdir(parents=True, exist_ok=True)
with open(out, "w") as fp:
    json.dump(backlog, fp, indent=2)

print(f"Master backlog: {len(findings)} findings written to {out}")
print(f"By severity: {backlog['summary']['by_severity']}")
print(f"By zone: {backlog['summary']['by_zone']}")
print(f"By effort: {by_effort}")
print(f"Actionable: {len(actionable)}")
